/**
 * Canonical-upload certification harness: sign a fixture user in for LOCALHOST journeys.
 *
 * Two methods, both producing the exact `sb-<ref>-auth-token[.N]` cookies @supabase/ssr writes
 * (they are generated BY @supabase/ssr's own createServerClient, so chunking/encoding match the app):
 *
 *   mint      service role -> auth.admin.generateLink({type:'magiclink'}) -> verifyOtp(token_hash).
 *             No password is used or known. Sends no email (generateLink never sends mail).
 *             Refuses unless the user ALREADY EXISTS (so it can never create an account).
 *   password  the FCAST fixture password, read at runtime from the gitignored fixture file.
 *
 * The session file (.canonical-cert/session-<email>.json, gitignored) holds live tokens: never print
 * it, never commit it. `revoke()` ends the session server-side when the journey is done.
 *
 * `api()` calls the LOCALHOST app with the cookies and folds any refreshed Set-Cookie back into the
 * session file, so a journey longer than the 1h access-token lifetime keeps working.
 */
import fs from 'node:fs';
import path from 'node:path';
import { loadDevEnv, serviceClient } from './env.mjs';
import { fixturePassword } from './users.mjs';

const SESSION_DIR = () => process.env.CERT_LEDGER_DIR ?? path.resolve(process.cwd(), '.canonical-cert');
const sessionFile = (email) => path.join(SESSION_DIR(), `session-${email.replace(/[^a-z0-9._-]/gi, '_')}.json`);

async function ssrClientCapturing() {
  const { createServerClient } = await import('@supabase/ssr');
  const { url, anonKey } = loadDevEnv();
  const jar = new Map();
  const client = createServerClient(url, anonKey, {
    cookies: {
      getAll: () => [...jar.entries()].map(([name, value]) => ({ name, value })),
      setAll: (list) => list.forEach(({ name, value }) => (value ? jar.set(name, value) : jar.delete(name))),
    },
  });
  return { client, jar };
}

export async function signIn(email, { method = 'mint' } = {}) {
  const admin = await serviceClient();
  const { client, jar } = await ssrClientCapturing();
  let userId;
  if (method === 'mint') {
    // Existence check FIRST: generateLink must never be the thing that creates an account.
    const existing = await findUserByEmail(admin, email);
    if (!existing) throw new Error(`REFUSING: ${email} does not exist on DEV; this harness never creates accounts.`);
    const { data, error } = await admin.auth.admin.generateLink({ type: 'magiclink', email });
    if (error) throw new Error(`generateLink failed: ${error.message}`);
    const { error: verr, data: v } = await client.auth.verifyOtp({ token_hash: data.properties.hashed_token, type: data.properties.verification_type ?? 'magiclink' });
    if (verr) throw new Error(`verifyOtp failed: ${verr.message}`);
    userId = v.user?.id;
    if (userId !== existing.id) throw new Error('minted session is for a different user id -- refusing');
  } else if (method === 'password') {
    const { data, error } = await client.auth.signInWithPassword({ email, password: fixturePassword(email) });
    if (error) throw new Error(`password sign-in failed for ${email}: ${error.message}`);
    userId = data.user?.id;
  } else throw new Error(`unknown method ${method}`);
  if (jar.size === 0) throw new Error('no auth cookies were produced');
  const session = { email, userId, method, createdAt: new Date().toISOString(), cookies: Object.fromEntries(jar) };
  fs.mkdirSync(SESSION_DIR(), { recursive: true });
  fs.writeFileSync(sessionFile(email), JSON.stringify(session, null, 2));
  return { email, userId, method, cookieNames: [...jar.keys()], file: sessionFile(email) };
}

async function findUserByEmail(admin, email) {
  for (let page = 1; page < 50; page++) {
    const { data, error } = await admin.auth.admin.listUsers({ page, perPage: 1000 });
    if (error) throw error;
    const hit = data.users.find((u) => u.email === email);
    if (hit) return hit;
    if (data.users.length < 1000) return null;
  }
  return null;
}

export function loadSession(email) {
  const f = sessionFile(email);
  if (!fs.existsSync(f)) throw new Error(`no session for ${email}; run signin.mjs first`);
  return JSON.parse(fs.readFileSync(f, 'utf8'));
}

export function cookieHeader(session) {
  return Object.entries(session.cookies).map(([n, v]) => `${n}=${v}`).join('; ');
}

/** JS to paste into the Browser pane's javascript tool ON THE LOCALHOST ORIGIN to sign that tab in. */
export function browserCookieScript(session) {
  return Object.entries(session.cookies)
    .map(([n, v]) => `document.cookie = ${JSON.stringify(`${n}=${v}; path=/; SameSite=Lax`)};`)
    .join('\n');
}

/**
 * Call the localhost app as the user. Returns {status, json, text, headers}.
 * @param {string} email
 * @param {string} method
 * @param {string} route
 * @param {{ port?: number, json?: unknown, body?: BodyInit, contentType?: string, headers?: Record<string, string> }} [opts]
 * @returns {Promise<{ status: number, json: any, text: string, headers: Headers }>}
 */
export async function api(email, method, route, { port, json, body, contentType, headers = {} } = {}) {
  const session = loadSession(email);
  const base = `http://127.0.0.1:${port ?? process.env.CERT_PORT ?? 3000}`;
  const init = { method, headers: { cookie: cookieHeader(session), ...headers }, redirect: 'manual' };
  if (json !== undefined) { init.body = JSON.stringify(json); init.headers['Content-Type'] = 'application/json'; }
  else if (body !== undefined) { init.body = body; if (contentType) init.headers['Content-Type'] = contentType; }
  const res = await fetch(base + route, init);
  const setCookies = typeof res.headers.getSetCookie === 'function' ? res.headers.getSetCookie() : [];
  let changed = false;
  for (const sc of setCookies) {
    const [pair, ...attrs] = sc.split(';');
    const i = pair.indexOf('=');
    const name = pair.slice(0, i).trim(); const value = pair.slice(i + 1).trim();
    if (!name.startsWith('sb-')) continue;
    const expired = attrs.some((a) => /max-age=0/i.test(a)) || value === '';
    if (expired) delete session.cookies[name]; else session.cookies[name] = value;
    changed = true;
  }
  if (changed) fs.writeFileSync(sessionFile(email), JSON.stringify(session, null, 2));
  const text = await res.text();
  let parsed = null; try { parsed = JSON.parse(text); } catch { /* not json */ }
  return { status: res.status, json: parsed, text, headers: res.headers };
}

/** End the session server-side (local scope: only this session) and delete the session file. */
export async function revoke(email) {
  const session = loadSession(email);
  const chunk = (n) => { const m = n.match(/^sb-[a-z0-9]+-auth-token(?:\.(\d+))?$/); return m ? Number(m[1] ?? -1) : null; };
  const raw = Object.entries(session.cookies).filter(([n]) => chunk(n) !== null)
    .sort(([a], [b]) => chunk(a) - chunk(b)).map(([, v]) => v).join('');
  const decoded = raw.startsWith('base64-') ? Buffer.from(raw.slice(7), 'base64url').toString('utf8') : raw;
  const token = JSON.parse(decoded).access_token;
  const admin = await serviceClient();
  const { error } = await admin.auth.admin.signOut(token, 'local');
  fs.rmSync(sessionFile(email), { force: true });
  if (error) throw new Error(`signOut failed: ${error.message}`);
  return true;
}
