/**
 * Canonical-upload certification harness: sign a fixture user in for LOCALHOST journeys.
 *
 * Two methods, both producing the exact `sb-<ref>-auth-token[.N]` cookies @supabase/ssr writes
 * (they are generated BY @supabase/ssr's own createServerClient, so chunking/encoding match the app):
 *
 *   mint      service role -> auth.admin.generateLink({type:'magiclink'}) -> verifyOtp(token_hash).
 *             No password is used or known. Sends no email (generateLink never sends mail).
 *             Refuses unless the user ALREADY EXISTS (so it can never create an account).
 *   password  the FCAST fixture password, read at runtime from the gitignored fixture file.
 *
 * The session file (.canonical-cert/session-<email>.json, gitignored) holds live tokens: never print
 * it, never commit it. `revoke()` ends the session server-side when the journey is done.
 *
 * `api()` calls the LOCALHOST app with the cookies and folds any refreshed Set-Cookie back into the
 * session file, so a journey longer than the 1h access-token lifetime keeps working.
 */
import fs from 'node:fs';
import path from 'node:path';
import { loadDevEnv, serviceClient } from './env.mjs';
import { fixturePassword } from './users.mjs';
import { flowForDocumentType, flowForUploadRoute, legacyOwnerRoleOf, resolveSyntheticOwner, routeHasOwner, routeWithOwner } from '../../lib/syntheticOwner.mjs';

const SESSION_DIR = () => process.env.CERT_LEDGER_DIR ?? path.resolve(process.cwd(), '.canonical-cert');
const sessionFile = (email) => path.join(SESSION_DIR(), `session-${email.replace(/[^a-z0-9._-]/gi, '_')}.json`);

async function ssrClientCapturing() {
  const { createServerClient } = await import('@supabase/ssr');
  const { url, anonKey } = loadDevEnv();
  const jar = new Map();
  const client = createServerClient(url, anonKey, {
    cookies: {
      getAll: () => [...jar.entries()].map(([name, value]) => ({ name, value })),
      setAll: (list) => list.forEach(({ name, value }) => (value ? jar.set(name, value) : jar.delete(name))),
    },
  });
  return { client, jar };
}

export async function signIn(email, { method = 'mint' } = {}) {
  const admin = await serviceClient();
  const { client, jar } = await ssrClientCapturing();
  let userId;
  if (method === 'mint') {
    // Existence check FIRST: generateLink must never be the thing that creates an account.
    const existing = await findUserByEmail(admin, email);
    if (!existing) throw new Error(`REFUSING: ${email} does not exist on DEV; this harness never creates accounts.`);
    const { data, error } = await admin.auth.admin.generateLink({ type: 'magiclink', email });
    if (error) throw new Error(`generateLink failed: ${error.message}`);
    const { error: verr, data: v } = await client.auth.verifyOtp({ token_hash: data.properties.hashed_token, type: data.properties.verification_type ?? 'magiclink' });
    if (verr) throw new Error(`verifyOtp failed: ${verr.message}`);
    userId = v.user?.id;
    if (userId !== existing.id) throw new Error('minted session is for a different user id -- refusing');
  } else if (method === 'password') {
    const { data, error } = await client.auth.signInWithPassword({ email, password: fixturePassword(email) });
    if (error) throw new Error(`password sign-in failed for ${email}: ${error.message}`);
    userId = data.user?.id;
  } else throw new Error(`unknown method ${method}`);
  if (jar.size === 0) throw new Error('no auth cookies were produced');
  const session = { email, userId, method, createdAt: new Date().toISOString(), cookies: Object.fromEntries(jar) };
  fs.mkdirSync(SESSION_DIR(), { recursive: true });
  fs.writeFileSync(sessionFile(email), JSON.stringify(session, null, 2));
  return { email, userId, method, cookieNames: [...jar.keys()], file: sessionFile(email) };
}

async function findUserByEmail(admin, email) {
  for (let page = 1; page < 50; page++) {
    const { data, error } = await admin.auth.admin.listUsers({ page, perPage: 1000 });
    if (error) throw error;
    const hit = data.users.find((u) => u.email === email);
    if (hit) return hit;
    if (data.users.length < 1000) return null;
  }
  return null;
}

export function loadSession(email) {
  const f = sessionFile(email);
  if (!fs.existsSync(f)) throw new Error(`no session for ${email}; run signin.mjs first`);
  return JSON.parse(fs.readFileSync(f, 'utf8'));
}

export function cookieHeader(session) {
  return Object.entries(session.cookies).map(([n, v]) => `${n}=${v}`).join('; ');
}

/** JS to paste into the Browser pane's javascript tool ON THE LOCALHOST ORIGIN to sign that tab in. */
export function browserCookieScript(session) {
  return Object.entries(session.cookies)
    .map(([n, v]) => `document.cookie = ${JSON.stringify(`${n}=${v}; path=/; SameSite=Lax`)};`)
    .join('\n');
}

const syntheticOwnerCache = new Map();

/**
 * Owner-before-upload. Every financial-document upload route now requires the owner chosen BEFORE the file is
 * sent, so a journey that uploads must supply one. `api()` does that for the fixture user it is signed in as:
 * a POST to an owner-required upload route (or an upload-session for an owner-bearing document type) gets a
 * VALID synthetic owner -- Self by default, or the role a script asks for with `owner: 'spouse' | 'joint' |
 * 'smsf' | {wire selection}`, or the retired loose `owner_role=<role>` query value, translated. Pass
 * `owner: null` to send NO owner (the owner-required negative controls). A route that already carries an
 * `owner` is never touched.
 */
async function withSyntheticOwner(email, method, route, opts) {
  if (method !== 'POST' || opts.owner === null) return { route, opts };
  const request = async (m, r, j) => {
    const res = await rawApi(email, m, r, { port: opts.port, json: j });
    return { status: res.status, json: res.json };
  };
  const resolve = async (role, flow) => {
    const key = `${email}|${role}|${flow}`;
    if (!syntheticOwnerCache.has(key)) syntheticOwnerCache.set(key, await resolveSyntheticOwner(request, role, flow));
    return syntheticOwnerCache.get(key);
  };
  const wanted = async (flow, legacyRole) => (opts.owner && typeof opts.owner === 'object' ? opts.owner : resolve(typeof opts.owner === 'string' ? opts.owner : legacyRole ?? 'self', flow));

  const uploadFlow = flowForUploadRoute(route);
  if (uploadFlow && !routeHasOwner(route)) {
    return { route: routeWithOwner(route, await wanted(uploadFlow, legacyOwnerRoleOf(route))), opts };
  }
  if (route.split('?')[0].endsWith('/documents/upload-sessions') && opts.json && typeof opts.json === 'object' && opts.json.owner === undefined) {
    const flow = flowForDocumentType(opts.json.document_type);
    if (flow) return { route, opts: { ...opts, json: { ...opts.json, owner: await wanted(flow, null) } } };
  }
  return { route, opts };
}

/**
 * Call the localhost app as the user. Returns {status, json, text, headers}.
 * @param {string} email
 * @param {string} method
 * @param {string} route
 * @param {{ port?: number, json?: any, body?: BodyInit, contentType?: string, headers?: Record<string, string>, owner?: null | string | object }} [opts]
 * @returns {Promise<{ status: number, json: any, text: string, headers: Headers }>}
 */
export async function api(email, method, route, opts = {}) {
  const prepared = await withSyntheticOwner(email, method, route, opts);
  const { owner: _owner, ...rest } = prepared.opts;
  void _owner;
  return rawApi(email, method, prepared.route, rest);
}

async function rawApi(email, method, route, { port, json, body, contentType, headers = {} } = {}) {
  const session = loadSession(email);
  const base = `http://127.0.0.1:${port ?? process.env.CERT_PORT ?? 3000}`;
  const init = { method, headers: { cookie: cookieHeader(session), ...headers }, redirect: 'manual' };
  if (json !== undefined) { init.body = JSON.stringify(json); init.headers['Content-Type'] = 'application/json'; }
  else if (body !== undefined) { init.body = body; if (contentType) init.headers['Content-Type'] = contentType; }
  // node:http, not fetch: Node's fetch gives up on a response after 300 s (undici headersTimeout), and a
  // scale journey must be able to MEASURE a request that runs longer than that (localhost only).
  const res = await httpRequest(base + route, init);
  const setCookies = res.setCookies;
  let changed = false;
  for (const sc of setCookies) {
    const [pair, ...attrs] = sc.split(';');
    const i = pair.indexOf('=');
    const name = pair.slice(0, i).trim(); const value = pair.slice(i + 1).trim();
    if (!name.startsWith('sb-')) continue;
    const expired = attrs.some((a) => /max-age=0/i.test(a)) || value === '';
    if (expired) delete session.cookies[name]; else session.cookies[name] = value;
    changed = true;
  }
  if (changed) fs.writeFileSync(sessionFile(email), JSON.stringify(session, null, 2));
  const text = res.text;
  let parsed = null; try { parsed = JSON.parse(text); } catch { /* not json */ }
  return { status: res.status, json: parsed, text, headers: res.headers };
}

/** Plain HTTP request with no client-side timeout (the app is on localhost). */
async function httpRequest(url, init) {
  const http = await import('node:http');
  let body = init.body;
  if (body !== undefined && typeof body !== 'string' && !Buffer.isBuffer(body)) {
    body = body instanceof Uint8Array ? Buffer.from(body) : Buffer.from(await new Response(body).arrayBuffer());
  }
  return new Promise((resolve, reject) => {
    const req = http.request(url, { method: init.method, headers: { ...init.headers, ...(body !== undefined ? { 'Content-Length': Buffer.byteLength(body) } : {}) } }, (res) => {
      const chunks = [];
      res.on('data', (c) => chunks.push(c));
      res.on('end', () => {
        const headers = new Headers();
        for (const [k, v] of Object.entries(res.headers)) if (v !== undefined && k !== 'set-cookie') headers.set(k, Array.isArray(v) ? v.join(', ') : String(v));
        resolve({ status: res.statusCode, text: Buffer.concat(chunks).toString('utf8'), headers, setCookies: res.headers['set-cookie'] ?? [] });
      });
      res.on('error', reject);
    });
    req.setTimeout(0);
    req.on('error', reject);
    if (body !== undefined) req.write(body);
    req.end();
  });
}

/** End the session server-side (local scope: only this session) and delete the session file. */
export async function revoke(email, { scope = 'local' } = {}) {
  const session = loadSession(email);
  const chunk = (n) => { const m = n.match(/^sb-[a-z0-9]+-auth-token(?:\.(\d+))?$/); return m ? Number(m[1] ?? -1) : null; };
  const raw = Object.entries(session.cookies).filter(([n]) => chunk(n) !== null)
    .sort(([a], [b]) => chunk(a) - chunk(b)).map(([, v]) => v).join('');
  const decoded = raw.startsWith('base64-') ? Buffer.from(raw.slice(7), 'base64url').toString('utf8') : raw;
  const stored = JSON.parse(decoded);
  let token = stored.access_token;
  // An access token expires after an hour and signOut needs a valid one. Deleting the session file after a
  // failed signOut used to strand a live refresh token on DEV; refresh first instead (canonical-cert, 2026-09-27).
  if (typeof stored.expires_at === 'number' && stored.expires_at * 1000 < Date.now() + 30_000 && stored.refresh_token) {
    const { url, anonKey } = loadDevEnv();
    const res = await fetch(`${url}/auth/v1/token?grant_type=refresh_token`, {
      method: 'POST', headers: { apikey: anonKey, 'Content-Type': 'application/json' }, body: JSON.stringify({ refresh_token: stored.refresh_token }),
    });
    const body = await res.json().catch(() => ({}));
    if (!res.ok || !body.access_token) throw new Error(`signOut: refresh before sign-out failed (HTTP ${res.status}); session file kept`);
    token = body.access_token;
  }
  const admin = await serviceClient();
  const { error } = await admin.auth.admin.signOut(token, scope);
  if (error) throw new Error(`signOut failed: ${error.message}; session file kept`);
  fs.rmSync(sessionFile(email), { force: true });
  return true;
}
