// M12D — per-(phase, family) evidence profile. 192 groups.
// Each entry: [status, impl, test, live, grade, rationale]
// Keys are "PHASE/FAMILY".
import { A, T, L, D } from './rules.mjs';

const na = '—';
export const FAM = {
  // =====================================================================
  // AIE-1.0 — Architecture & Privacy Contract (268 incl. 18 ADRs)
  // These requirements are ARCHITECTURE-DEFINITION obligations. The spec's own
  // "Required treatment" asks for a target rule + enforcement point + failure
  // behaviour, and its "Minimum evidence" asks for the resulting ADR/diagram/
  // contract/matrix entry. Where a real technical control exists, that control
  // is the enforcement point and is cited. Where only the documentary
  // deliverable was asked for and no document exists, the honest answer is
  // UNVERIFIED — this phase does not invent an ADR citation.
  // =====================================================================
  'AIE-1.0/GOV': ['CODE', 'docs/investment-intelligence/II_POST_PC4_MASTER_SCOPE_LEDGER_2026-09-15.md; ' + A.flags, na, na, 'B',
    'Programme-governance obligations. The mission genuinely operates a scope ledger, a verdict vocabulary that distinguishes code-complete / migration-prepared / DEV-applied / merged / deployed / production-active, a blocker+decision register, and production-off-by-default flags. Documentary deliverables are evidenced by the named documents; the flag default is evidenced by code.'],
  'AIE-1.0/INV': ['CODE', 'docs/investment-intelligence/II_POST_PC4_MASTER_SCOPE_LEDGER_2026-09-15.md; docs/aie-programme/AIE_1_EXTERNAL_DEPENDENCIES_REGISTER.md', na, na, 'B',
    'Current-state inventory obligations. The M0 scope ledger and the external-dependencies register are the actual inventory artifacts produced by this programme. Grade B: the registers exist and cover the subject, but were not re-audited line-by-line against each INV-nn sub-question in this phase.'],
  'AIE-1.0/CTX': ['CODE', A.orch + '; ' + A.types + '; ' + A.pc5If, T.pc5If, na, 'B',
    'Bounded-context definition. The dependency direction it mandates (adapters depend on AIE contracts; AIE core never imports module canonical tables) is structurally true of lib/aie — verified by reading the adapter headers, which import domain services, never the reverse.'],
  'AIE-1.0/FLOW': ['CODE', A.orch, T.orch, L.maskEgress, 'B',
    'Target data-flow/orchestration order. lib/aie/orchestrator.ts is the single place this order is enforced: quarantine/validation, local extraction, masking, deterministic parse, admission-gated AI, schema validation, reconciliation, acceptance-gated canonical write.'],
  'AIE-1.0/TRUST': ['CODE', A.config + '; ' + A.storage, na, L.rls, 'B',
    'Trust boundaries and deployment topology. The server-only secret boundary was hardened in M12C and the storage/signed-URL path is server-side; several sub-items (network egress allowlist, subprocessor register, break-glass) are policy artifacts, handled by the per-ID overrides.'],
  'AIE-1.0/PRIV': ['CODE', A.mask, T.mask, L.maskEgress, 'B',
    'Privacy and data classification. The typed PII class vocabulary the contract asks for exists as real code in piiMasking.ts; the legal/consent/residency sub-items are handled by per-ID overrides because they are genuinely not engineering artifacts.'],
  'AIE-1.0/MASK': ['CODE', A.mask + '; ' + A.token, T.mask + '; ' + T.token, L.maskEgress, 'B',
    'Masking/tokenisation contract. The implementation is one-way HMAC tokenisation (identifierToken.ts) with a typed placeholder vocabulary; masking-before-egress is proven live in DEV.'],
  'AIE-1.0/PAR': ['CODE', A.parserReg, na, na, 'B',
    'Deterministic parser strategy. lib/aie/classifier/registry.ts is the registry the contract mandates, with sniff/parse, typed outcomes and priority.'],
  'AIE-1.0/AI': ['CODE', A.gateway + '; ' + A.providerFactory, T.gateway + '; ' + T.injection, L.provider, 'B',
    'AI fallback policy and provider governance. One internal gateway; adapters cannot choose provider/model; prompt templates treat document content as hostile evidence (proven by the prompt-injection suite).'],
  'AIE-1.0/SCH': ['CODE', A.schemaReg + '; ' + A.types, T.schemaReg, na, 'B',
    'Canonical extraction envelope and schema governance. The Zod-based registry is the single schema mechanism; strict additionalProperties rejection is tested.'],
  'AIE-1.0/PROV': ['CODE', A.repo + '; ' + A.mig140, na, L.iiDispatch, 'B',
    'Provenance/evidence model. aie_field_candidate / aie_extraction_run / aie_parser_attempt in migration 0140 carry the identities and lineage; supersession rather than overwrite is the schema shape.'],
  'AIE-1.0/CONF': ['CODE', A.recTypes + '; ' + A.revMerge, T.revMerge, na, 'B',
    'Confidence/completeness/materiality. The load-bearing rule — confidence can never override reconciliation — is enforced STRUCTURALLY: the ReconciliationRule signature has no confidence parameter at all.'],
  'AIE-1.0/REC': ['CODE', A.recTypes, T.iiRecon + '; ' + T.fdhRecon + '; ' + T.insRecon, na, 'B',
    'Deterministic reconciliation contract. One shared result interface, per-adapter rules, typed PASS/FAIL/INDETERMINATE outcomes.'],
  'AIE-1.0/EXC': ['CODE', A.repo + '; ' + A.pc5If, T.pc5If, L.pc5If, 'B',
    'Unified unresolved-item contract and PC5 integration. One exception system (aie_unresolved_item); PC5 is a governed consumer only, enforced by migration 0153 and pc5ExceptionInterface.ts.'],
  'AIE-1.0/PC6': ['CODE', 'lib/services/investment-intelligence/pc6/ (separate from lib/aie/ by construction)', 'tests/unit/pc6ReferenceMarketData.test.ts (79 cases)', 'scripts/pc6_live_dev_matrix.ts (41/41)', 'B',
    'PC6 reference-market-data EXCLUSION. These ten are the exclusion CONTRACT, not benchmark ingestion, and the exclusion is genuinely honoured: no PC6 module imports lib/aie/**, PC6 tables carry no tenancy column, and document acceptance succeeds with no live PC6 availability. The requirements that genuinely depend on licensed benchmark or risk-free DATA are overridden individually to DECISION, citing PO-PC6-1 / PO-PC6-2.'],
  'AIE-1.0/SEC': ['TEST', A.fileVal + '; ' + A.malware, T.fileVal + '; ' + T.adv + '; ' + T.advPdf + '; ' + T.injection, L.crossTenant, 'B',
    'Threat model. This is a MODELLING obligation; the mission produced adversarial test suites rather than a formal threat-model document. Each SEC-nn is mapped to the suite that exercises its threat class; the formal threat-model document itself does not exist and that is disclosed per-ID.'],
  'AIE-1.0/RET': ['CODE', A.purge + '; ' + A.mig149, T.purge + '; ' + T.purgeStatus, L.backstop, 'B',
    'Retention/deletion/replay/legal hold. Migration 0149 plus purge.ts implement retention classes, tombstones and cleanup retries; the 24h backstop is proven live in DEV.'],
  'AIE-1.0/AUD': ['CODE', A.audit + '; ' + A.mig140, na, na, 'B',
    'Audit and privacy-safe observability. aie_audit_event with allowlisted structured fields; raw prompt/response logging is prohibited in code.'],
  'AIE-1.0/COST': ['CODE', A.cost + '; ' + A.mig150 + '; ' + A.mig152, T.cost + '; ' + T.costPg, L.costIdem + '; ' + L.costConc, 'B',
    'Cost/capacity. Atomic quota reservation, idempotent reserve/settle and kill switches are implemented and proven live in DEV under genuine concurrency.'],
  'AIE-1.0/API': ['CODE', A.rIntake + '; ' + A.rRun + '; ' + A.rAccept + '; ' + A.rDecide, T.revAccept + '; ' + T.revDecide, L.crossTenant, 'B',
    'Contract/API/versioning. The internal command surface exists as real routes with server-generated IDs and server-derived tenancy.'],
  'AIE-1.0/ROLL': ['CODE', A.flags, T.pilot, na, 'B',
    'Migration/adoption/deprecation. "Wrap, do not rebuild" is literally what AIE-1.2/1.3/1.4 did; flags exist per core/adapter/cohort. Production canary items are overridden to DEFERRED.'],
  'AIE-1.0/QA': ['TEST', na, na, na, 'A',
    'Architecture validation proofs. These twelve are the most directly traceable requirements in the entire contract — each names a specific proof. Every one is individually mapped in the per-ID overrides.'],
  'AIE-1.0/ADR': ['UNVERIFIED', na, na, na, 'D', D.NOADR],

  // =====================================================================
  // AIE-1.1 — Shared preprocessing, masking and JSON-schema gateway (332)
  // =====================================================================
  'AIE-1.1/PRE': ['CODE', 'docs/aie-programme/AIE_1_1_IMPLEMENTATION.md; ' + A.flags, na, L.migState, 'B',
    'Entry conditions and AIE-1.0 conformance. Branch/HEAD discipline, migration-lineage collision avoidance and production-safe flag defaults are all real and evidenced; PRE-03 (the traceability matrix) is exactly what THIS document is, and is overridden per-ID.'],
  'AIE-1.1/MOD': ['CODE', 'lib/aie/ (package layout)', na, na, 'B',
    'Package boundaries. The boundary is real: lib/aie/{db,masking,provider,schema,classifier,reconciliation,review,adapters}. The architecture LINT tests the spec asks for (MOD-05/06) do not exist — overridden per-ID.'],
  'AIE-1.1/DB': ['CODE', A.mig140 + '; ' + A.repo, na, L.rls, 'B',
    'Database model/constraints/RLS. Migration 0140 creates 15 aie_* tables with 16 RLS policies, 17 CHECK constraints, 7 UNIQUE constraints and 17 indexes — counted in this phase. RLS is proven live in DEV against the real tables.'],
  'AIE-1.1/FSM': ['TEST', A.fsm, T.fsm, L.failState + '; ' + L.accepted, 'B',
    'Processing state machine. stateMachine.ts enforces transitions server-side; 17 unit cases cover legal and illegal transitions; M12C closed the remaining FSM gaps.'],
  'AIE-1.1/UPL': ['CODE', A.rIntake + '; ' + A.fileVal, T.fileVal + '; ' + T.entitlement, na, 'B',
    'Upload admission and entitlement. Server-derived tenancy, entitlement/country/flag evaluation, size and type limits, sanitised display filename.'],
  'AIE-1.1/QUA': ['TEST', A.fileVal + '; ' + A.malware, T.fileVal + '; ' + T.guardduty + '; ' + T.advPdf, na, 'B',
    'Quarantine/malware/MIME/structural validation. Magic-byte + MIME + structural checks; GuardDuty scan-result handling is fail-closed; password-protected PDF handling exists with a brute-force limiter added in M12C. The live scanner itself is AWS-blocked (see AWS note on QUA-03).'],
  'AIE-1.1/DUP': ['TEST', A.fingerprint + '; ' + A.repo, T.fingerprint, na, 'B',
    'Fingerprinting/duplicate/replay admission. SHA-based exact fingerprint, tenant-scoped duplicate checks, superseding lineage, unique constraints preventing double finalisation.'],
  'AIE-1.1/TXT': ['CODE', A.txt, na, na, 'B',
    'Local PDF text extraction. HONEST NARROWING: textExtraction.ts (90 lines) was read in full in this phase. It genuinely implements per-page text, page/char limits, sparse-page detection and password/corrupt disambiguation. It does NOT implement span offsets, bounding boxes, font/rotation hints, Unicode/ligature handling or extractor versioning. The file header cites "TXT-01..12", which is an OVERBROAD range citation; this matrix does not honour it wholesale — each member is adjudicated individually in the overrides.'],
  'AIE-1.1/TAB': ['UNVERIFIED', na, na, na, 'D',
    'Local table and layout extraction. No table/row/cell/coordinate extraction subsystem exists in lib/aie. The adapters consume already-certified domain parsers (FDH bank-PDF, CAMS/KFintech) that do their own row reconstruction; AIE-1.1 core has no generic table model. This family is genuinely not implemented and is reported as such.'],
  'AIE-1.1/OCR': ['UNVERIFIED', na, na, na, 'D',
    'Selective OCR subsystem. NO OCR code exists anywhere in lib/aie (verified by search in this phase: the only OCR mentions are type fields and a comment). The subsystem was never built. Reported honestly rather than mapped to an unrelated artifact.'],
  'AIE-1.1/ART': ['CODE', A.storage + '; ' + A.repo + '; ' + A.purge, T.purge, na, 'B',
    'Extraction artifact and provenance store. Raw source vs derived artifacts are separated, bound to tenant/intake/run, retention-classed at creation, with deletion tombstones and cleanup retries.'],
  'AIE-1.1/REG': ['CODE', A.parserReg, na, na, 'B',
    'Deterministic parser registry. 80-line registry with sniff/parse, typed outcomes and registration metadata; three adapters register against it (II, FDH-bank, Insurance) and none creates a second registry.'],
  'AIE-1.1/PII': ['TEST', A.mask + '; ' + A.token, T.mask + '; ' + T.token, L.maskEgress + '; ' + L.m12bPrivacy, 'B',
    'PII detection and masking pipeline. 703-line masking module, one-way HMAC tokens, 30 + 13 unit cases, live-DEV masking-before-egress proof, and M12B\'s own privacy proof that caught a genuine pre-egress PII leak (found and fixed). The shared masking-crash defect found in M12C affected all three adapters and is fixed.'],
  'AIE-1.1/PAY': ['CODE', A.orch + '; ' + A.gateway, T.gateway + '; ' + T.injection, L.maskEgress, 'B',
    'Minimum-necessary AI payload construction. Requested-field-only completion, hostile-data delimiting, payload limits, and a fail-closed check that refuses to build a payload when the masking summary is missing or below policy.'],
  'AIE-1.1/GW': ['TEST', A.gateway + '; ' + A.openai + '; ' + A.providerFactory, T.gateway + '; ' + T.openai + '; ' + T.providerFactory, L.provider, 'B',
    'Low-cost AI gateway and provider client. One internal gateway, a factory that is the only place a provider is chosen, and a REAL OpenAI provider call proven once live.'],
  'AIE-1.1/PRM': ['TEST', A.gateway, T.injection, na, 'B',
    'Prompt and structured-output contract. The prompt-injection suite proves document content is treated as inert evidence and embedded instructions are not followed.'],
  'AIE-1.1/JSC': ['TEST', A.schemaReg + '; ' + A.jsonSchema, T.schemaReg + '; ' + T.providerFactory, na, 'B',
    'JSON Schema registry and validation. Versioned registry, strict rejection of unknown properties, structured-output schema generation.'],
  'AIE-1.1/NORM': ['CODE', A.types + '; ' + A.revValidation, T.revValidation, na, 'B',
    'Shared normalisation primitives. Decimal-string handling, ISO currency/country codes and typed date semantics; the domain adapters reuse their own already-certified normalisers rather than duplicating them.'],
  'AIE-1.1/REC': ['CODE', A.recTypes, T.iiRecon + '; ' + T.fdhRecon + '; ' + T.insRecon, na, 'B',
    'Reconciliation handoff and unresolved-item creation. One injected ReconciliationRule contract; three adapters implement it.'],
  'AIE-1.1/EXC': ['CODE', A.repo + '; ' + A.mig140, T.pc5If, L.pc5If, 'B',
    'Unresolved-item persistence contract. aie_unresolved_item with typed reason codes, severity and permitted actions.'],
  'AIE-1.1/JOB': ['UNVERIFIED', na, na, na, 'D',
    'Workers, queues, leases and concurrency. There is no queue/worker/lease subsystem — AIE processing runs inline in the request path plus one cron purge sweep. Lease expiry, dead-letter and worker-crash recovery therefore have no implementation to cite. Reported honestly; individual members that ARE satisfied by the inline design (e.g. idempotent re-entry) are overridden.'],
  'AIE-1.1/API': ['CODE', A.rIntake + '; ' + A.rInbox + '; ' + A.rRun + '; ' + A.rAccept + '; ' + A.rDecide + '; ' + A.rUnresolved, T.revAccept + '; ' + T.revDecide, L.crossTenant, 'B',
    'Server APIs and authorisation surfaces. 14 real routes; cross-tenant access proven to fail closed live in DEV.'],
  'AIE-1.1/RET': ['TEST', A.purge + '; ' + A.mig149 + '; ' + A.rPurgeCron, T.purge + '; ' + T.purgeStatus, L.backstop, 'B',
    'Retention, deletion and cleanup implementation. Real purge service, real cron route, real migration, 16 unit cases, and a live-DEV 24h backstop proof.'],
  'AIE-1.1/OBS': ['CODE', A.audit, na, na, 'B',
    'Audit, metrics, logging and alerting. The audit-event layer is real; ALERTING and DASHBOARDS are not implemented — overridden per-ID to UNVERIFIED rather than credited to audit.ts.'],
  'AIE-1.1/CST': ['TEST', A.cost + '; ' + A.mig150 + '; ' + A.mig152, T.cost + '; ' + T.costPg, L.costIdem + '; ' + L.costConc, 'B',
    'Cost, quota and kill-switch implementation. Atomic reserve/settle proven idempotent live in DEV; the M12C cost-retry accounting defect was found and fixed.'],
  'AIE-1.1/TST': ['TEST', na, '58 AIE test files under tests/unit and tests/live-dev', na, 'B',
    'Automated test architecture and corpus. A real suite exists. The CORPUS side is materially weaker than the spec asks: no real issuer PDF layout has ever been sourced for Insurance, and the golden corpora are synthetic. Disclosed per-ID.'],
  'AIE-1.1/DEV': ['LIVEDEV', na, na, 'the live-DEV scripts catalogued in docs/aie-programme/AIE_1_LIVE_DEV_VERIFICATION_REPORT.md', 'B',
    'Live DEV integration and evidence. 15+ live-DEV scripts exist and were run; this is the strongest live-evidence family in the programme.'],
  'AIE-1.1/REGX': ['TEST', na, 'full repository suite', na, 'B',
    'Regression, build and release readiness. The regression baseline (17 files / 39 tests failing, pre-existing) was confirmed unchanged across every phase of this mission — a real, repeatedly re-measured control.'],

  // =====================================================================
  // AIE-1.2 — Investment Intelligence adapter (346)
  // =====================================================================
  'AIE-1.2/ENTRY': ['CODE', 'docs/aie-programme/AIE_1_2_IMPLEMENTATION.md', na, na, 'B', 'Entry conditions and phase boundary, recorded in the AIE-1.2 implementation report.'],
  'AIE-1.2/DISC': ['CODE', 'docs/investment-intelligence/R0_CURRENT_STATE_DISCOVERY.md; docs/aie-programme/AIE_1_2_IMPLEMENTATION.md', na, na, 'B', 'Current Investment Intelligence discovery — the II R0 discovery pack is the real artifact.'],
  'AIE-1.2/CAT': ['CODE', A.iiDir + 'documentCatalogue.ts', T.iiParse, na, 'B', 'Supported document/issuer catalogue — a deliberately static, honest list of what the codebase can already deterministically parse (CAMS/KFintech CAS + CAMS Folio).'],
  'AIE-1.2/CLASS': ['TEST', A.iiDir + 'parserAdapter.ts', T.iiParse, L.iiDispatch, 'B', 'Investment document classification, by wrapping the already-certified II parsers as one AIE RegisteredParser.'],
  'AIE-1.2/SCHEMA': ['TEST', A.iiDir + 'schema.ts; ' + A.iiDir + 'documentFactsSchema.ts', T.iiSchema + '; ' + T.iiFacts, na, 'B', 'Investment extraction schema — a closed AI-completable field enum enforced by schema SHAPE, not policy text.'],
  'AIE-1.2/ACCT': ['TEST', A.iiDir + 'accountMatching.ts', T.iiMatch, L.iiDispatch, 'B', 'Account identification and matching, reusing II\'s own pure resolution functions; unknown or conflicting evidence becomes a typed unresolved item, never a guess.'],
  'AIE-1.2/OWN': ['TEST', A.iiDir + 'ownerMatching.ts', T.iiMatch, L.ownerRepro, 'B', 'Ownership/beneficial-holder resolution — K.4/K.7 of PC5. The owner-mapping UI screen it ultimately needs is missing (see per-ID override).'],
  'AIE-1.2/PER': ['TEST', A.iiDir + 'statementMatching.ts', T.iiMatch, na, 'B', 'Statement period and temporal semantics — pure structural validation that never guesses a missing period.'],
  'AIE-1.2/HOLD': ['TEST', A.iiDir + 'parserAdapter.ts', T.iiParse + '; ' + T.iiCorpus, L.iiDispatch, 'B', 'Holding extraction and normalisation, delegated to the certified II parsers.'],
  'AIE-1.2/TXN': ['TEST', A.iiDir + 'parserAdapter.ts', T.iiParse + '; ' + T.iiCorpus, L.iiDispatch, 'B', 'Investment transaction extraction, delegated to the certified II parsers.'],
  'AIE-1.2/CASH': ['TEST', A.iiDir + 'reconciliationRule.ts', T.iiRecon, na, 'B', 'Cash ledger and movement extraction, reconciled by the adapter rule.'],
  'AIE-1.2/INC': ['TEST', A.iiDir + 'parserAdapter.ts', T.iiParse, na, 'B', 'Income/distributions/withholding/credits, carried through from the certified II transaction classification.'],
  'AIE-1.2/FEE': ['TEST', A.iiDir + 'parserAdapter.ts', T.iiParse, na, 'B', 'Fees/charges/tax evidence, carried through from the certified II parsers.'],
  'AIE-1.2/CA': ['TEST', A.iiDir + 'schema.ts', T.iiProhib, na, 'B', 'Corporate actions — the load-bearing control is the PROHIBITION on inventing tax/cost consequences, which is enforced by the closed schema enum and tested.'],
  'AIE-1.2/INST': ['TEST', A.iiDir + 'instrumentMatching.ts', T.iiMatch + '; ' + T.iiProhib, na, 'B', 'Instrument identification and mapping, reusing II\'s own resolver; no AI-created instrument identifier is possible by schema shape.'],
  'AIE-1.2/CUR': ['TEST', A.iiDir + 'householdContext.ts; ' + A.iiDir + 'reconciliationRule.ts', T.iiRecon + '; ' + T.iiProhib, na, 'B', 'Currency and FX handling — expected currency is derived from household country, never from AI; undocumented FX is a prohibited AI use.'],
  'AIE-1.2/COST': ['TEST', A.iiDir + 'write.ts', T.iiWrite + '; ' + T.iiPc4, L.syntheticPack, 'B', 'Cost-base evidence and lot boundaries. M12C confirmed and fixed PC4\'s opening-balance defect (M3-F1) in this area.'],
  'AIE-1.2/RECH': ['TEST', A.iiDir + 'reconciliationRule.ts', T.iiRecon, L.iiDispatch, 'B', 'Holding roll-forward reconciliation against the real II tables.'],
  'AIE-1.2/RECC': ['TEST', A.iiDir + 'reconciliationRule.ts', T.iiRecon, L.iiDispatch, 'B', 'Cash and total-value reconciliation.'],
  'AIE-1.2/DUP': ['TEST', A.iiDir + 'reconciliationRule.ts', T.iiRecon + '; ' + T.iiPc4, L.pc4Attr, 'B', 'Duplicate/overlap/statement chronology. M12C\'s residual attribution probe traced Kotak\'s +111.505 residual to genuinely double-counted transactions — a real, checkable use of this machinery.'],
  'AIE-1.2/PC5': ['CODE', A.pc5If + '; ' + A.mig153, T.pc5If, L.pc5If, 'B', 'PC5 ownership and reconciliation consumption, through the governed read/resolve interface only.'],
  'AIE-1.2/PREV': ['TEST', A.revProjection, T.revMerge, L.accepted, 'B', 'Investment-specific preview and acceptance payload.'],
  'AIE-1.2/WRITE': ['TEST', A.iiDir + 'write.ts', T.iiWrite, L.iiDispatch, 'B', 'Atomic canonical Investment Intelligence write — gated behind reconciliation AND a flag defaulted OFF; no new direct-to-table path.'],
  'AIE-1.2/CORR': ['TEST', A.iiDir + 'rehydrate.ts', T.iiPc4, na, 'B', 'Correction, reprocessing and historical lineage — rehydration from persisted candidates rather than re-reading the PDF.'],
  'AIE-1.2/AUTH': ['TEST', A.rIiIntake + '; ' + A.rIiProcess, T.iiDispatch, L.crossTenant, 'B', 'Authorization, privacy and support controls on the II intake/process routes.'],
  'AIE-1.2/TEST': ['TEST', na, T.iiCorpus + '; ' + T.iiParse + '; ' + T.iiMatch, na, 'B', 'Investment test corpus and golden truth. The corpus is real but SYNTHETIC-derived; that limit is disclosed per-ID.'],
  'AIE-1.2/MET': ['TEST', na, T.iiCorpus, na, 'B', 'Accuracy metrics and thresholds, measured by the II corpus-accuracy suite.'],
  'AIE-1.2/LIVE': ['LIVEDEV', na, na, L.iiDispatch + '; ' + L.syntheticPack, 'B', 'Live DEV certification — the II dispatch live-DEV suite plus M12C\'s S01-S10 synthetic pack.'],
  'AIE-1.2/REG': ['TEST', na, 'full repository suite', na, 'B', 'Regression, build and handoff against the confirmed-unchanged 17-file / 39-test baseline.'],

  // =====================================================================
  // AIE-1.3 — FDH bank-statement adapter (346)
  // =====================================================================
  'AIE-1.3/ENTRY': ['CODE', 'docs/aie-programme/AIE_1_3_IMPLEMENTATION.md', na, na, 'B', 'Entry conditions and phase boundary.'],
  'AIE-1.3/BASE': ['CODE', 'docs/aie-programme/AIE_1_3_IMPLEMENTATION.md', na, na, 'B', 'FDH current-state discovery — the adapter wraps FDH-5 bank-PDF and R7 bank-CSV rather than rebuilding them.'],
  'AIE-1.3/CAT': ['TEST', A.fdhDir + 'parser.ts', T.fdhParse, L.m12aCorpus, 'B', 'Bank/statement-format catalogue, inherited from FDH-4\'s 8 spec-priority certified banks.'],
  'AIE-1.3/CLASS': ['TEST', A.fdhDir + 'parser.ts', T.fdhParse, L.m12aCorpus, 'B', 'Document and institution classification.'],
  'AIE-1.3/SCH': ['TEST', A.fdhDir + 'schema.ts', T.fdhOrch, na, 'B', 'Bank-statement extraction schema — strict, no extra properties. The disclosed limitation (the orchestrator hardcodes the generic completion schema for the provider envelope) is in the file header.'],
  'AIE-1.3/ACCT': ['TEST', A.fdhDir + 'parser.ts', T.fdhParse, L.m12aCorpus, 'B', 'Institution and account matching.'],
  'AIE-1.3/HOLD': ['TEST', A.fdhDir + 'parser.ts; ' + A.pc5If, T.pc5If, L.pc5If, 'B', 'Account-holder and PC5 ownership linkage, through the governed PC5 interface.'],
  'AIE-1.3/PER': ['TEST', A.fdhDir + 'reconciliation.ts', T.fdhRecon, L.m12aCorpus, 'B', 'Statement period and page completeness.'],
  'AIE-1.3/ROW': ['TEST', A.fdhDir + 'parser.ts', T.fdhParse, L.m12aCorpus, 'B', 'Transaction-row segmentation, reusing FDH-5\'s certified row reconstruction; measured at 100% field accuracy by the M12A corpus.'],
  'AIE-1.3/DATE': ['TEST', A.fdhDir + 'parser.ts', T.fdhParse, L.m12aCorpus, 'B', 'Transaction date semantics (booking vs value date).'],
  'AIE-1.3/SIGN': ['TEST', A.fdhDir + 'parser.ts', T.fdhParse, L.m12aCorpus, 'B', 'Debit/credit and signed-amount normalisation.'],
  'AIE-1.3/AMT': ['TEST', A.fdhDir + 'parser.ts', T.fdhParse, L.m12aCorpus, 'B', 'Amount, decimal and currency parsing.'],
  'AIE-1.3/BAL': ['TEST', A.fdhDir + 'reconciliation.ts', T.fdhRecon, L.m12aCorpus, 'B', 'Opening/closing/running balances — the gate the canonical import is blocked behind.'],
  'AIE-1.3/STAT': ['TEST', A.fdhDir + 'parser.ts', T.fdhParse, L.m12aCorpus, 'B', 'Pending/reversed/cancelled/duplicated display rows.'],
  'AIE-1.3/NAR': ['TEST', A.mask, T.mask, L.maskEgress, 'B', 'Narration/reference/counterparty privacy — masked without destroying debit/credit table structure. The M12C address-masking hardening applies here.'],
  'AIE-1.3/AI': ['TEST', A.fdhDir + 'parser.ts; ' + A.fdhDir + 'index.ts', T.fdhOrch, na, 'B', 'Deterministic parser and AI fallback boundary — exactly ONE AI-eligible field (institution hint), which can never reach a financial value.'],
  'AIE-1.3/RECON': ['TEST', A.fdhDir + 'reconciliation.ts', T.fdhRecon, L.m12aCorpus, 'A', 'Statement and running-balance reconciliation. The file header cites AIE13-RECON-01..12 directly and the module is exactly this subject.'],
  'AIE-1.3/DUP': ['TEST', A.fdhDir + 'types.ts; ' + A.fdhDir + 'parser.ts', T.fdhParse, L.m12aCorpus, 'B', 'Transaction identity, duplicates and PDF/CSV overlap, via an account-scoped DedupIndex.'],
  'AIE-1.3/ENR': ['TEST', A.fdhDir + 'atomicImport.ts', T.fdhOrch, na, 'B', 'Merchant/MCC/category enrichment boundary — enrichment stays in FDH and cannot alter source facts.'],
  'AIE-1.3/IMPORT': ['TEST', A.fdhDir + 'atomicImport.ts', T.fdhOrch, L.m12aCorpus, 'B', 'Atomic canonical FDH import, through FDH-5\'s own atomic-import service. M12A found and fixed a REAL canonical-write bypass in the intake gate here, plus a false-canonical-write case.'],
  'AIE-1.3/CORR': ['TEST', A.fdhDir + 'atomicImport.ts', T.fdhOrch, na, 'B', 'Corrections, reprocessing and supersession.'],
  'AIE-1.3/AUTH': ['TEST', A.rFdhIntake, T.fdhOrch, L.crossTenant, 'B', 'Authorization, privacy and support access on the FDH-bank intake route.'],
  'AIE-1.3/CORP': ['TEST', A.fdhDir + 'parser.ts', T.fdhParse, na, 'B', 'Personal/joint/business/card/loan statement variants, inherited from FDH-4\'s certified bank set.'],
  'AIE-1.3/COUN': ['TEST', A.fdhDir + 'parser.ts', T.fdhParse, na, 'B', 'Country/institution/locale controls (AU + India).'],
  'AIE-1.3/UI': ['TEST', A.revProjection + '; ' + A.uiPanel, T.revMerge, L.accepted, 'B', 'FDH statement summary and exception payload, rendered through the shared review surface.'],
  'AIE-1.3/TEST': ['TEST', na, T.fdhParse + '; ' + T.fdhRecon + '; ' + T.fdhOrch, L.m12aCorpus, 'B', 'Bank-statement golden and adversarial corpus — M12A built a real accuracy corpus with an oracle.'],
  'AIE-1.3/MET': ['LIVEDEV', na, T.accHarness, L.m12aCorpus, 'A', 'Accuracy and false-clean metrics. M12A measured 100% document and 100% field accuracy against a real oracle, and found 2 genuine defects doing it. This is the strongest measured-accuracy evidence in the programme.'],
  'AIE-1.3/LIVE': ['LIVEDEV', na, na, L.m12aCorpus, 'B', 'Live DEV certification and residue cleanup.'],
  'AIE-1.3/REG': ['TEST', na, 'full repository suite', na, 'B', 'Regression, build and handoff.'],

  // =====================================================================
  // AIE-1.4 — Other PDF-enabled FHIP modules (286)
  // Nine candidate classes: 1 implemented (Insurance), 7 deferred, 1 NA, 1 prohibited.
  // =====================================================================
  'AIE-1.4/ENTRY': ['CODE', 'docs/aie-programme/AIE_1_4_IMPLEMENTATION.md', na, na, 'B', 'Entry conditions and phase boundary.'],
  'AIE-1.4/DISC': ['CODE', 'docs/aie-programme/AIE_1_4_IMPLEMENTATION.md §4 (eligibility scorecard)', na, na, 'B', 'Cross-module document discovery — the nine-class scorecard is the real artifact and is the basis for every DEFER/PROHIBIT decision below.'],
  'AIE-1.4/ELIG': ['CODE', 'docs/aie-programme/AIE_1_CLOSURE_DEFERRED_CLASS_REGISTER.md', na, na, 'C', 'Module and document eligibility framework — discharged by the class register, which names a repo-grounded reason for every class.'],
  'AIE-1.4/SDK': ['CODE', A.parserReg + '; ' + A.recTypes, T.insOrch, na, 'B', 'Adapter SDK and registration contract — demonstrated three times over (II, FDH-bank, Insurance) against one shared registry.'],
  'AIE-1.4/COMMON': ['TEST', A.insDir + 'types.ts; ' + A.types, T.insParse, na, 'B', 'Shared field and provenance rules.'],
  'AIE-1.4/INS': ['LIVEDEV', A.insDir, T.insParse + '; ' + T.insRecon + '; ' + T.insWrite + '; ' + T.insOrch + '; ' + T.insE2e, L.m12bCorpus + '; ' + L.insReg, 'A', 'Insurance policy documents — the ONE implemented class. M12B measured 100% document and 100% field accuracy and found 5 real defects including a genuine pre-egress PII leak. Several file headers cite AIE14-INS-nn directly.'],
  'AIE-1.4/PAY': ['DEFERRED', na, na, na, 'C', D.CLASS_DEFER('Payslip/income', 'a mature separate FDH payslip pipeline already exists (lib/financial-data-hub/payslip/**); wrapping it behind AIE is its own multi-session effort.')],
  'AIE-1.4/LOAN': ['DEFERRED', na, na, na, 'C', D.CLASS_DEFER('Loans/liabilities', 'lib/financial-data-hub/liability/adapters/** already exists as its own mature pipeline.')],
  'AIE-1.4/VAL': ['DEFERRED', na, na, na, 'C', D.CLASS_DEFER('Asset/property/valuation', 'no dedicated PDF ingestion path exists for this class at all, so there is no existing pipeline to wrap — a from-scratch build, outside AIE-1\'s "wrap what exists" mandate.')],
  'AIE-1.4/RET': ['DEFERRED', na, na, na, 'C', D.CLASS_DEFER('Retirement/superannuation/pension', 'lib/financial-data-hub/retirement/** already exists, and FDH-12\'s own 179-section closure work covers this domain separately.')],
  'AIE-1.4/GOAL': ['DEFERRED', na, na, na, 'C', D.CLASS_DEFER('Goals', 'goals have no document-based ingestion concept in this product at all — they are user-entered, not document-derived. A product decision, not an engineering gap.')],
  'AIE-1.4/BILL': ['DEFERRED', na, na, na, 'C', D.CLASS_DEFER('Bills/invoices/recurring expenses', 'bills/expenses ingestion is tangled with FDH\'s transaction-classification pipeline in ways AIE-1.4\'s own discovery found required deeper, separate design work.')],
  'AIE-1.4/TAX': ['DEFERRED', na, na, na, 'C', D.CLASS_DEFER('Tax-supporting evidence', 'no existing canonical "tax evidence" storage/table this class would write to, so there is no "wrap the existing write service" target yet.')],
  'AIE-1.4/CB': ['NA', na, na, na, 'C', D.CLASS_NA],
  'AIE-1.4/ID': ['PROHIBITED', na, na, na, 'C', D.CLASS_PROHIBIT],
  'AIE-1.4/XMOD': ['CODE', A.repo, T.insOrch, na, 'B', 'Cross-module duplicate and conflict resolution. With exactly ONE implemented class, cross-module conflict cannot actually be exercised; the fingerprint/duplicate machinery exists but the multi-module case is untested. Disclosed.'],
  'AIE-1.4/REC': ['TEST', A.insDir + 'reconciliation.ts; ' + A.recTypes, T.insRecon, na, 'B', 'Module reconciliation framework, demonstrated by the Insurance rule against the shared contract.'],
  'AIE-1.4/OWN': ['TEST', A.insDir + 'write.ts; ' + A.pc5If, T.insWrite + '; ' + T.pc5If, L.pc5If, 'B', 'Identity/ownership/PC5 consumption. The Insurance adapter deliberately never derives `owner` from document text.'],
  'AIE-1.4/WRITE': ['TEST', A.insDir + 'write.ts', T.insWrite, L.insReg, 'B', 'Canonical write and amendment contract — the same write path a manual insurance entry uses, gated behind reconciliation and an OFF-by-default flag.'],
  'AIE-1.4/UX': ['TEST', A.revProjection + '; ' + A.uiPanel, T.revMerge + '; ' + T.insE2e, L.accepted, 'B', 'Module summary and shared exception payload.'],
  'AIE-1.4/PRIV': ['TEST', A.mask, T.mask + '; ' + T.privHarness, L.m12bPrivacy, 'B', 'Privacy, authorization and retention. M12B\'s privacy proof found a genuine pre-egress PII leak in this adapter, which was fixed.'],
  'AIE-1.4/COST': ['TEST', A.cost, T.cost, L.costIdem, 'B', 'Cost, fallback and adapter operations, through the shared cost-admission layer.'],
  'AIE-1.4/TEST': ['LIVEDEV', na, T.insParse + '; ' + T.accHarness, L.m12bCorpus, 'B', 'Module-specific corpus and accuracy. IMPORTANT LIMIT, carried forward unchanged: no real insurer\'s exact PDF layout has ever been sourced — the corpus is a bounded generic Label:Value layout.'],
  'AIE-1.4/LIVE': ['LIVEDEV', na, na, L.insReg + '; ' + L.m12bCorpus, 'B', 'Live DEV and regression certification of the Insurance journey.'],

  // =====================================================================
  // AIE-1.5 — User exception review and acceptance integration (346)
  // =====================================================================
  'AIE-1.5/ENTRY': ['CODE', 'docs/aie-programme/AIE_1_5_IMPLEMENTATION.md', na, na, 'B', 'Entry conditions and phase boundary.'],
  'AIE-1.5/DISC': ['CODE', 'docs/aie-programme/AIE_1_5_IMPLEMENTATION.md', na, na, 'B', 'Existing review and exception discovery.'],
  'AIE-1.5/IA': ['CODE', A.pageInbox + '; ' + A.pageRun + '; ' + A.uiInbox, T.revUserState, L.a11y, 'B', 'Review information architecture — a real inbox page and a real per-run review page.'],
  'AIE-1.5/TRI': ['TEST', A.revProjection, T.revMerge, L.accepted, 'B', 'Clean-result summary path — clean results go to summary/acceptance, not to detailed review.'],
  'AIE-1.5/ITEM': ['TEST', A.revReasons + '; ' + A.uiPanel, T.revReasons, na, 'B', 'Exception item presentation contract — typed reason codes carry question, materiality and permitted actions.'],
  'AIE-1.5/EVID': ['TEST', A.uiEvidence + '; ' + A.revReveal, T.revReveal, na, 'B', 'Document evidence viewer. Narrow snippet reveal exists; page/region COORDINATE highlighting does not, because no coordinate model was ever built (see AIE-1.1/TAB). Disclosed per-ID.'],
  'AIE-1.5/MASK': ['TEST', A.revReveal + '; ' + A.rReveal, T.revReveal, L.maskEgress, 'B', 'Masking and controlled-reveal UX — masked by default, authorised and audited reveal.'],
  'AIE-1.5/ACT': ['TEST', A.revDecide + '; ' + A.rDecide, T.revReasons, na, 'B', 'Decision action model — permitted actions are server-derived per reason code.'],
  'AIE-1.5/VALID': ['TEST', A.revValidation, T.revValidation, na, 'B', 'Correction validation and financial safety.'],
  'AIE-1.5/DEP': ['TEST', A.revRevalidate, T.revRevalidate, na, 'B', 'Dependency graph and reconciliation reruns after a correction.'],
  'AIE-1.5/CONC': ['TEST', A.revAccept + '; ' + A.fsm, T.revAccept + '; ' + T.fsm, na, 'B', 'Concurrency, stale state and idempotency — optimistic version checks on decisions and acceptance.'],
  'AIE-1.5/GROUP': ['CODE', A.revProjection + '; ' + A.uiInbox, T.revMerge, na, 'B', 'Grouping, ordering and prioritisation in the inbox projection.'],
  'AIE-1.5/BULK': ['TEST', A.revAccept, T.revAccept, na, 'B', 'Bulk review constraints — a blocking failure cannot be bulk-accepted.'],
  'AIE-1.5/PC5': ['CODE', A.pc5If + '; ' + A.mig153, T.pc5If, L.pc5If, 'A', 'PC5 ownership and reconciliation integration. AIE15-PC5-01..12 is the block the AIE-1.0 boundary contract binds; migration 0153 and pc5ExceptionInterface.ts implement exactly the governed read/resolve surface it permits.'],
  'AIE-1.5/MOD': ['TEST', A.revModules, T.revReasons, na, 'B', 'Module-specific review rendering through a module registry.'],
  'AIE-1.5/ACPT': ['TEST', A.revAccept + '; ' + A.rAccept, T.revAccept + '; ' + T.insE2e, L.accepted, 'B', 'Document acceptance and canonical-write gating.'],
  'AIE-1.5/FAIL': ['TEST', A.revAccept + '; ' + A.fsm, T.revAccept + '; ' + T.fsm, L.failState, 'B', 'Canonical-write failure and recovery — the FAILED state UI is proven live in DEV.'],
  'AIE-1.5/AMEND': ['TEST', A.revAccept, T.revAccept, na, 'B', 'Post-acceptance correction, undo and amendments with immutable history.'],
  'AIE-1.5/SUP': ['CODE', A.revReject + '; ' + A.rReject, T.revReject, na, 'B', 'Support, disputes and no-valid-option flows — reject is a real, typed path.'],
  'AIE-1.5/NOTIF': ['UNVERIFIED', na, na, na, 'D', 'Notifications, reminders and re-entry. No notification/reminder subsystem exists for AIE review. Re-entry works (the inbox is durable), but reminders and notifications were never built. Reported honestly.'],
  'AIE-1.5/A11Y': ['LIVEDEV', A.revAria, T.revAria, L.a11y + '; ' + L.a11yAxe, 'A', 'Accessibility and inclusive review. AIE15-A11Y-01..12 is one of the 70 requirement IDs the earlier traceability run silently dropped. Real evidence exists: an ariaLabels module, its unit suite, two live-DEV accessibility scripts and M12C\'s automated axe pass. Manual screen-reader testing remains genuinely unavailable — disclosed per-ID.'],
  'AIE-1.5/MOB': ['UNVERIFIED', A.uiPanel, na, na, 'D', 'Responsive and mobile interaction. The components use the design system\'s responsive primitives, but no mobile-viewport test or live-DEV mobile scenario exists for the AIE review surface. Honest status: unverified.'],
  'AIE-1.5/PRIV': ['TEST', A.revReveal + '; ' + A.uiEvidence, T.revReveal, L.m12bPrivacy, 'B', 'Frontend privacy and security — masked defaults, audited reveal, no raw PII in the projection.'],
  'AIE-1.5/AUD': ['CODE', A.audit, na, na, 'B', 'Audit, analytics and operational monitoring of review decisions.'],
  'AIE-1.5/PERF': ['UNVERIFIED', A.rInbox, na, na, 'D', 'Performance, pagination and resilience. Pagination exists on the inbox route; no performance measurement, load test or p95 latency evidence exists for the review surface.'],
  'AIE-1.5/MIG': ['CODE', A.mig144, na, na, 'B', 'Legacy exception migration and route cutover. PARTIAL and disclosed: the schema work exists, but the legacy ii_reconciliation_cases store is still live and unbridged (M12C-O9).'],
  'AIE-1.5/TEST': ['TEST', na, T.revAccept + '; ' + T.revReject + '; ' + T.revReveal + '; ' + T.revValidation + '; ' + T.revRevalidate + '; ' + T.revUserState + '; ' + T.insE2e, na, 'B', 'Automated test matrix and user journeys — a real end-to-end Insurance review journey test exists.'],
  'AIE-1.5/LIVE': ['LIVEDEV', na, na, L.insReg + '; ' + L.failState + '; ' + L.accepted + '; ' + L.a11y, 'B', 'Live DEV certification and zero residue.'],
  'AIE-1.5/REG': ['TEST', na, 'full repository suite', na, 'B', 'Regression, build and handoff.'],

  // =====================================================================
  // AIE-1.6 — Production cost, security and accuracy certification (360)
  // This is a PRODUCTION-CERTIFICATION phase. The programme has never held
  // production authority, so a large, honest share of it is DEFERRED.
  // =====================================================================
  'AIE-1.6/ENTRY': ['CODE', 'docs/investment-intelligence/AIE1_TERMINAL_CERTIFICATION_2026-09-15.md', na, na, 'B', 'Certification authority and prerequisites — the terminal certification document records SHA, branch, scope and the CONDITIONAL PASS verdict, and explicitly states it does not authorise production.'],
  'AIE-1.6/TRACE': ['CODE', 'docs/aie-programme/AIE_1_REQUIREMENT_TRACEABILITY_FINAL_2026-09-15.md', na, na, 'A', 'Programme traceability and evidence reconciliation. THIS matrix is the artifact section 6 asks for. Its own honest limits are stated in the companion closure report rather than hidden.'],
  'AIE-1.6/BUILD': ['TEST', na, 'repository typecheck/lint/build + ' + L.migState, na, 'B', 'Build, dependency and migration integrity. Typecheck/lint/build and migration-lineage checks are real and were re-run every phase; SBOM and advisory review were not produced (overridden per-ID).'],
  'AIE-1.6/CFG': ['CODE', A.config + '; ' + A.flags, T.gateway, L.migState, 'B', 'Configuration, secrets and environment separation. M12C hardened the server-only secret boundary; flags default OFF and are independently operable.'],
  'AIE-1.6/CORP': ['TEST', na, T.accHarness + '; ' + L.m12aCorpus + '; ' + L.m12bCorpus, na, 'B', 'Truth-set corpus governance. Real oracles exist for FDH-bank and Insurance. The corpora are SYNTHETIC and there is no sealed holdout set or independent annotator — disclosed per-ID rather than claimed.'],
  'AIE-1.6/MET': ['TEST', na, T.accHarness, L.m12aCorpus + '; ' + L.m12bCorpus, 'B', 'Accuracy metric definitions and thresholds. The M12A/M12B harness defines document accuracy, field accuracy and a false-clean check with explicit numerators and denominators.'],
  'AIE-1.6/CLS': ['TEST', A.parserReg, T.fdhParse + '; ' + T.insParse + '; ' + T.iiParse, L.m12aCorpus, 'B', 'Document classification and support-boundary accuracy.'],
  'AIE-1.6/INV': ['TEST', na, T.iiCorpus + '; ' + T.iiPc4 + '; ' + T.iiProhib, L.iiDispatch + '; ' + L.syntheticPack, 'B', 'Investment Intelligence accuracy certification.'],
  'AIE-1.6/FDH': ['LIVEDEV', na, T.accHarness, L.m12aCorpus, 'A', 'FDH bank-statement accuracy certification — M12A measured 100%/100% against a real oracle and found 2 genuine defects.'],
  'AIE-1.6/OTH': ['LIVEDEV', na, T.accHarness, L.m12bCorpus, 'B', 'Other-module adapter accuracy certification — only Insurance is certifiable; the other eight classes are deferred/prohibited and are overridden per-ID.'],
  'AIE-1.6/FIN': ['TEST', A.recTypes, T.adv + '; ' + T.iiProhib + '; ' + T.fdhRecon, L.m12aCorpus, 'B', 'Financial integrity and reconciliation attack testing — seeded-error suites exist.'],
  'AIE-1.6/ATOM': ['TEST', A.revAccept + '; ' + A.iiDir + 'write.ts; ' + A.fdhDir + 'atomicImport.ts', T.revAccept + '; ' + T.iiWrite + '; ' + T.insWrite, L.costIdem, 'B', 'Canonical-write atomicity, idempotency and lineage.'],
  'AIE-1.6/MASK': ['LIVEDEV', A.mask + '; ' + A.token, T.mask + '; ' + T.token + '; ' + T.privHarness, L.maskEgress + '; ' + L.m12bPrivacy, 'A', 'PII masking accuracy and leakage certification. The strongest privacy evidence in the programme: a live pre-egress payload capture plus M12B\'s own proof, which caught a genuine leak.'],
  'AIE-1.6/PRIV': ['DECISION', na, na, na, 'C', 'Privacy contract, provider and residency certification. These are CONTRACTUAL and LEGAL verifications (provider training/retention terms, subprocessor list, residency per jurisdiction, privacy-approver sign-off) that no engineering artifact can discharge. They require named Product-Owner/privacy-approver action; several are also gated on the unresolved AWS/provider track.'],
  'AIE-1.6/PDF': ['TEST', A.fileVal + '; ' + A.txt, T.advPdf + '; ' + T.fileVal + '; ' + T.guardduty, na, 'B', 'Hostile-document and parser security. The adversarial PDF suite is real; the malware-scanner half is AWS-blocked and overridden per-ID.'],
  'AIE-1.6/INJ': ['TEST', A.gateway + '; ' + A.schemaReg, T.injection + '; ' + T.adv + '; ' + T.schemaReg, na, 'B', 'Prompt injection and structured-output security — 8 injection cases plus strict schema rejection.'],
  'AIE-1.6/AUTH': ['LIVEDEV', na, T.revAccept + '; ' + T.entitlement, L.crossTenant + '; ' + L.rls, 'B', 'Authorization, tenant isolation and privileged access — cross-tenant access proven to fail closed live in DEV.'],
  'AIE-1.6/REV': ['LIVEDEV', na, T.revAccept + '; ' + T.revReveal + '; ' + T.insE2e + '; ' + T.revAria, L.a11yAxe + '; ' + L.failState, 'B', 'User-review integrity, accessibility and privacy.'],
  'AIE-1.6/PC5': ['LIVEDEV', A.pc5If + '; ' + A.mig153, T.pc5If, L.pc5If, 'B', 'PC5 single-exception-system certification — the governed interface is proven live in DEV and no competing PC5 exception store exists.'],
  'AIE-1.6/PC6': ['TEST', 'lib/services/investment-intelligence/pc6/', 'tests/unit/pc6ReferenceMarketData.test.ts (79 cases)', 'scripts/pc6_live_dev_matrix.ts (41/41); scripts/pc6_performance_activation_proof.ts (24/24)', 'B',
    'PC6 SEPARATION and non-regression certification — which is about the boundary, not about licensed data, and is genuinely evidenced (PC6 total 174/174 assertions pass). The members that depend on licensed benchmark or risk-free DATA are overridden to DECISION citing PO-PC6-1 / PO-PC6-2.'],
  'AIE-1.6/COST': ['TEST', A.cost, T.cost + '; ' + T.costPg, L.costIdem + '; ' + L.costConc, 'B', 'Measured cost and budget certification. Admission/quota/idempotency are proven; the MEASURED cost model (p50/p95/p99, volume scenarios, PO sign-off) was never produced — overridden per-ID.'],
  'AIE-1.6/LOAD': ['UNVERIFIED', na, na, na, 'D', 'Performance, scalability and capacity. No load test, latency measurement or capacity model exists anywhere for AIE. Genuinely not done.'],
  'AIE-1.6/IDEM': ['TEST', A.cost + '; ' + A.fsm, T.cost + '; ' + T.costPg + '; ' + T.fsm, L.costIdem + '; ' + L.costConc, 'B', 'Concurrency, replay and race certification — genuine-concurrency cost admission was proven live in DEV.'],
  'AIE-1.6/OUT': ['TEST', A.gateway, T.gateway, na, 'B', 'Provider, OCR and infrastructure outage drills. Provider timeout/refusal handling is tested and the provider-refusal state-machine guarantee is registered; OCR, queue, storage and database outage drills have no subsystem to drill (see AIE-1.1/OCR, /JOB). Overridden per-ID.'],
  'AIE-1.6/KILL': ['TEST', A.flags + '; ' + A.config, T.gateway + '; ' + T.pilot, na, 'B', 'Kill-switch and rollback drills. Kill switches are real, independently operable and tested; the ROLLBACK drills require a production-like environment and are deferred.'],
  'AIE-1.6/RET': ['TEST', A.purge + '; ' + A.mig149, T.purge + '; ' + T.purgeStatus, L.backstop, 'B', 'Retention, deletion, backup and legal-hold certification. Backup-window and provider-side deletion evidence are not obtainable in DEV — overridden per-ID.'],
  'AIE-1.6/OBS': ['UNVERIFIED', A.audit, na, na, 'D', 'Monitoring, alerts and operational dashboards. Audit events exist; no alert, dashboard, routing or on-call artifact exists. Genuinely not done.'],
  'AIE-1.6/RUN': ['CODE', 'docs/aie-programme/AIE_1_CLOSURE_OPERATIONAL_RUNBOOKS.md; docs/investment-intelligence/PC6_OPERATOR_RUNBOOK.md', na, na, 'B', 'Runbooks, incident response and support readiness. Real runbook documents exist. The DRILLS (RUN-11) were never run — overridden.'],
  'AIE-1.6/CAN': ['DEFERRED', na, na, na, 'C', D.NOPROD],
  'AIE-1.6/GATE': ['CODE', 'docs/investment-intelligence/AIE1_TERMINAL_CERTIFICATION_2026-09-15.md', na, na, 'B', 'Terminal go/no-go decision. The terminal certification issued a CONDITIONAL PASS with 8 named blockers and explicitly separated the release-candidate technical verdict from production-activation authorisation — which is exactly what GATE-04 requires.'],
};
