/**
 * R8 — Transaction Categorisation & Merchant Intelligence: shared engine
 * types.
 *
 * Every type here describes PURE, DETERMINISTIC data — no AI, no network
 * call, no side effect. The engine functions in this directory take plain
 * data in and return plain data out; `lib/financial-data-hub/services/
 * transactionClassificationService.ts` is the only file that talks to the
 * database, reading reference data into these shapes and persisting the
 * results this module computes.
 */

import type {
  FdhCategory,
  FdhClassificationRule,
  FdhMerchant,
  FdhMerchantAlias,
  FdhSubcategory,
  FdhUserClassificationRule,
} from '../domain/types';
import type { FdhCreditDebit, FdhEconomicTransactionType, FdhTransactionTypeHint } from '../constants/enums';
import { CLASSIFICATION_CONFIDENCE_SCORE } from './thresholds';

/** The minimal transaction slice the engine needs. Deliberately narrow —
 * never the full row — so a caller cannot accidentally leak an unrelated
 * field into a classification decision. */
export interface ClassifiableTransaction {
  id: string;
  financial_account_id: string;
  transaction_date: string;
  description_clean: string | null;
  merchant_raw: string | null;
  amount_original: number;
  currency_original: string;
  credit_debit: FdhCreditDebit;
  transaction_type_hint: FdhTransactionTypeHint;
  user_override: boolean;
}

/** Deterministic confidence STATE, never a fake percentage (spec section 44).
 * Mapped to the numeric `numeric(5,4)` column at the persistence boundary
 * only, using the fixed buckets in `confidenceToScore`. */
export type ClassificationConfidenceState = 'HIGH' | 'MEDIUM' | 'LOW' | 'UNRESOLVED';

/** Re-exported from `./thresholds.ts` (spec section 84 — centralised
 * threshold governance) so every existing caller (`import {
 * CONFIDENCE_SCORE } from './types'`) keeps working unchanged. */
export const CONFIDENCE_SCORE: Record<ClassificationConfidenceState, number> = CLASSIFICATION_CONFIDENCE_SCORE;

export interface ClassificationSource {
  kind:
    | 'user_rule'
    | 'verified_merchant_alias'
    | 'verified_global_rule'
    | 'narrative_pattern'
    | 'unresolved'
    /** FDH-6 (spec section 57): two or more ACTIVE rules at the SAME
     * precedence tier and the SAME priority proposed genuinely different
     * classify outcomes for this transaction. Never resolved by array
     * order — always routed to `unknown`/review instead. */
    | 'rule_conflict';
  ruleId?: string;
  merchantId?: string;
  /** Present only when `kind === 'rule_conflict'` — every rule id that
   * tied and disagreed, for the review surface / audit trail. */
  conflictingRuleIds?: string[];
}

/** The engine's full output for one transaction. */
export interface EconomicTypeResult {
  economicTransactionType: FdhEconomicTransactionType;
  categoryId: string | null;
  subcategoryId: string | null;
  merchantId: string | null;
  transferFlag: boolean;
  subscriptionFlag: boolean;
  classificationMethod: 'merchant_master' | 'global_rule' | 'user_rule' | 'unclassified';
  confidence: ClassificationConfidenceState;
  source: ClassificationSource;
  /** Deterministic, human-readable evidence (spec section 45). Never
   * generated by an LLM. */
  explanation: string;
  /** Set when a rule proposed a candidate relationship (transfer, credit-card
   * settlement, investment funding) that a SEPARATE matching stage must
   * confirm before it becomes an authoritative `fdh_transaction_links` row —
   * see spec section 32/34. */
  flaggedCandidate: 'transfer_candidate' | 'liability_settlement_candidate' | 'investment_funding_candidate' | null;
}

/** Reference data the engine needs, read once per run and reused across
 * every transaction in the batch — never refetched per row. */
export interface ClassificationReferenceData {
  categories: FdhCategory[];
  subcategories: FdhSubcategory[];
  merchants: FdhMerchant[];
  merchantAliases: FdhMerchantAlias[];
  globalRules: FdhClassificationRule[];
  userRules: FdhUserClassificationRule[];
}
