// Module 11.4 — the approved 25-question standard catalogue (spec sections
// 10-11, 16, 35). Code/config, following the same "stable taxonomy lives in
// code" precedent as lib/ai/resolution/intentTaxonomy.ts — the mutable,
// admin-controlled subset (enabled/display_order/effective dates) is
// additionally DB-backed (migration 0124, ai_standard_questions) so an admin
// can disable a question without a deploy; see catalogueDb.ts for the merge.
//
// Do NOT rely on display_text as a key anywhere (spec section 10) —
// standard_question_code is the only stable identifier.

import type { StandardQuestionDefinition } from '@/lib/ai/standardQuestions/types';

export const CATALOGUE_INTRODUCED_VERSION = 'module-11.4';

function q(def: Omit<StandardQuestionDefinition, 'question_version' | 'enabled' | 'introduced_version'>): StandardQuestionDefinition {
  return { ...def, question_version: 1, enabled: true, introduced_version: CATALOGUE_INTRODUCED_VERSION };
}

/**
 * The approved 25 (spec section 11) in exact code/text order. `components`
 * drive AIStandardQuestionService's zero-cost composition
 * (DETERMINISTIC/KNOWLEDGE_BASE/STORED_PERSONALISED intent codes only —
 * never a free-text prompt, never AIModelGateway).
 */
export const STANDARD_QUESTIONS: StandardQuestionDefinition[] = [
  q({
    standard_question_code: 'SQ-AI-001',
    display_text: 'How healthy are my finances overall?',
    short_label: 'Overall health',
    category: 'FINANCIAL_OVERVIEW',
    description: 'A high-level summary of overall financial health.',
    personalised: true,
    premium_required: true,
    country_scope: null,
    required_domains: ['score'],
    primary_intent_code: 'FINANCIAL_HEALTH_SCORE',
    secondary_intent_codes: ['OVERALL_FINANCIAL_SUMMARY_EXPLANATION'],
    components: [
      { role: 'metric', intent_code: 'FINANCIAL_HEALTH_SCORE' },
      { role: 'explanation', intent_code: 'OVERALL_FINANCIAL_SUMMARY_EXPLANATION' },
    ],
    preferred_resolution_sources: ['COMPOSED_ZERO_COST', 'DETERMINISTIC'],
    stored_pack_block_codes: ['overall_financial_summary'],
    related_module: 'dashboard',
    action_route: '/dashboard',
    display_order: 1,
    requires_target: null,
  }),
  q({
    standard_question_code: 'SQ-AI-002',
    display_text: 'What are my strongest financial areas?',
    short_label: 'Strongest areas',
    category: 'FINANCIAL_OVERVIEW',
    description: 'The household’s strongest recorded financial areas.',
    personalised: true,
    premium_required: true,
    country_scope: null,
    required_domains: [],
    primary_intent_code: 'STRENGTHS_EXPLANATION',
    secondary_intent_codes: [],
    components: [{ role: 'explanation', intent_code: 'STRENGTHS_EXPLANATION' }],
    preferred_resolution_sources: ['STORED_PERSONALISED'],
    stored_pack_block_codes: ['strengths'],
    related_module: 'dashboard',
    action_route: '/dashboard',
    display_order: 2,
    requires_target: null,
  }),
  q({
    standard_question_code: 'SQ-AI-003',
    display_text: 'What should I focus on first?',
    short_label: 'Focus first',
    category: 'FINANCIAL_OVERVIEW',
    description: 'The single highest-priority already-ranked review area (never re-ranked here — Module 11.6\'s scope).',
    personalised: true,
    premium_required: true,
    country_scope: null,
    required_domains: [],
    primary_intent_code: 'PRIORITY_REVIEW_AREAS_EXPLANATION',
    secondary_intent_codes: [],
    components: [{ role: 'explanation', intent_code: 'PRIORITY_REVIEW_AREAS_EXPLANATION' }],
    preferred_resolution_sources: ['STORED_PERSONALISED'],
    stored_pack_block_codes: ['priority_review_areas'],
    related_module: 'recommendations',
    action_route: '/recommendations',
    display_order: 3,
    requires_target: null,
  }),
  q({
    standard_question_code: 'SQ-AI-004',
    display_text: 'Why is my Financial Health Score what it is?',
    short_label: 'Why my Score',
    category: 'SCORE_AND_BEHAVIOUR',
    description: 'A grounded explanation of the current Financial Health Score.',
    personalised: true,
    premium_required: true,
    country_scope: null,
    required_domains: ['score'],
    primary_intent_code: 'FINANCIAL_HEALTH_SCORE',
    secondary_intent_codes: ['SCORE_EXPLANATION'],
    components: [
      { role: 'metric', intent_code: 'FINANCIAL_HEALTH_SCORE' },
      { role: 'explanation', intent_code: 'SCORE_EXPLANATION' },
    ],
    preferred_resolution_sources: ['COMPOSED_ZERO_COST', 'DETERMINISTIC'],
    stored_pack_block_codes: ['score_explanation'],
    related_module: 'score',
    action_route: '/score',
    display_order: 4,
    requires_target: null,
  }),
  q({
    standard_question_code: 'SQ-AI-005',
    display_text: 'Why did my score change?',
    short_label: 'Score change',
    category: 'SCORE_AND_BEHAVIOUR',
    description: 'Why the Financial Health Score moved since the previous valid comparison. NOT_APPLICABLE with no prior comparable score (spec section 86).',
    personalised: true,
    premium_required: true,
    country_scope: null,
    required_domains: ['score'],
    primary_intent_code: 'SCORE_CHANGE_EXPLANATION',
    secondary_intent_codes: [],
    components: [{ role: 'explanation', intent_code: 'SCORE_CHANGE_EXPLANATION' }],
    preferred_resolution_sources: ['STORED_PERSONALISED'],
    stored_pack_block_codes: ['score_change_explanation'],
    related_module: 'score',
    action_route: '/score',
    display_order: 5,
    requires_target: null,
  }),
  q({
    standard_question_code: 'SQ-AI-006',
    display_text: 'How strong is my monthly cash flow?',
    short_label: 'Cash flow strength',
    category: 'CASH_FLOW',
    description: 'The certified monthly surplus/deficit position, in plain language — including a negative cash-flow position stated factually (spec section 85).',
    personalised: true,
    premium_required: true,
    country_scope: null,
    required_domains: ['cash_flow'],
    primary_intent_code: 'MONTHLY_SURPLUS',
    secondary_intent_codes: ['CASH_FLOW_EXPLANATION'],
    components: [
      { role: 'metric', intent_code: 'MONTHLY_SURPLUS' },
      { role: 'explanation', intent_code: 'CASH_FLOW_EXPLANATION' },
    ],
    preferred_resolution_sources: ['COMPOSED_ZERO_COST', 'DETERMINISTIC'],
    stored_pack_block_codes: ['cash_flow_explanation'],
    related_module: 'dashboard',
    action_route: '/dashboard',
    display_order: 6,
    requires_target: null,
  }),
  q({
    standard_question_code: 'SQ-AI-007',
    display_text: 'What does my savings rate mean?',
    short_label: 'Savings rate',
    category: 'CASH_FLOW',
    description: 'The flagship composed answer: deterministic savings rate + Knowledge Base definition + stored personalised explanation (spec section 92).',
    personalised: true,
    premium_required: true,
    country_scope: null,
    required_domains: ['cash_flow'],
    primary_intent_code: 'SAVINGS_RATE',
    secondary_intent_codes: ['SAVINGS_RATE_DEFINITION', 'SAVINGS_EXPLANATION'],
    components: [
      { role: 'metric', intent_code: 'SAVINGS_RATE' },
      { role: 'definition', intent_code: 'SAVINGS_RATE_DEFINITION' },
      { role: 'explanation', intent_code: 'SAVINGS_EXPLANATION' },
    ],
    preferred_resolution_sources: ['COMPOSED_ZERO_COST'],
    stored_pack_block_codes: ['savings_explanation'],
    related_module: 'dashboard',
    action_route: '/dashboard',
    display_order: 7,
    requires_target: null,
  }),
  q({
    standard_question_code: 'SQ-AI-008',
    display_text: 'Where is most of my money going?',
    short_label: 'Where money goes',
    category: 'CASH_FLOW',
    description: 'Recorded expense composition, in plain language.',
    personalised: true,
    premium_required: true,
    country_scope: null,
    required_domains: ['cash_flow'],
    primary_intent_code: 'MONTHLY_EXPENSES',
    secondary_intent_codes: ['EXPENSE_EXPLANATION'],
    components: [
      { role: 'metric', intent_code: 'MONTHLY_EXPENSES' },
      { role: 'explanation', intent_code: 'EXPENSE_EXPLANATION' },
    ],
    preferred_resolution_sources: ['COMPOSED_ZERO_COST', 'DETERMINISTIC'],
    stored_pack_block_codes: ['expense_explanation'],
    related_module: 'expenses',
    action_route: '/expenses',
    display_order: 8,
    requires_target: null,
  }),
  q({
    standard_question_code: 'SQ-AI-009',
    display_text: 'What makes up my net worth?',
    short_label: 'Net worth composition',
    category: 'BALANCE_SHEET_AND_LIQUIDITY',
    description: 'Recorded assets minus liabilities, and what makes up the total.',
    personalised: true,
    premium_required: true,
    country_scope: null,
    required_domains: ['balance_sheet'],
    primary_intent_code: 'CURRENT_NET_WORTH',
    secondary_intent_codes: ['NET_WORTH_EXPLANATION'],
    components: [
      { role: 'metric', intent_code: 'CURRENT_NET_WORTH' },
      { role: 'explanation', intent_code: 'NET_WORTH_EXPLANATION' },
    ],
    preferred_resolution_sources: ['COMPOSED_ZERO_COST', 'DETERMINISTIC'],
    stored_pack_block_codes: ['net_worth_explanation'],
    related_module: 'dashboard',
    action_route: '/dashboard',
    display_order: 9,
    requires_target: null,
  }),
  q({
    standard_question_code: 'SQ-AI-010',
    display_text: 'Is my wealth concentrated?',
    short_label: 'Concentration',
    category: 'BALANCE_SHEET_AND_LIQUIDITY',
    description: 'Whether recorded wealth is concentrated in one asset type/holding.',
    personalised: true,
    premium_required: true,
    country_scope: null,
    required_domains: ['balance_sheet'],
    primary_intent_code: 'ASSET_CONCENTRATION_EXPLANATION',
    secondary_intent_codes: ['INVESTMENT_CONCENTRATION_DEFINITION'],
    components: [
      { role: 'definition', intent_code: 'INVESTMENT_CONCENTRATION_DEFINITION' },
      { role: 'explanation', intent_code: 'ASSET_CONCENTRATION_EXPLANATION' },
    ],
    preferred_resolution_sources: ['COMPOSED_ZERO_COST', 'STORED_PERSONALISED'],
    stored_pack_block_codes: ['asset_concentration_explanation'],
    related_module: 'assets',
    action_route: '/assets',
    display_order: 10,
    requires_target: null,
  }),
  q({
    standard_question_code: 'SQ-AI-011',
    display_text: 'Do I have enough emergency savings?',
    short_label: 'Emergency savings',
    category: 'BALANCE_SHEET_AND_LIQUIDITY',
    description: 'Emergency-fund coverage in months, in plain language.',
    personalised: true,
    premium_required: true,
    country_scope: null,
    required_domains: ['resilience'],
    primary_intent_code: 'EMERGENCY_FUND_MONTHS',
    secondary_intent_codes: ['EMERGENCY_FUND_DEFINITION', 'LIQUIDITY_EXPLANATION'],
    components: [
      { role: 'metric', intent_code: 'EMERGENCY_FUND_MONTHS' },
      { role: 'definition', intent_code: 'EMERGENCY_FUND_DEFINITION' },
      { role: 'explanation', intent_code: 'LIQUIDITY_EXPLANATION' },
    ],
    preferred_resolution_sources: ['COMPOSED_ZERO_COST', 'DETERMINISTIC'],
    stored_pack_block_codes: ['liquidity_explanation'],
    related_module: 'resilience',
    action_route: '/resilience',
    display_order: 11,
    requires_target: null,
  }),
  q({
    standard_question_code: 'SQ-AI-012',
    display_text: 'How much debt pressure do I have?',
    short_label: 'Debt pressure',
    category: 'BALANCE_SHEET_AND_LIQUIDITY',
    description: 'Recorded liabilities and debt pressure — distinguishing confirmed-zero liabilities from unavailable liability data (spec section 84).',
    personalised: true,
    premium_required: true,
    country_scope: null,
    required_domains: ['balance_sheet'],
    primary_intent_code: 'TOTAL_LIABILITIES',
    secondary_intent_codes: ['DEBT_EXPLANATION'],
    components: [
      { role: 'metric', intent_code: 'TOTAL_LIABILITIES' },
      { role: 'explanation', intent_code: 'DEBT_EXPLANATION' },
    ],
    preferred_resolution_sources: ['COMPOSED_ZERO_COST', 'DETERMINISTIC'],
    stored_pack_block_codes: ['debt_explanation'],
    related_module: 'liabilities',
    action_route: '/liabilities',
    display_order: 12,
    requires_target: null,
  }),
  q({
    standard_question_code: 'SQ-AI-013',
    display_text: 'What happens if interest rates increase?',
    short_label: 'Rate rise impact',
    category: 'BALANCE_SHEET_AND_LIQUIDITY',
    description: 'Only ACTIVE where an existing certified stress result already covers this household (spec section 13, 90) — 11.4 never runs a new calculation. See AIStandardQuestionService\'s dedicated handler.',
    personalised: true,
    premium_required: true,
    country_scope: null,
    required_domains: ['resilience'],
    primary_intent_code: null,
    secondary_intent_codes: [],
    components: [],
    preferred_resolution_sources: ['DETERMINISTIC'],
    stored_pack_block_codes: [],
    related_module: 'resilience',
    action_route: '/resilience',
    display_order: 13,
    requires_target: null,
  }),
  q({
    standard_question_code: 'SQ-AI-014',
    display_text: 'How diversified are my investments?',
    short_label: 'Diversification',
    category: 'INVESTMENTS_AND_RETIREMENT',
    description: 'Recorded investment diversification.',
    personalised: true,
    premium_required: true,
    country_scope: null,
    required_domains: ['investments'],
    primary_intent_code: 'INVESTMENT_DIVERSIFICATION',
    secondary_intent_codes: ['DIVERSIFICATION_DEFINITION', 'INVESTMENT_EXPLANATION'],
    components: [
      { role: 'metric', intent_code: 'INVESTMENT_DIVERSIFICATION' },
      { role: 'definition', intent_code: 'DIVERSIFICATION_DEFINITION' },
      { role: 'explanation', intent_code: 'INVESTMENT_EXPLANATION' },
    ],
    preferred_resolution_sources: ['COMPOSED_ZERO_COST', 'DETERMINISTIC'],
    stored_pack_block_codes: ['investment_explanation'],
    related_module: 'investments',
    action_route: '/investments',
    display_order: 14,
    requires_target: null,
  }),
  q({
    standard_question_code: 'SQ-AI-015',
    display_text: 'What are the main risks in my investments?',
    short_label: 'Investment risks',
    category: 'INVESTMENTS_AND_RETIREMENT',
    description: 'Reuses the same validated investment explanation block as SQ-AI-014 (no dedicated investment-risk pack block exists yet) — presented with a risk-focused heading, never re-derived.',
    personalised: true,
    premium_required: true,
    country_scope: null,
    required_domains: ['investments'],
    primary_intent_code: 'INVESTMENT_EXPLANATION',
    secondary_intent_codes: [],
    components: [{ role: 'explanation', intent_code: 'INVESTMENT_EXPLANATION' }],
    preferred_resolution_sources: ['STORED_PERSONALISED'],
    stored_pack_block_codes: ['investment_explanation'],
    related_module: 'investments',
    action_route: '/investments',
    display_order: 15,
    requires_target: null,
  }),
  q({
    standard_question_code: 'SQ-AI-016',
    display_text: 'Am I progressing toward retirement?',
    short_label: 'Retirement progress',
    category: 'INVESTMENTS_AND_RETIREMENT',
    description: 'Recorded retirement balance and progress, in country-appropriate language.',
    personalised: true,
    premium_required: true,
    country_scope: null,
    required_domains: ['retirement'],
    primary_intent_code: 'RETIREMENT_BALANCE',
    secondary_intent_codes: ['RETIREMENT_EXPLANATION'],
    components: [
      { role: 'metric', intent_code: 'RETIREMENT_BALANCE' },
      { role: 'explanation', intent_code: 'RETIREMENT_EXPLANATION' },
    ],
    preferred_resolution_sources: ['COMPOSED_ZERO_COST', 'DETERMINISTIC'],
    stored_pack_block_codes: ['retirement_explanation'],
    related_module: 'retirement',
    action_route: '/retirement',
    display_order: 16,
    requires_target: null,
  }),
  q({
    standard_question_code: 'SQ-AI-017',
    display_text: 'What is affecting my retirement forecast?',
    short_label: 'Retirement forecast drivers',
    category: 'INVESTMENTS_AND_RETIREMENT',
    description: 'A grounded explanation of the current retirement forecast.',
    personalised: true,
    premium_required: true,
    country_scope: null,
    required_domains: ['forecasts', 'retirement'],
    primary_intent_code: 'FORECAST_SUMMARY_EXPLANATION',
    secondary_intent_codes: ['RETIREMENT_EXPLANATION'],
    components: [
      { role: 'explanation', intent_code: 'FORECAST_SUMMARY_EXPLANATION' },
      { role: 'explanation', intent_code: 'RETIREMENT_EXPLANATION' },
    ],
    preferred_resolution_sources: ['STORED_PERSONALISED', 'COMPOSED_ZERO_COST'],
    stored_pack_block_codes: ['forecast_summary', 'retirement_explanation'],
    related_module: 'forecasting',
    action_route: '/forecast/retirement',
    display_order: 17,
    requires_target: null,
  }),
  q({
    standard_question_code: 'SQ-AI-018',
    display_text: 'Is my insurance information complete?',
    short_label: 'Insurance completeness',
    category: 'PROTECTION',
    description: 'The recorded data-quality state of insurance information — correctly distinguishes missing from confirmed-none (spec section 83).',
    personalised: true,
    premium_required: true,
    country_scope: null,
    required_domains: ['insurance'],
    primary_intent_code: 'INSURANCE_DATA_STATUS',
    secondary_intent_codes: [],
    components: [{ role: 'metric', intent_code: 'INSURANCE_DATA_STATUS' }],
    preferred_resolution_sources: ['DETERMINISTIC'],
    stored_pack_block_codes: [],
    related_module: 'insurance',
    action_route: '/insurance',
    display_order: 18,
    requires_target: null,
  }),
  q({
    standard_question_code: 'SQ-AI-019',
    display_text: 'What does my protection position mean?',
    short_label: 'Protection meaning',
    category: 'PROTECTION',
    description: 'Never invents adequacy when insurance data is missing (spec section 83) — depends on a stored, grounded explanation.',
    personalised: true,
    premium_required: true,
    country_scope: null,
    required_domains: ['insurance'],
    primary_intent_code: 'INSURANCE_EXPLANATION',
    secondary_intent_codes: [],
    components: [{ role: 'explanation', intent_code: 'INSURANCE_EXPLANATION' }],
    preferred_resolution_sources: ['STORED_PERSONALISED'],
    stored_pack_block_codes: ['insurance_explanation'],
    related_module: 'insurance',
    action_route: '/insurance',
    display_order: 19,
    requires_target: null,
  }),
  q({
    standard_question_code: 'SQ-AI-020',
    display_text: 'Which goals are on track?',
    short_label: 'Goals on track',
    category: 'GOALS_AND_FORECAST',
    description: 'The certified count of on-track vs at-risk goals.',
    personalised: true,
    premium_required: true,
    country_scope: null,
    required_domains: ['goals'],
    primary_intent_code: 'GOALS_ON_TRACK_COUNT',
    secondary_intent_codes: ['GOALS_AT_RISK_COUNT'],
    components: [
      { role: 'metric', intent_code: 'GOALS_ON_TRACK_COUNT' },
      { role: 'metric', intent_code: 'GOALS_AT_RISK_COUNT' },
    ],
    preferred_resolution_sources: ['DETERMINISTIC'],
    stored_pack_block_codes: [],
    related_module: 'goals',
    action_route: '/goals',
    display_order: 20,
    requires_target: null,
  }),
  q({
    standard_question_code: 'SQ-AI-021',
    display_text: 'Why is one of my goals off track?',
    short_label: 'Goal off track',
    category: 'GOALS_AND_FORECAST',
    description: 'Requires the caller to select one of THEIR OWN eligible (off-track) goals (spec sections 27-28, 91) — resolved from certified per-goal deterministic facts only, never re-derived.',
    personalised: true,
    premium_required: true,
    country_scope: null,
    required_domains: ['goals'],
    primary_intent_code: 'GOALS_AT_RISK_COUNT',
    secondary_intent_codes: [],
    components: [],
    preferred_resolution_sources: ['DETERMINISTIC'],
    stored_pack_block_codes: [],
    related_module: 'goals',
    action_route: '/goals',
    display_order: 21,
    requires_target: 'goal',
  }),
  q({
    standard_question_code: 'SQ-AI-022',
    display_text: 'What does my forecast mean?',
    short_label: 'Forecast meaning',
    category: 'GOALS_AND_FORECAST',
    description: 'What the current base-case forecast means, in plain language.',
    personalised: true,
    premium_required: true,
    country_scope: null,
    required_domains: ['forecasts'],
    primary_intent_code: 'FORECAST_LATEST_RUN_DATE',
    secondary_intent_codes: ['FORECASTING_DEFINITION', 'FORECAST_SUMMARY_EXPLANATION'],
    components: [
      { role: 'metric', intent_code: 'FORECAST_LATEST_RUN_DATE' },
      { role: 'definition', intent_code: 'FORECASTING_DEFINITION' },
      { role: 'explanation', intent_code: 'FORECAST_SUMMARY_EXPLANATION' },
    ],
    preferred_resolution_sources: ['COMPOSED_ZERO_COST', 'STORED_PERSONALISED'],
    stored_pack_block_codes: ['forecast_summary'],
    related_module: 'forecasting',
    action_route: '/forecast',
    display_order: 22,
    requires_target: null,
  }),
  q({
    standard_question_code: 'SQ-AI-023',
    display_text: 'How do I compare with my Financial Twin?',
    short_label: 'Twin comparison',
    category: 'BENCHMARK_AND_CROSS_BORDER',
    description: 'DOMAIN_UNAVAILABLE (never generic benchmark text) with no Twin comparison available (spec section 88).',
    personalised: true,
    premium_required: true,
    country_scope: null,
    required_domains: ['financial_twin'],
    primary_intent_code: 'TWIN_COHORT',
    secondary_intent_codes: ['TWIN_SUMMARY_EXPLANATION'],
    components: [
      { role: 'metric', intent_code: 'TWIN_COHORT' },
      { role: 'explanation', intent_code: 'TWIN_SUMMARY_EXPLANATION' },
    ],
    preferred_resolution_sources: ['COMPOSED_ZERO_COST', 'DETERMINISTIC'],
    stored_pack_block_codes: ['twin_summary'],
    related_module: 'financial_twin',
    action_route: '/financial-twin',
    display_order: 23,
    requires_target: null,
  }),
  q({
    standard_question_code: 'SQ-AI-024',
    display_text: 'What are my cross-border financial exposures?',
    short_label: 'Cross-border exposure',
    category: 'BENCHMARK_AND_CROSS_BORDER',
    description: 'Only shown where cross-border context is applicable — never sums currencies raw, never invented with invalid currency integrity (spec section 89).',
    personalised: true,
    premium_required: true,
    country_scope: null,
    required_domains: ['cross_border'],
    primary_intent_code: 'COUNTRIES_PRESENT',
    secondary_intent_codes: ['CROSS_BORDER_SUMMARY_EXPLANATION'],
    components: [
      { role: 'metric', intent_code: 'COUNTRIES_PRESENT' },
      { role: 'explanation', intent_code: 'CROSS_BORDER_SUMMARY_EXPLANATION' },
    ],
    preferred_resolution_sources: ['COMPOSED_ZERO_COST', 'DETERMINISTIC'],
    stored_pack_block_codes: ['cross_border_summary'],
    related_module: 'forecasting',
    action_route: '/forecast/cross-border',
    display_order: 24,
    requires_target: null,
  }),
  q({
    standard_question_code: 'SQ-AI-025',
    display_text: 'What are the three most important things this month?',
    short_label: 'Top 3 this month',
    category: 'FINANCIAL_OVERVIEW',
    description: 'The same already-ranked priority list as SQ-AI-003, presented as up to 3 items (never re-ranked here — spec section 14-15).',
    personalised: true,
    premium_required: true,
    country_scope: null,
    required_domains: [],
    primary_intent_code: 'PRIORITY_REVIEW_AREAS_EXPLANATION',
    secondary_intent_codes: [],
    components: [{ role: 'explanation', intent_code: 'PRIORITY_REVIEW_AREAS_EXPLANATION' }],
    preferred_resolution_sources: ['STORED_PERSONALISED'],
    stored_pack_block_codes: ['priority_review_areas'],
    related_module: 'recommendations',
    action_route: '/recommendations',
    display_order: 25,
    requires_target: null,
  }),
];

export function getQuestionDefinition(code: string): StandardQuestionDefinition | null {
  return STANDARD_QUESTIONS.find((q2) => q2.standard_question_code === code) ?? null;
}
