// Maps each functional-requirement ID to the file(s) that satisfy it, so
// Module Acceptance Gates can be audited against the FRD without re-deriving
// coverage by hand. Update this map whenever a module is built or changed.
export const TRACEABILITY: Record<string, string[]> = {
  'FR-CORE-001': ['proxy.ts'],
  'FR-CORE-002': ['supabase/migrations/0001_foundation.sql'],
  'FR-CORE-003': ['lib/engines/money.ts'],
  'FR-M07-001': ['app/(auth)/signup/page.tsx', 'app/(auth)/login/page.tsx'],
  'FR-M07-002': ['app/(app)/onboarding/page.tsx', 'app/(app)/onboarding/OnboardingWizard.tsx'],
  'FR-M07-003': ['app/api/onboarding/complete/route.ts', 'proxy.ts'],
  'FR-M07-004': ['app/(app)/dashboard/page.tsx'],
  'FR-M07-005': ['app/api/user/profile/route.ts'],
  'FR-M07-006': ['app/api/household/route.ts'],
  'FR-M07-007': ['app/api/goals/route.ts'],
  'FR-M08-001': ['app/api/income/route.ts', 'app/(app)/income/page.tsx', 'lib/grid/configs.ts'],
  'FR-M08-002': ['app/api/expenses/route.ts', 'app/(app)/expenses/page.tsx', 'lib/grid/configs.ts'],
  'FR-M08-003': ['app/api/assets/route.ts', 'app/(app)/assets/page.tsx', 'lib/grid/configs.ts'],
  'FR-M08-004': ['app/api/liabilities/route.ts', 'app/(app)/liabilities/page.tsx', 'lib/grid/configs.ts'],
  'FR-M08-005': ['app/api/investments/route.ts', 'app/(app)/investments/page.tsx', 'lib/grid/configs.ts'],
  'FR-M08-006': ['app/api/retirement/route.ts', 'app/(app)/retirement/page.tsx', 'lib/grid/configs.ts'],
  'FR-M08-007': ['app/api/insurance/route.ts', 'app/(app)/insurance/page.tsx', 'lib/grid/configs.ts'],
  'FR-M08-GRID': ['components/grid/FinancialDataGrid.tsx', 'lib/engines/data-quality.ts', 'lib/services/masterItems.ts'],
  'FR-M09-001': ['app/(app)/dashboard/page.tsx', 'lib/services/dashboardData.ts'],
  'FR-M09-002': ['lib/engines/dashboard.ts'],
  'FR-M09-003': ['supabase/migrations/0005_module3_dashboard.sql'],
  'FR-M09-004': ['lib/engines/dashboard.ts'],
  'FR-M09-005': ['components/dashboard/sections.tsx', 'components/dashboard/placeholders.tsx'],
  'FR-M10-001': ['lib/engines/healthScore.ts', 'lib/services/healthScoreData.ts'],
  'FR-M10-002': ['supabase/migrations/0006_module4_health_score.sql'],
  'FR-M10-003': ['components/score/ComponentGrid.tsx', 'components/score/ExplanationPanel.tsx'],
  'FR-M10-004': ['app/(app)/score/page.tsx', 'components/score/HealthScoreGauge.tsx'],
  'FR-M10-005': ['lib/services/healthScoreData.ts'],
  'FR-M10-SIMULATOR': ['lib/engines/whatIf.ts', 'app/api/health-score/simulate/route.ts', 'components/score/WhatIfSimulator.tsx'],
  'FR-M10-BEHAVIOUR': ['supabase/migrations/0006_module4_health_score.sql', 'components/score/CheckInsPanel.tsx'],
  'FR-M11-001': ['lib/engines/financialDna.ts', 'lib/services/financialDnaData.ts'],
  'FR-M11-002': ['supabase/migrations/0007_module5_financial_dna.sql'],
  'FR-M11-003': ['app/(app)/dna/page.tsx', 'components/dna/sections.tsx'],
  'FR-M11-004': ['lib/services/financialDnaData.ts'],
  'FR-M11-SIMULATOR': [
    'app/api/intelligence/financial-dna/scenario/route.ts',
    'components/dna/WhatIfSimulator.tsx',
  ],
  'FR-M11-PERSONAS': ['tests/unit/financialDna.test.ts'],
  'FR-M12-001': ['lib/engines/resilience.ts', 'lib/services/resilienceData.ts'],
  'FR-M12-002': ['supabase/migrations/0008_module6_resilience.sql'],
  'FR-M12-003': ['components/resilience/ComponentGrid.tsx', 'components/resilience/EmergencyFundDetail.tsx'],
  'FR-M12-004': ['app/(app)/resilience/page.tsx', 'components/resilience/ResilienceGauge.tsx'],
  'FR-M12-RISKS': ['components/resilience/RiskRegister.tsx', 'components/resilience/ActionPlan.tsx'],
  'FR-M12-COMMITMENTS': [
    'supabase/migrations/0008_module6_resilience.sql',
    'app/api/commitments/route.ts',
    'app/api/commitments/[id]/route.ts',
    'components/resilience/CommitmentsManager.tsx',
  ],
  'FR-M12-STRESSTEST': [
    'lib/engines/resilienceStress.ts',
    'app/api/resilience/scenario/route.ts',
    'components/resilience/StressTestPanel.tsx',
  ],
  'FR-M12-ABSORPTION': ['lib/engines/healthScore.ts', 'lib/engines/scoring.ts'],
  'FR-M13-001': ['lib/services/goalsData.ts', 'app/api/goals/route.ts', 'app/api/goals/[id]/route.ts'],
  'FR-M13-002': ['supabase/migrations/0009_module7_goals.sql'],
  'FR-M13-LIFECYCLE': [
    'app/api/goals/[id]/pause/route.ts',
    'app/api/goals/[id]/resume/route.ts',
    'app/api/goals/[id]/complete/route.ts',
    'app/api/goals/[id]/archive/route.ts',
  ],
  'FR-M13-FORECAST': ['lib/engines/goalMath.ts', 'lib/engines/goalForecast.ts'],
  'FR-M13-FUNDING': [
    'lib/services/goalFundingAllocation.ts',
    'app/api/goals/[id]/funding-sources/route.ts',
    'app/api/goals/[id]/funding-sources/[sourceId]/route.ts',
  ],
  'FR-M13-CONTRIBUTIONS': [
    'app/api/goals/[id]/contributions/route.ts',
    'app/api/goals/[id]/contributions/[contributionId]/route.ts',
    'components/goals/ContributionHistory.tsx',
  ],
  'FR-M13-AFFORDABILITY': ['lib/engines/goalAffordability.ts', 'components/goals/MonthlyAllocationPanel.tsx'],
  'FR-M13-SIMULATOR': ['app/api/goals/[id]/forecast/route.ts', 'components/goals/GoalWhatIfSimulator.tsx'],
  'FR-M13-UI': ['app/(app)/goals/page.tsx', 'app/(app)/goals/[id]/page.tsx', 'app/(app)/goals/new/GoalCreationWizard.tsx'],
  'FR-M13-DASHBOARD': ['components/goals/DashboardGoalsCard.tsx', 'app/(app)/dashboard/page.tsx'],
  'FR-M13-HOUSEHOLD': ['app/api/household-members/route.ts', 'app/api/household-members/[id]/route.ts'],
  'FR-M13-PERSONAS': ['tests/unit/goals.test.ts'],

  // Module 9 (Reports and Exports) — source spec's own FR IDs preserved
  // verbatim, per instruction not to rename or remove them.
  'FR-M15-001': [
    'lib/services/reportsData.ts',
    'lib/services/reportSnapshotResolver.ts',
    'lib/engines/reportSections.ts',
    'app/api/reports/generate/route.ts',
  ],
  'FR-M15-002': ['supabase/migrations/0010_module9_reports.sql', 'app/api/reports/route.ts', 'components/reports/ReportHistoryTable.tsx'],
  'FR-M15-003': ['app/globals.css', 'components/reports/ReportPreview.tsx', 'components/reports/ReportActions.tsx'],
  'FR-M15-004': ['lib/engines/reportSections.ts'],
  'FR-M15-ELIGIBILITY': ['lib/engines/reportEligibility.ts'],
  'FR-M15-NARRATIVE': ['lib/engines/reportNarrative.ts'],
  'FR-M15-VERSIONING': ['app/api/reports/[id]/publish/route.ts', 'app/api/reports/[id]/revise/route.ts', 'app/api/reports/[id]/retry/route.ts'],
  'FR-M15-EXPORTS': [
    'supabase/migrations/0010_module9_reports.sql',
    'app/api/reports/[id]/exports/route.ts',
    'app/api/report-exports/[exportId]/route.ts',
    'app/api/report-exports/[exportId]/download/route.ts',
    'lib/services/entitlements.ts',
  ],
  'FR-M15-CRON': ['supabase/migrations/0010_module9_reports.sql', 'app/api/reports/cron/monthly-generate/route.ts', 'lib/supabase/admin.ts'],
  'FR-M15-UI': ['app/(app)/reports/page.tsx', 'app/(app)/reports/[id]/page.tsx'],
  'FR-M15-CROSSBORDER': ['lib/engines/dashboard.ts'],
  'FR-M15-PERSONAS': ['tests/unit/reports.test.ts'],

  // Module 8 (Financial Twin and Benchmark Intelligence Engine)
  'FR-M14-001': ['lib/services/twinCohortMatching.ts', 'lib/engines/twin/taxonomy.ts'],
  'FR-M14-002': ['lib/services/financialTwinService.ts', 'components/financial-twin/TwinDetailView.tsx'],
  'FR-M14-003': ['lib/engines/twin/metricCatalogue.ts', 'lib/engines/twin/metricDerivation.ts'],
  'FR-M14-004': ['components/financial-twin/TwinDetailView.tsx', 'app/api/financial-twin/methodology/route.ts'],
  'FR-M14-TAXONOMY': ['lib/engines/twin/taxonomy.ts'],
  'FR-M14-CATALOGUE': ['lib/engines/twin/metricCatalogue.ts', 'lib/engines/twin/metricDerivation.ts', 'lib/services/twinData.ts'],
  'FR-M14-COHORT': ['lib/services/twinCohortMatching.ts'],
  'FR-M14-GAPANALYSIS': ['lib/engines/twin/gapAnalysis.ts', 'lib/engines/twin/percentile.ts', 'lib/engines/twin/confidence.ts'],
  'FR-M14-BENCHMARKS': [
    'supabase/migrations/0011_module8_financial_twin.sql',
    'supabase/migrations/0012_module8_benchmark_seed.sql',
    'lib/services/twinBenchmarkRetrieval.ts',
  ],
  'FR-M14-ORCHESTRATION': ['lib/services/financialTwinService.ts'],
  'FR-M14-API': [
    'app/api/financial-twin/generate/route.ts',
    'app/api/financial-twin/current/route.ts',
    'app/api/financial-twin/history/route.ts',
    'app/api/financial-twin/[id]/route.ts',
    'app/api/benchmarks/categories/route.ts',
    'app/api/benchmarks/sources/route.ts',
  ],
  'FR-M14-ADMIN': [
    'lib/services/adminAuth.ts',
    'lib/services/benchmarkGovernance.ts',
    'app/api/admin/benchmarks/sources/route.ts',
    'app/api/admin/benchmarks/datasets/route.ts',
    'app/api/admin/benchmarks/datasets/[id]/activate/route.ts',
    'app/api/admin/benchmarks/datasets/[id]/retire/route.ts',
    'app/(app)/admin/benchmarks/page.tsx',
  ],
  'FR-M14-UI': ['app/(app)/financial-twin/page.tsx', 'app/(app)/financial-twin/[id]/page.tsx', 'app/(app)/financial-twin/history/page.tsx'],
  'FR-M14-PERSONAS': ['tests/unit/financialTwin.test.ts'],
};
