/**
 * The upload field-disposition registry (WP-00). One file per adapter so each
 * domain work package edits only its own file:
 *   bankStatement.ts            WP-08   economicTransactionType.ts  WP-02
 *   payslip.ts                  WP-09   liabilityStatement.ts       WP-10
 *   liabilityActivityLedger.ts  WP-11   auInvestmentStatement.ts    WP-12
 *   retirementStatement.ts      WP-13   iiCas.ts                    WP-12 (closed)
 *   insurance.ts                not active
 *
 * Human-readable form: UPLOAD_FIELD_DISPOSITION_REGISTRY.md in the FDH docs
 * folder, generated by scripts/generate-upload-field-disposition-doc.mjs from
 * renderRegistryMarkdown() below and compared (never written) by the gate test.
 */
import { auInvestmentStatementRegistry } from './auInvestmentStatement';
import { bankStatementRegistry } from './bankStatement';
import { economicTransactionTypeRegistry } from './economicTransactionType';
import { iiCasRegistry } from './iiCas';
import { insuranceRegistry } from './insurance';
import { liabilityActivityLedgerRegistry } from './liabilityActivityLedger';
import { liabilityStatementRegistry } from './liabilityStatement';
import { payslipRegistry } from './payslip';
import { retirementStatementRegistry } from './retirementStatement';
import type { FieldDispositionEntry, RegistryFile } from './types';

export * from './types';
export { INACTIVE_UPLOAD_FLOWS } from './insurance';

export const REGISTRY_FILES: readonly RegistryFile[] = [
  bankStatementRegistry,
  economicTransactionTypeRegistry,
  payslipRegistry,
  liabilityStatementRegistry,
  liabilityActivityLedgerRegistry,
  auInvestmentStatementRegistry,
  retirementStatementRegistry,
  iiCasRegistry,
  insuranceRegistry,
];

export const FIELD_DISPOSITION_REGISTRY: readonly FieldDispositionEntry[] = REGISTRY_FILES.flatMap((f) => f.entries);

/**
 * Registry rule R7 (strict certification). OFF until WP-14: while it is off,
 * open gaps are allowed under each file's ratchet ceiling. WP-14 turns it on,
 * after which ANY open P0/P1 gap in an active adapter fails the gate.
 */
export const STRICT_CERTIFICATION = false;

const DISPOSITION_LABEL: Record<string, string> = {
  A_STATE: 'A state',
  B_EVENT: 'B event',
  C_EVIDENCE: 'C evidence',
  D_METADATA: 'D metadata',
  E_UNSUPPORTED: 'E unsupported',
};

const cell = (s: string | null | undefined) => (s ?? '').replace(/\|/g, '\\|');

/** Deterministic markdown rendering of the whole registry (the generated doc). */
export function renderRegistryMarkdown(files: readonly RegistryFile[] = REGISTRY_FILES): string {
  const all = files.flatMap((f) => f.entries);
  const count = (pred: (e: FieldDispositionEntry) => boolean) => all.filter(pred).length;
  const lines: string[] = [];
  lines.push('# UPLOAD_FIELD_DISPOSITION_REGISTRY');
  lines.push('');
  lines.push('GENERATED -- do not edit by hand. Source: `lib/canonical-data/disposition/*.ts`.');
  lines.push('Regenerate with `node scripts/generate-upload-field-disposition-doc.mjs`; `tests/unit/uploadFieldDispositionRegistry.test.ts` fails if this file is stale.');
  lines.push('');
  lines.push('Every field an active upload adapter extracts, every evidence column and every activity / economic-type enum value has exactly one disposition:');
  lines.push('**A** canonical state · **B** canonical event · **C** evidence (must be user-visible) · **D** technical metadata · **E** explicitly unsupported (with a visible explanation).');
  lines.push('`open_gap` rows name the gap (see APPROVED_UPLOAD_CANONICAL_DATA_FLOW_MATRIX.md, gap register) and the work package that closes it; `not_active` rows belong to a flow no user can reach.');
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push('| Registry file | Owner | Entries | A | B | C | D | E | open_gap | ceiling | not_active |');
  lines.push('|---|---|---|---|---|---|---|---|---|---|---|');
  for (const f of files) {
    const e = f.entries;
    const n = (d: string) => e.filter((x) => x.disposition === d).length;
    lines.push(`| ${f.id} | ${f.ownerWp} | ${e.length} | ${n('A_STATE')} | ${n('B_EVENT')} | ${n('C_EVIDENCE')} | ${n('D_METADATA')} | ${n('E_UNSUPPORTED')} | ${e.filter((x) => x.status === 'open_gap').length} | ${f.OPEN_GAP_CEILING} | ${e.filter((x) => x.status === 'not_active').length} |`);
  }
  lines.push(`| **total** | | **${all.length}** | ${count((e) => e.disposition === 'A_STATE')} | ${count((e) => e.disposition === 'B_EVENT')} | ${count((e) => e.disposition === 'C_EVIDENCE')} | ${count((e) => e.disposition === 'D_METADATA')} | ${count((e) => e.disposition === 'E_UNSUPPORTED')} | ${count((e) => e.status === 'open_gap')} | | ${count((e) => e.status === 'not_active')} |`);
  lines.push('');
  const gaps = new Map<string, { severity: string; owners: Set<string>; n: number }>();
  for (const e of all) {
    if (e.status !== 'open_gap' || !e.gapId) continue;
    const g = gaps.get(e.gapId) ?? { severity: e.severity ?? '', owners: new Set<string>(), n: 0 };
    g.n += 1;
    if (e.ownerWp) g.owners.add(e.ownerWp);
    gaps.set(e.gapId, g);
  }
  lines.push('## Open gaps by id');
  lines.push('');
  lines.push('| Gap | Severity | Owner WP | Fields |');
  lines.push('|---|---|---|---|');
  for (const [id, g] of [...gaps.entries()].sort((a, b) => (a[0] < b[0] ? -1 : 1))) lines.push(`| ${id} | ${g.severity} | ${[...g.owners].sort().join(', ')} | ${g.n} |`);
  lines.push('');
  for (const f of files) {
    lines.push(`## ${f.id} (owner ${f.ownerWp})`);
    const bySource = new Map<string, FieldDispositionEntry[]>();
    for (const e of f.entries) {
      const k = `${e.adapter} · ${e.sourceKind} · \`${e.sourceRef}\``;
      if (!bySource.has(k)) bySource.set(k, []);
      bySource.get(k)!.push(e);
    }
    for (const [k, list] of bySource) {
      lines.push('');
      lines.push(`### ${k}`);
      lines.push('');
      lines.push('| Field | Disposition | Destination | User-visible at | Status | Gap | Owner |');
      lines.push('|---|---|---|---|---|---|---|');
      for (const e of list) {
        lines.push(`| \`${cell(e.field)}\` | ${DISPOSITION_LABEL[e.disposition]} | ${cell(e.destination)} | ${cell(e.userVisibleAt) || '—'} | ${e.status} | ${e.gapId ? `${e.gapId} (${e.severity})` : '—'} | ${e.ownerWp ?? '—'} |`);
      }
    }
    lines.push('');
  }
  return lines.join('\n');
}
