import fs from 'node:fs';
const envText = fs.readFileSync('D:/FHIP/.env.local', 'utf8');
const env = Object.fromEntries(envText.split(/\r?\n/).filter((l) => l.includes('=') && !l.trim().startsWith('#')).map((l) => { const idx = l.indexOf('='); return [l.slice(0, idx).trim(), l.slice(idx + 1).trim()]; }));
const { createClient } = await import('@supabase/supabase-js');
const supabase = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const audit = JSON.parse(fs.readFileSync('C:/Users/user/AppData/Local/Temp/claude/D--FHIP/754236a6-648e-4039-9457-c73bef97d4a2/scratchpad/chunk3b_audit_output.json', 'utf8'));

const keys = ['employer_contributions','salary_sacrifice','personal_concessional','non_concessional','government_co_contribution','spouse_contribution'];
const { data: fullRows, error } = await supabase.from('retirement_accounts').select('id,user_id,master_item_key,current_balance,contribution_frequency,currency_code').in('master_item_key', keys).eq('is_active', true);
if (error) throw error;
const byId = new Map(fullRows.map((r) => [r.id, r]));

const confident = [];
const excluded = [];
for (const c of audit.contributionEvidence) {
  const row = byId.get(c.id);
  if (!row) { excluded.push({ ...c, reason: 'row not found on re-fetch' }); continue; }
  if (c.candidates.length === 1 && row.contribution_frequency) {
    confident.push({ ...row, candidateAccountId: c.candidates[0].id, candidateAccountKey: c.candidates[0].key });
  } else {
    excluded.push({ ...c, reason: c.candidates.length === 0 ? 'no candidate parent account (same user, same currency)' : `${c.candidates.length} ambiguous candidates` });
  }
}

console.log(`Confident (single-candidate) rows: ${confident.length}`);
console.log(`Excluded rows: ${excluded.length}`);
for (const e of excluded) console.log(`  EXCLUDED id=${e.id} key=${e.master_item_key} user=${e.user_id} reason=${e.reason}`);

let sql = `-- Chunk 3b — retirement_contributions data backfill (item 6, Spec 2 §34-36).
-- Auto-generated by scripts/chunk3bMigrationAudit.mjs's companion
-- generator against real DEV data (vqycarelcoijzwlpkpcz) on 2026-08-21 —
-- NOT hand-transcribed. Every row below is a real existing
-- retirement_accounts row using one of the 6 Class-F contribution
-- catalogue keys, linked to a specific parent retirement account using the
-- best available evidence: same user_id + same currency_code, and exactly
-- ONE candidate parent account existing for that user (a genuine balance-
-- style retirement item — industry_super/retail_super/smsf/etc., not
-- another contribution row). This is a real but comparatively weak
-- evidence bar for a LINK (retirement_accounts carries no institution/
-- account-number field to further disambiguate, unlike the
-- deterministic-duplicate MERGE bar in Spec 2 §54-57, which needs strong
-- multi-factor evidence because a wrong merge would hide real money —
-- linking to a plausible parent account has no such risk: it never changes
-- any total, only which account a contribution's own record display is
-- associated with). Rows with zero or multiple (ambiguous) candidate
-- parent accounts for their user are deliberately EXCLUDED below and
-- listed as a genuine data-quality gap in
-- docs/app-review-2026-08/CHUNK3B_MIGRATION_AUDIT.md — not silently
-- guessed at.
--
-- amount = the source row's current_balance (the only value field the
-- live grid ever exposed for a Class-F row — see dashboard.ts's
-- isRetirementContributionRow() comment for the phantom-balance mechanism
-- this corrects). frequency = the source row's own saved
-- contribution_frequency (real stored data, not assumed — every one of
-- the 45 affected rows in DEV has contribution_frequency = 'monthly').
-- contributor = 'spouse' only for spouse_contribution rows, 'self'
-- otherwise, per Chunk 3a's "who contributes to whose account" model.
--
-- Idempotent: guarded by a NOT EXISTS check so re-running this migration
-- (e.g. against a database where it was already applied) inserts nothing
-- new. Does NOT touch, modify, or delete the source retirement_accounts
-- row in any way — it stays exactly as saved (now correctly excluded from
-- totalRetirement by dashboard.ts's fix, and visible in the grid as an
-- "Archived item" once migration 0038 deprecates its catalogue entry).
--
-- Depends on migration 0036 (retirement_contributions table) and should be
-- applied after 0038 (catalogue deprecation) for a consistent taxonomy
-- state, though the ordering has no functional dependency either way.

`;

for (const r of confident) {
  const contributor = r.master_item_key === 'spouse_contribution' ? 'spouse' : 'self';
  sql += `insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select '${r.user_id}', '${r.candidateAccountId}', '${r.master_item_key}', ${Number(r.current_balance)}, '${r.contribution_frequency}', '${contributor}',
  'Chunk 3b backfill from retirement_accounts.id=${r.id} (deprecated catalogue key ${r.master_item_key}); linked to ${r.candidateAccountKey} account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = '${r.user_id}' and rc.retirement_account_id = '${r.candidateAccountId}'
    and rc.contribution_type = '${r.master_item_key}' and rc.amount = ${Number(r.current_balance)}
);

`;
}

sql += `-- =============================================================================
-- Rows EXCLUDED from this backfill (genuine data-quality gap, not guessed):
-- =============================================================================
`;
for (const e of excluded) {
  sql += `-- id=${e.id} user_id=${e.user_id} master_item_key=${e.master_item_key} reason: ${e.reason}\n`;
}

fs.writeFileSync('D:/FHIP/.claude/worktrees/agent-a28d2ff4c7c436129/supabase/migrations/0074_retirement_contributions_backfill.sql', sql);
console.log('\nWritten to supabase/migrations/0074_retirement_contributions_backfill.sql');
