// FDH-2 — generates the master-data manifest (counts + source-file
// checksums) used for drift detection. Run with `--write` to regenerate
// docs/financial-data-hub/FDH2_MASTER_DATA_MANIFEST.md; without it, prints
// the computed values only.
import { PGlite } from '@electric-sql/pglite';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, '..');
const MIG = path.join(REPO, 'supabase', 'migrations');
const DATA_DIR = path.join(REPO, 'data', 'financial-data-hub');
const DOC = path.join(REPO, 'docs', 'financial-data-hub', 'FDH2_MASTER_DATA_MANIFEST.md');

const db = await PGlite.create();
await db.exec(fs.readFileSync(path.join(REPO, 'scripts', 'db-rebuild-check', 'shim.sql'), 'utf8'));
const seed = fs.readFileSync(path.join(REPO, 'supabase', 'seed.sql'), 'utf8');
for (const f of fs.readdirSync(MIG).filter((f) => f.endsWith('.sql')).sort()) {
  await db.exec(fs.readFileSync(path.join(MIG, f), 'utf8').replace(/create\s+extension\s+if\s+not\s+exists\s+(pg_cron|pg_net)\s*;/gi, ''));
  if (f.startsWith('0001')) await db.exec(seed);
}
const q = async (sql) => (await db.query(sql)).rows;
const count = async (table, where = '') => (await q(`select count(*)::int c from ${table} ${where}`))[0].c;

const counts = {
  economic_transaction_types: await count('fdh_economic_transaction_types'),
  categories: await count('fdh_categories'),
  subcategories: await count('fdh_subcategories'),
  mcc: await count('fdh_mcc_master'),
  mcc_category_map: await count('fdh_mcc_category_map'),
  institutions_au: await count('fdh_financial_institutions', "where country_code='AU'"),
  institutions_in: await count('fdh_financial_institutions', "where country_code='IN'"),
  institution_capabilities: await count('fdh_institution_capabilities'),
  institution_aliases: await count('fdh_institution_aliases'),
  payment_rails: await count('fdh_payment_rail_master'),
  merchants_au: await count('fdh_merchants', "where country_code='AU'"),
  merchants_in: await count('fdh_merchants', "where country_code='IN'"),
  merchant_aliases: await count('fdh_merchant_aliases'),
  classification_rules: await count('fdh_classification_rules'),
  global_learning_candidates: await count('fdh_global_learning_candidates'),
  source_registry: await count('fdh_source_registry'),
};

const dataFiles = fs.readdirSync(DATA_DIR).filter((f) => f.endsWith('.mjs')).sort();
const checksums = {};
for (const f of dataFiles) {
  const content = fs.readFileSync(path.join(DATA_DIR, f));
  checksums[f] = crypto.createHash('sha256').update(content).digest('hex');
}

const generatedAt = process.env.FDH2_MANIFEST_FIXED_DATE || new Date().toISOString().slice(0, 10);

const md = `# FDH2_MASTER_DATA_MANIFEST

Generated by \`scripts/fdh2_manifest.mjs\` against a clean PGlite rebuild of
the full active migration chain, including the original generated seed
(\`0050\`-\`0056\`) and any subsequent hand-written corrective migrations
(e.g. \`0057\` — see \`FDH2_RESEARCH_EVIDENCE.md\`'s closure-research section).
Regenerate (this script only — never \`fdh2_generate_master_data_migration.mjs
--write\`, which would rewrite the immutable \`0050\`-\`0056\` files) after any
migration change and commit the updated file.

Note: after a closure-research corrective migration, the row counts below can
legitimately differ from what \`data/financial-data-hub/*.mjs\` alone would
generate — a corrected fact (e.g. a merchant marked \`active: false\`, an
institution's \`legal_name\`) may live only in the corrective migration's
UPDATE statements, with the source \`.mjs\` file updated to match for
documentation/future-regeneration purposes but not re-emitted through the
generator. This is expected, not drift to chase.

## Row counts (post-seed, single application)

| Entity | Count |
| --- | --- |
| Economic transaction types | ${counts.economic_transaction_types} |
| Top-level categories | ${counts.categories} |
| Subcategories | ${counts.subcategories} |
| MCC records | ${counts.mcc} |
| MCC-to-category mappings | ${counts.mcc_category_map} |
| AU institutions | ${counts.institutions_au} |
| IN institutions | ${counts.institutions_in} |
| Institution capabilities (multi-capability rows) | ${counts.institution_capabilities} |
| Institution aliases | ${counts.institution_aliases} |
| Payment rails | ${counts.payment_rails} |
| AU merchants | ${counts.merchants_au} |
| IN merchants | ${counts.merchants_in} |
| Merchant aliases (AU + IN) | ${counts.merchant_aliases} |
| Classification seed rules | ${counts.classification_rules} |
| Global-learning candidates (seeded) | ${counts.global_learning_candidates} |
| Source-registry entries | ${counts.source_registry} |
| **Total FDH-2 master-data rows** | **${Object.values(counts).reduce((a, b) => a + b, 0)}** |

## Idempotency

Verified by \`scripts/fdh2_certify_master_data.mjs\`: re-applying migrations
\`0053\`-\`0056\` a second time against the same database produces the
identical row counts above with zero duplicates (every INSERT uses
\`ON CONFLICT (<stable key>) DO NOTHING\`). Any corrective migration on top
(e.g. \`0057\`) uses idempotent \`UPDATE\`s and \`ON CONFLICT DO NOTHING\`
\`INSERT\`s for the same reason.

## Source data-file checksums (SHA-256)

Drift-detection anchor: if a source data module changes, its checksum below
changes, and the generated migration SQL must be regenerated
(\`node scripts/fdh2_generate_master_data_migration.mjs --write\`) and this
manifest refreshed.

| File | SHA-256 |
| --- | --- |
${dataFiles.map((f) => `| \`data/financial-data-hub/${f}\` | \`${checksums[f]}\` |`).join('\n')}

## Regeneration

\`\`\`sh
node scripts/fdh2_generate_master_data_migration.mjs --write
node scripts/fdh2_certify_master_data.mjs
node scripts/fdh2_manifest.mjs --write
\`\`\`

_Manifest generated ${generatedAt}._
`;

if (process.argv.includes('--write')) {
  fs.writeFileSync(DOC, md, 'utf8');
  console.log(`wrote ${DOC}`);
} else {
  console.log(md);
}
console.log('\ncounts:', JSON.stringify(counts, null, 1));
