// One-off generator: reads the 4 recommendation CSVs the user supplied and
// emits a SQL migration that bulk-inserts them into the v2 schema
// (0019_recommendations_schema_v2.sql). Not part of the app runtime — this
// is how the initial 542/2143/88/120-row library gets into the database;
// future updates go through the admin CSV-upload feature instead.
import fs from 'node:fs';
import path from 'node:path';

const SRC_DIR = 'D:\\FHIP\\User tests\\forecasting test';
const OUT_FILE = 'D:\\FHIP\\supabase\\migrations\\0020_recommendations_data_import.sql';

function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = '';
  let inQuotes = false;
  const src = text.replace(/^\uFEFF/, '');
  for (let i = 0; i < src.length; i++) {
    const c = src[i];
    if (inQuotes) {
      if (c === '"') {
        if (src[i + 1] === '"') {
          field += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else field += c;
      continue;
    }
    if (c === '"') inQuotes = true;
    else if (c === ',') {
      row.push(field);
      field = '';
    } else if (c === '\r') {
      // no-op
    } else if (c === '\n') {
      row.push(field);
      rows.push(row);
      row = [];
      field = '';
    } else field += c;
  }
  if (field.length > 0 || row.length > 0) {
    row.push(field);
    rows.push(row);
  }
  const nonEmpty = rows.filter((r) => !(r.length === 1 && r[0] === ''));
  const header = nonEmpty[0];
  return nonEmpty.slice(1).map((cells) => {
    const obj = {};
    header.forEach((h, i) => (obj[h.trim()] = cells[i] ?? ''));
    return obj;
  });
}

function sqlStr(value) {
  if (value === undefined || value === null || value === '') return 'null';
  return `'${String(value).replace(/'/g, "''")}'`;
}
function sqlStrRequired(value) {
  return `'${String(value ?? '').replace(/'/g, "''")}'`;
}
function sqlBool(value) {
  return String(value).trim().toLowerCase() === 'true' ? 'true' : 'false';
}
function sqlInt(value, fallback = 0) {
  const n = parseInt(value, 10);
  return Number.isFinite(n) ? String(n) : String(fallback);
}
function sqlDate(value) {
  if (!value || value.trim() === '') return 'null';
  return `'${value.trim()}'`;
}
function sqlArray(value) {
  const items = String(value ?? '')
    .split(';')
    .map((v) => v.trim())
    .filter((v) => v.length > 0);
  if (items.length === 0) return "'{}'";
  return `ARRAY[${items.map((v) => sqlStrRequired(v)).join(', ')}]::text[]`;
}

const master = parseCsv(fs.readFileSync(path.join(SRC_DIR, 'FHIP_Recommendation_Master_542.csv'), 'utf8'));
const conditions = parseCsv(fs.readFileSync(path.join(SRC_DIR, 'FHIP_Recommendation_Conditions_2143.csv'), 'utf8'));
const calcMethods = parseCsv(fs.readFileSync(path.join(SRC_DIR, 'FHIP_Recommendation_Calculation_Methods_88.csv'), 'utf8'));
const placeholders = parseCsv(fs.readFileSync(path.join(SRC_DIR, 'FHIP_Recommendation_Placeholders_120.csv'), 'utf8'));

const lines = [];
lines.push('-- Generated by scripts/generateRecommendationsImport.mjs — do not hand-edit.');
lines.push('-- Imports the user-supplied recommendation library (master/conditions/');
lines.push('-- calculation methods/placeholders) into the v2 schema.');
lines.push('');

lines.push('insert into recommendation_template_placeholders');
lines.push('  (placeholder, data_type, description, source, availability, display_format, is_active, validation_note)');
lines.push('values');
lines.push(
  placeholders
    .map(
      (p) =>
        `  (${sqlStrRequired(p.placeholder)}, ${sqlStrRequired(p.data_type)}, ${sqlStr(p.description)}, ${sqlStr(p.source)}, ${sqlStr(p.availability)}, ${sqlStr(p.display_format)}, ${sqlBool(p.is_active)}, ${sqlStr(p.validation_note)})`
    )
    .join(',\n') + '\non conflict (placeholder) do nothing;'
);
lines.push('');

lines.push('insert into recommendation_calculation_methods');
lines.push('  (calculation_method_code, method_name, forecast_categories, description, calculation_service, required_inputs, outputs, rounding_method, supported_scenarios, is_active, version_number, admin_notes)');
lines.push('values');
lines.push(
  calcMethods
    .map(
      (m) =>
        `  (${sqlStrRequired(m.calculation_method_code)}, ${sqlStrRequired(m.method_name)}, ${sqlArray(m.forecast_categories)}, ${sqlStr(m.description)}, ${sqlStr(m.calculation_service)}, ${sqlArray(m.required_inputs)}, ${sqlArray(m.outputs)}, ${sqlStr(m.rounding_method)}, ${sqlArray(m.supported_scenarios)}, ${sqlBool(m.is_active)}, ${sqlInt(m.version_number, 1)}, ${sqlStr(m.admin_notes)})`
    )
    .join(',\n') + '\non conflict (calculation_method_code) do nothing;'
);
lines.push('');

lines.push('insert into action_recommendation_master');
lines.push(
  '  (recommendation_code, forecast_category, sub_category, scenario_name, scenario_description, variance_result, forecast_status, severity, action_type, action_title_template, action_content_template, financial_impact_template, calculation_method_code, required_input_fields, supported_placeholders, priority_score, country_code, currency_code, customer_segment, effective_from, effective_to, is_active, requires_ai, version_number, admin_notes, include_in_forecasting, include_in_monthly_report)'
);
lines.push('values');
lines.push(
  master
    .map((m) => {
      const isDataQuality = m.forecast_category === 'data_quality';
      return `  (${sqlStrRequired(m.recommendation_code)}, ${sqlStrRequired(m.forecast_category)}, ${sqlStrRequired(m.sub_category)}, ${sqlStrRequired(m.scenario_name)}, ${sqlStr(m.scenario_description)}, ${sqlStr(m.variance_result)}, ${sqlStrRequired(m.forecast_status)}, ${sqlStrRequired(m.severity)}, ${sqlStrRequired(m.action_type)}, ${sqlStrRequired(m.action_title_template)}, ${sqlStrRequired(m.action_content_template)}, ${sqlStr(m.financial_impact_template)}, ${sqlStr(m.calculation_method_code)}, ${sqlArray(m.required_input_fields)}, ${sqlArray(m.supported_placeholders)}, ${sqlInt(m.priority_score, 0)}, ${sqlStr(m.country_code)}, ${sqlStr(m.currency_code)}, ${sqlStrRequired(m.customer_segment || 'base')}, ${sqlDate(m.effective_from)}, ${sqlDate(m.effective_to)}, ${sqlBool(m.is_active)}, ${sqlBool(m.requires_ai)}, ${sqlInt(m.version_number, 1)}, ${sqlStr(m.admin_notes)}, ${isDataQuality ? 'false' : 'true'}, ${isDataQuality ? 'true' : 'false'})`;
    })
    .join(',\n') + '\non conflict (recommendation_code) do nothing;'
);
lines.push('');

lines.push('insert into action_recommendation_conditions');
lines.push('  (recommendation_code, condition_group, field_name, operator, comparison_value, comparison_value_2, data_type, logical_operator, evaluation_order, is_active)');
lines.push('values');
lines.push(
  conditions
    .map(
      (c) =>
        `  (${sqlStrRequired(c.recommendation_code)}, ${sqlInt(c.condition_group, 1)}, ${sqlStrRequired(c.field_name)}, ${sqlStrRequired(c.operator)}, ${sqlStr(c.comparison_value)}, ${sqlStr(c.comparison_value_2)}, ${sqlStrRequired(c.data_type)}, ${sqlStrRequired(c.logical_operator)}, ${sqlInt(c.evaluation_order, 1)}, ${sqlBool(c.is_active)})`
    )
    .join(',\n') + ';'
);
lines.push('');

fs.writeFileSync(OUT_FILE, lines.join('\n'), 'utf8');
console.log(`Wrote ${OUT_FILE}`);
console.log(`Rows: placeholders=${placeholders.length}, calcMethods=${calcMethods.length}, master=${master.length}, conditions=${conditions.length}`);
