#!/usr/bin/env python3
"""Investment Intelligence R6-P1 — independent certification oracle.

Stdlib only. Imports NOTHING from `lib/engines/investment-intelligence` or
any other TypeScript/production source in this repository — grep-verifiable
(the only imports below are `json`, `datetime`, `math`, `pathlib`, `sys`).
Its only inputs are `cases.json` (written by
`scripts/ii-r6p1-certification/generate_cases.mjs`, a separate,
production-independent generator) and this file's own transcription of the
researched tax rules (see ruleVersions.ts's header comments and
docs/investment-intelligence/R6P1_TAX_METHODOLOGY.md for the same sourcing
independently cited on the production side — this file does not read that
doc programmatically, it is a human cross-reference only).

Expected values are NEVER generated by calling production TypeScript code.
"""

import json
import sys
from datetime import date, timedelta
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CASES_PATH = REPO_ROOT / "scripts" / "ii-r6p1-certification" / "cases.json"
RESULTS_PATH = REPO_ROOT / "scripts" / "ii-r6p1-certification" / "oracle_results.json"


def parse_iso(d: str) -> date:
    y, m, dd = (int(x) for x in d.split("-"))
    return date(y, m, dd)


def iso(d: date) -> str:
    return d.isoformat()


def days_in_month(year: int, month: int) -> int:
    if month == 12:
        return (date(year + 1, 1, 1) - date(year, 12, 1)).days
    return (date(year, month + 1, 1) - date(year, month, 1)).days


def add_months_clamped(iso_date: str, months: int) -> str:
    d = parse_iso(iso_date)
    total_month_index0 = (d.month - 1) + months
    target_year = d.year + total_month_index0 // 12
    target_month0 = total_month_index0 % 12  # Python % always non-negative for positive divisor
    target_month = target_month0 + 1
    clamped_day = min(d.day, days_in_month(target_year, target_month))
    return iso(date(target_year, target_month, clamped_day))


def add_days(iso_date: str, n: int) -> str:
    return iso(parse_iso(iso_date) + timedelta(days=n))


def holding_days(acq: str, disp: str) -> int:
    return (parse_iso(disp) - parse_iso(acq)).days


# ---------------------------------------------------------------------------
# Rule versions — independently transcribed (not imported) from the same
# researched sources cited in ruleVersions.ts: Finance Act 2023 (debt-
# specified-fund rule, FY2023-24 onward), Finance (No. 2) Act 2024 (equity
# rate change effective 23 July 2024), and the Income-tax Act 2025 (in force
# from 1 April 2026). R6-FINAL closure (2026-08-22) independently re-verified
# the 2025 Act row against indiankanoon.org's transcription of the enacted
# Act text (Sections 196/198) plus five corroborating secondary sources —
# same 20%/12.5%/Rs 1,25,000 figures as the pre-transition row, confirmed as
# a renumbering with no rate change, not assumed. See
# docs/investment-intelligence/R6_TAX_LEGAL_SOURCE_REGISTER.md.
# ---------------------------------------------------------------------------
RULE_VERSIONS = [
    {
        "version": "1961_act_pre_20240723",
        "effective_from": "2023-04-01",
        "effective_to": "2024-07-22",
        "placeholder": False,
        "stcg_rate_pct": 15,
        "ltcg_rate_pct": 10,
        "ltcg_exemption_inr": 100000,
    },
    {
        "version": "1961_act_post_20240723",
        "effective_from": "2024-07-23",
        "effective_to": "2026-03-31",
        "placeholder": False,
        "stcg_rate_pct": 20,
        "ltcg_rate_pct": 12.5,
        "ltcg_exemption_inr": 125000,
    },
    {
        "version": "2025_act_post_20260401",
        "effective_from": "2026-04-01",
        "effective_to": None,
        "placeholder": False,
        "stcg_rate_pct": 20,
        "ltcg_rate_pct": 12.5,
        "ltcg_exemption_inr": 125000,
    },
]


def resolve_rule_version(disposal_date: str) -> dict:
    for v in RULE_VERSIONS:
        if disposal_date >= v["effective_from"] and (v["effective_to"] is None or disposal_date <= v["effective_to"]):
            return v
    raise ValueError(f"No rule version covers {disposal_date}")


def financial_year_of(d: str) -> str:
    dt = parse_iso(d)
    start_year = dt.year if dt.month >= 4 else dt.year - 1
    return f"FY{start_year}-{str((start_year + 1) % 100).zfill(2)}"


def financial_year_end(fy: str) -> str:
    start_year = int(fy[2:6])
    return f"{start_year + 1}-03-31"


# ---------------------------------------------------------------------------
# Family oracles
# ---------------------------------------------------------------------------

def oracle_fifo(case: dict) -> dict:
    lots = []
    for a in case["acquisitions"]:
        lots.append({"acquisitionDate": a["acquisitionDate"], "remaining": a["units"], "costPerUnit": a["costPerUnit"]})
    lots.sort(key=lambda l: l["acquisitionDate"])

    result_by_disposal = {}
    for disp in case["disposals"]:
        remaining_to_consume = disp["units"]
        consumed = []
        for lot in lots:
            if remaining_to_consume <= 1e-9:
                break
            if lot["remaining"] <= 1e-9:
                continue
            take = min(lot["remaining"], remaining_to_consume)
            lot["remaining"] -= take
            consumed.append({
                "acquisitionDate": lot["acquisitionDate"],
                "unitsConsumed": round(take, 6),
                "costBasis": round(take * lot["costPerUnit"], 2),
            })
            remaining_to_consume -= take
        if remaining_to_consume > 1e-6:
            raise ValueError(f"{case['id']}: disposal exceeds available lot balance by {remaining_to_consume}")
        total_cost_basis = round(sum(c["costBasis"] for c in consumed), 2)
        total_units = round(sum(c["unitsConsumed"] for c in consumed), 6)
        result_by_disposal[disp["sourceEventId"]] = {
            "consumedLots": consumed,
            "totalCostBasis": total_cost_basis,
            "totalUnitsConsumed": total_units,
        }
    return {"byDisposal": result_by_disposal}


def oracle_grandfathering(case: dict) -> dict:
    actual = case["actualCostPerUnit"]
    sale = case["salePricePerUnit"]
    fmv = case["fmvPerUnit"]
    acq = case["acquisitionDate"]

    if not case.get("isEquityOriented", True):
        return {"basisSource": "not_applicable", "costBasisPerUnit": round(actual, 6)}
    if acq >= "2018-02-01":
        return {"basisSource": "not_applicable", "costBasisPerUnit": round(actual, 6)}
    if fmv is None:
        return {"basisSource": "fmv_unavailable", "costBasisPerUnit": round(actual, 6)}

    # THE FORMULA: max(actualCost, min(fmv, salePrice)).
    lower_of_fmv_and_sale = min(fmv, sale)
    cost_basis = max(actual, lower_of_fmv_and_sale)
    basis_source = "fmv_grandfathered" if cost_basis > actual else "actual_cost"
    return {"basisSource": basis_source, "costBasisPerUnit": round(cost_basis, 6)}


def oracle_boundary(case: dict) -> dict:
    acq = case["acquisitionDate"]
    disp = case["disposalDate"]
    months = case["thresholdMonths"]
    anniversary = add_months_clamped(acq, months)
    is_long_term = disp > anniversary  # strictly after
    return {
        "isLongTerm": is_long_term,
        "holdingDays": holding_days(acq, disp),
        "anniversaryDate": anniversary,
    }


SPECIFIED_FUND_CUTOFF = "2023-04-01"  # Section 50AA / Finance Act 2023
BUDGET_2024_BOUNDARY = "2024-07-23"  # Finance (No. 2) Act, 2024


def oracle_debt(case: dict) -> dict:
    """Covers BOTH the 'debt' family (all fixtures acquired on/after the
    Section 50AA cutoff -> always STCG, unchanged R6-P1 behaviour) and the
    'debt_pre2023' family (R6-DEBTFIX, 2026-08-22: fixtures acquired BEFORE
    the cutoff -> legacy debt-fund treatment, keyed by the DISPOSAL date's
    own rule window, per ruleVersions.ts's LegacyDebtFundRegime / the
    R6_TAX_LEGAL_SOURCE_REGISTER.md Section 4a research)."""
    acq = case["acquisitionDate"]
    disp = case["disposalDate"]
    units = case["unitsConsumed"]
    cost_basis = round(units * case["costPerUnit"], 2)
    sale_value = round(units * case["salePricePerUnit"], 2)
    taxable_gain = round(sale_value - cost_basis, 2)  # never indexed, either branch

    if acq >= SPECIFIED_FUND_CUTOFF:
        # Section 50AA: always short-term, regardless of holding period.
        return {
            "gainType": "stcg",
            "holdingDays": holding_days(acq, disp),
            "costBasisUsed": cost_basis,
            "saleValue": sale_value,
            "taxableGain": taxable_gain,
        }

    # Acquired before the cutoff: legacy regime, threshold/rate depends on
    # which side of the 23-Jul-2024 Budget boundary the DISPOSAL falls.
    threshold_months = 36 if disp < BUDGET_2024_BOUNDARY else 24
    anniversary = add_months_clamped(acq, threshold_months)
    is_long_term = disp > anniversary
    gain_type = "ltcg" if is_long_term else "stcg"
    return {
        "gainType": gain_type,
        "holdingDays": holding_days(acq, disp),
        "costBasisUsed": cost_basis,
        "saleValue": sale_value,
        "taxableGain": taxable_gain,
    }


def oracle_fy_aggregation(case: dict) -> dict:
    by_fy = {}
    for d in case["disposals"]:
        fy = financial_year_of(d["disposalDate"])
        by_fy.setdefault(fy, []).append(d)

    out = {}
    for fy, disposals in by_fy.items():
        fy_end = financial_year_end(fy)
        rule = resolve_rule_version(fy_end)
        exemption_threshold = rule["ltcg_exemption_inr"]
        total = round(sum(d["taxableGain"] for d in disposals), 2)
        exemption_applied = round(min(max(total, 0), exemption_threshold), 2)
        taxable_after = round(max(total - exemption_applied, 0), 2)
        out[fy] = {
            "exemptionThresholdInr": exemption_threshold,
            "exemptionRuleVersion": rule["version"],
            "totalLtcgBeforeExemption": total,
            "exemptionApplied": exemption_applied,
            "taxableLtcgAfterExemption": taxable_after,
            "contributingDisposalCount": len(disposals),
        }
    return {"byFinancialYear": out}


def oracle_exit_load(case: dict) -> dict:
    acq = case["acquisitionDate"]
    disp = case["disposalDate"]
    hd = holding_days(acq, disp)
    tiers = sorted(case["tiers"], key=lambda t: t["uptoDays"])
    load_pct = 0
    for t in tiers:
        if hd <= t["uptoDays"]:
            load_pct = t["loadPct"]
            break
    amount = round(case["saleValueApportioned"] * load_pct / 100, 2)
    return {"holdingDays": hd, "applicableLoadPct": load_pct, "exitLoadAmount": amount}


def oracle_ambiguous(case: dict) -> dict:
    return {"gainType": "unresolved", "taxableGain": None}


def oracle_rate_version(case: dict) -> dict:
    rule = resolve_rule_version(case["disposalDate"])
    return {
        "ruleVersion": rule["version"],
        "placeholder": rule["placeholder"],
        "stcgRatePct": rule["stcg_rate_pct"],
        "ltcgRatePct": rule["ltcg_rate_pct"],
        "ltcgExemptionThresholdInr": rule["ltcg_exemption_inr"],
    }


def oracle_act_transition(case: dict) -> dict:
    # R6-FINAL closure, Section 10: full disposal-tax computation (rule
    # version + holding-period STCG/LTCG split + grandfathering-if-applicable)
    # for a disposal dated either side of the 1961 Act -> 2025 Act boundary.
    acq = case["acquisitionDate"]
    disp = case["disposalDate"]
    units = case["unitsConsumed"]
    cost_per_unit = case["costPerUnit"]
    sale_per_unit = case["salePricePerUnit"]
    sale_value = round(units * sale_per_unit, 2)
    cost_basis = round(units * cost_per_unit, 2)

    rule = resolve_rule_version(disp)
    anniversary = add_months_clamped(acq, 12)
    is_long_term = disp > anniversary
    gain_type = "ltcg" if is_long_term else "stcg"
    # All ACTTRANS fixtures acquire on/after 2018-02-01 (post grandfathering
    # cutoff), so grandfathering never applies here — cost basis is plain.
    taxable_gain = round(sale_value - cost_basis, 2)

    return {
        "ruleVersion": rule["version"],
        "placeholder": rule["placeholder"],
        "gainType": gain_type,
        "costBasisUsed": cost_basis,
        "saleValue": sale_value,
        "taxableGain": taxable_gain,
    }


def oracle_grand_boundary(case: dict) -> dict:
    # R6-FINAL closure, Section 11: full disposal-tax computation straddling
    # the 31-Jan/1-Feb-2018 grandfathering eligibility cutoff, disposed under
    # the 2025 Act (disposalDate 2026-06-15) to also exercise continuity.
    acq = case["acquisitionDate"]
    disp = case["disposalDate"]
    units = case["unitsConsumed"]
    cost_per_unit = case["costPerUnit"]
    fmv = case["fmvPerUnit"]
    sale_per_unit = case["salePricePerUnit"]
    sale_value = round(units * sale_per_unit, 2)

    rule = resolve_rule_version(disp)
    # All fixtures here are long-term by construction (2018 acquisition,
    # 2026 disposal) — no need to re-derive the STCG/LTCG split.
    eligible = acq < "2018-02-01"
    if eligible:
        lower_of_fmv_and_sale = min(fmv, sale_per_unit)
        basis_per_unit = max(cost_per_unit, lower_of_fmv_and_sale)
        basis_source = "fmv_grandfathered" if basis_per_unit > cost_per_unit else "actual_cost"
    else:
        basis_per_unit = cost_per_unit
        basis_source = "not_applicable"
    cost_basis = round(units * basis_per_unit, 2)
    taxable_gain = round(sale_value - cost_basis, 2)

    return {
        "ruleVersion": rule["version"],
        "grandfatheringEligible": eligible,
        "basisSource": basis_source,
        "costBasisUsed": cost_basis,
        "saleValue": sale_value,
        "taxableGain": taxable_gain,
    }


FAMILY_ORACLES = {
    "fifo": oracle_fifo,
    "grandfathering": oracle_grandfathering,
    "boundary": oracle_boundary,
    "debt": oracle_debt,
    "debt_pre2023": oracle_debt,
    "fy_aggregation": oracle_fy_aggregation,
    "cross_fy": oracle_fy_aggregation,  # same aggregation logic, different fixture emphasis
    "exit_load": oracle_exit_load,
    "ambiguous": oracle_ambiguous,
    "rate_version": oracle_rate_version,
    "act_transition": oracle_act_transition,
    "grand_boundary": oracle_grand_boundary,
}


def main() -> int:
    if not CASES_PATH.exists():
        print(f"cases.json not found at {CASES_PATH} — run generate_cases.mjs first.", file=sys.stderr)
        return 1

    data = json.loads(CASES_PATH.read_text(encoding="utf-8"))
    cases = data["cases"]

    results = {}
    counts = {}
    for case in cases:
        fam = case["family"]
        oracle = FAMILY_ORACLES.get(fam)
        if oracle is None:
            raise ValueError(f"No oracle registered for family {fam}")
        results[case["id"]] = oracle(case)
        counts[fam] = counts.get(fam, 0) + 1

    # newline='' prevents Python's universal-newline translation from turning
    # json.dumps's '\n' line separators into CRLF on Windows — this repo's
    # convention (and a prior CRLF-broke-an-exact-match-test incident) requires LF.
    RESULTS_PATH.write_text(json.dumps({"cases": results}, indent=2, sort_keys=True), encoding="utf-8", newline="")
    print(f"Computed {len(results)} oracle results -> {RESULTS_PATH}")
    print("By family:", counts)
    return 0


if __name__ == "__main__":
    sys.exit(main())
