// NAV 1 Stage D — generate (or refresh) the AMFI fund-house seed for
// ii_amfi_fund_houses (migration 0191).
//
// WHY THIS EXISTS. On-demand hydration needs each scheme's AMFI fund-house
// code, because AMFI's NAV history report can only be filtered by fund house.
// It used to discover that by probing all 150 codes on every cold server
// process -- a burst that AMFI appears to throttle from the production
// server's address: the second real production hydration run (2026-09-24)
// stalled with nothing recorded. The codes are now stored once and resolved
// through ii_scheme_master.amc_name, so a hydration run sends AMFI no probes.
//
// WHAT IT DOES. Asks AMFI for one full business day per fund-house code
// (4 requests in flight -- gentle, and run by an operator, never by the
// server), reads the fund-house NAME from each response with the production
// parser, and prints an idempotent SQL upsert. Nothing is hand-typed.
//
// Run: npx tsx scripts/pc6_amfi_fund_houses_seed.ts [dd-Mon-yyyy]
//   e.g. npx tsx scripts/pc6_amfi_fund_houses_seed.ts 22-Sep-2026
// then apply the printed SQL (or paste it into a new migration).

import { parseNavHistory } from '../lib/services/investment-intelligence/pc6/amfiParser';
import { classifyAmfiHistoryBody } from '../lib/services/investment-intelligence/pc6/adapters/amfiHistoricalAdapter';

const MAX_CODE = 150;
const MIN_SCHEMES = 5000; // a full business day; a weekend or holiday has a few hundred
const MONTHS: Record<string, string> = { Jan: '01', Feb: '02', Mar: '03', Apr: '04', May: '05', Jun: '06', Jul: '07', Aug: '08', Sep: '09', Oct: '10', Nov: '11', Dec: '12' };

(async () => {
  const day = process.argv[2];
  if (!day || !/^\d{2}-[A-Z][a-z]{2}-\d{4}$/.test(day)) { console.error('usage: npx tsx scripts/pc6_amfi_fund_houses_seed.ts dd-Mon-yyyy (a full business day)'); process.exit(2); }
  const [dd, mon, yyyy] = day.split('-');
  const iso = `${yyyy}-${MONTHS[mon]}-${dd}`;

  const found: { code: number; name: string; schemes: number }[] = [];
  const problems: string[] = [];
  const codes = Array.from({ length: MAX_CODE }, (_, i) => i + 1);
  const worker = async () => {
    for (let mf = codes.shift(); mf !== undefined; mf = codes.shift()) {
      const res = await fetch(`https://portal.amfiindia.com/DownloadNAVHistoryReport_Po.aspx?mf=${mf}&frmdt=${day}&todt=${day}`, { headers: { 'User-Agent': 'FHIP-PC6/1.0 (fund-house seed)' } });
      const body = await res.text();
      const kind = classifyAmfiHistoryBody(body);
      if (kind === 'no_data') continue;
      if (kind === 'unrecognised') { problems.push(`mf=${mf}: unrecognised response (HTTP ${res.status})`); continue; }
      const parsed = parseNavHistory(new TextEncoder().encode(body), { asOfDate: iso });
      if (parsed.amcNames.length !== 1) { problems.push(`mf=${mf}: ${parsed.amcNames.length} fund-house names ${JSON.stringify(parsed.amcNames)}`); continue; }
      found.push({ code: mf, name: parsed.amcNames[0], schemes: new Set(parsed.records.map((r) => r.amfiSchemeCode)).size });
    }
  };
  await Promise.all(Array.from({ length: 4 }, worker));
  found.sort((a, b) => a.code - b.code);

  const schemes = found.reduce((s, f) => s + f.schemes, 0);
  const names = found.map((f) => f.name.toLowerCase());
  if (problems.length) { console.error('REFUSING -- problems:\n  ' + problems.join('\n  ')); process.exit(3); }
  if (schemes < MIN_SCHEMES) { console.error(`REFUSING -- ${day} covered only ${schemes} schemes; pick a full business day`); process.exit(3); }
  if (new Set(names).size !== names.length) { console.error('REFUSING -- two codes share a fund-house name'); process.exit(3); }

  const esc = (s: string) => s.replace(/'/g, "''");
  console.log(`-- Generated by scripts/pc6_amfi_fund_houses_seed.ts from AMFI's NAV history report for ${day}:`);
  console.log(`-- ${found.length} fund houses, ${schemes} schemes. Idempotent.`);
  console.log('insert into ii_amfi_fund_houses (fund_house_code, amc_name, observed_on) values');
  console.log(found.map((f) => `  (${f.code}, '${esc(f.name)}', '${iso}')`).join(',\n'));
  console.log('on conflict (fund_house_code) do update\n  set amc_name = excluded.amc_name, observed_on = excluded.observed_on, updated_at = now();');
})();
