/**
 * R8 — independent oracle comparison harness (spec sections 65-66, 70).
 *
 * Runs the SAME fixture cases (`tests/fixtures/r8/independent_oracle_cases
 * .json`) through the REAL production engine (`lib/financial-data-hub/
 * classification/*`) and diffs the result field-by-field against
 * `scripts/r8_independent_classification_oracle.py`'s frozen, independently
 * re-implemented expectation (`tests/fixtures/r8/oracle_output.json`,
 * regenerated by this script before comparing — always fresh, never stale).
 *
 * The reference data fed to the real engine here is a small, hand-built set
 * that mirrors what the Python oracle hard-codes (4 merchants, ~10
 * narrative rules) — deliberately NOT the real 60-row FDH-2 seed or the
 * production `classificationRules.mjs` file, so a bug in either the real
 * engine OR the real seed data has an independent chance of being caught by
 * a genuinely different code path computing the same expectation.
 *
 * Usage: npx tsx scripts/r8_oracle_compare.ts
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { classifyTransaction } from '../lib/financial-data-hub/classification/economicTypeEngine';
import { matchInternalTransfers, type TransferCandidateTxn } from '../lib/financial-data-hub/classification/transferMatching';
import { matchRefundsToOriginals, type RefundCandidateTxn } from '../lib/financial-data-hub/classification/refundReversalMatching';
import { detectRecurringSeries, type RecurringCandidateTxn } from '../lib/financial-data-hub/classification/recurringDetection';
import type { ClassifiableTransaction, ClassificationReferenceData } from '../lib/financial-data-hub/classification/types';
import type { FdhCategory, FdhClassificationRule, FdhMerchant } from '../lib/financial-data-hub/domain/types';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');
const FIXTURES = path.join(ROOT, 'tests', 'fixtures', 'r8');
const CASE_FILE = path.join(FIXTURES, 'independent_oracle_cases.json');
const ORACLE_OUTPUT_FILE = path.join(FIXTURES, 'oracle_output.json');

console.log('Regenerating oracle output (Python, independent implementation)...');
execFileSync('python', [path.join(HERE, 'r8_independent_classification_oracle.py'), CASE_FILE, '-o', ORACLE_OUTPUT_FILE], {
  cwd: ROOT,
  stdio: 'inherit',
});

const cases = JSON.parse(fs.readFileSync(CASE_FILE, 'utf8'));
const oracle = JSON.parse(fs.readFileSync(ORACLE_OUTPUT_FILE, 'utf8'));

let comparisons = 0;
let mismatches = 0;
const fail = (label: string, expected: unknown, actual: unknown) => {
  mismatches += 1;
  console.log(`  MISMATCH  ${label}: expected=${JSON.stringify(expected)} actual=${JSON.stringify(actual)}`);
};
const cmp = (label: string, expected: unknown, actual: unknown) => {
  comparisons += 1;
  if (JSON.stringify(expected) !== JSON.stringify(actual)) fail(label, expected, actual);
};

// --- Reference data mirroring the Python oracle's hard-coded tables ---
const category = (id: string, key: string): FdhCategory => ({
  id, category_key: key, display_name: key, description: null, economic_type: 'expense',
  country_applicability: ['AU', 'IN'], essential_discretionary: 'essential', tax_reporting_flag: false,
  fhip_mapping_key: null, display_order: 1, icon_key: null, active: true, version: 1,
  created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z',
});
const merchant = (id: string, name: string, categoryId: string): FdhMerchant => ({
  id, canonical_name: name, display_name: name, country_code: 'AU', merchant_type: 'retail',
  default_category_id: categoryId, default_subcategory_id: null, mcc: null, subscription_possible: false,
  essential_discretionary: 'essential', verification_status: 'approved', merged_into_merchant_id: null,
  active: true, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z',
  recurring_possible: null, typical_frequency: null, fixed_amount_expected: null, variable_amount_possible: null,
  recurring_type: null, is_payment_processor: null,
});
const rule = (id: string, required: string[], excluded: string[], economicType: string, priority = 200): FdhClassificationRule => ({
  id, rule_key: id, rule_type: 'narrative_pattern', country_applicability: ['AU', 'IN'],
  match_definition: { match_kind: 'narrative_pattern', required_terms_normalised: required, excluded_terms_normalised: excluded.length ? excluded : undefined },
  action_definition: { action_kind: 'classify', economic_transaction_type: economicType as never },
  priority, status: 'approved', active: true, version: 1,
  created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z',
});

const catGroceries = category('cat-groceries', 'groceries');
const catEntertainment = category('cat-entertainment', 'entertainment_subscriptions');
const ref: ClassificationReferenceData = {
  categories: [catGroceries, catEntertainment],
  subcategories: [],
  merchants: [
    merchant('m-woolworths', 'WOOLWORTHS', catGroceries.id),
    merchant('m-coles', 'COLES', catGroceries.id),
    merchant('m-netflix', 'NETFLIX', catEntertainment.id),
    merchant('m-spotify', 'SPOTIFY', catEntertainment.id),
  ],
  merchantAliases: [],
  globalRules: [
    rule('r-salary', ['SALARY'], ['SALARY SACRIFICE', 'SALARY PACKAGING'], 'income'),
    rule('r-payroll', ['PAYROLL'], [], 'income'),
    rule('r-wages', ['WAGES'], [], 'income'),
    rule('r-interest-credited', ['INTEREST CREDITED'], [], 'income'),
    rule('r-interest-charged', ['INTEREST CHARGED'], [], 'debt_interest'),
    rule('r-account-fee', ['ACCOUNT FEE'], ['FEE WAIVED', 'FEE REFUND', 'FEE REVERSED'], 'fee'),
    rule('r-monthly-fee', ['MONTHLY FEE'], ['FEE WAIVED'], 'fee'),
    rule('r-atm', ['ATM WITHDRAWAL'], [], 'cash_withdrawal'),
    rule('r-cash', ['CASH WITHDRAWAL'], [], 'cash_withdrawal'),
    rule('r-refund', ['REFUND'], [], 'refund'),
    rule('r-reversal', ['REVERSAL'], [], 'refund'),
    rule('r-chargeback', ['CHARGEBACK'], [], 'refund'),
  ],
  userRules: [],
};

console.log('\n=== Economic-type classification ===');
for (const c of cases.economic_type_cases) {
  const oracleCase = oracle.economic_type.find((o: { id: string }) => o.id === c.id);
  const txn: ClassifiableTransaction = {
    id: c.id, financial_account_id: 'acc-1', transaction_date: '2026-03-01', description_clean: c.description,
    merchant_raw: null, amount_original: 10, currency_original: 'AUD', credit_debit: c.credit_debit,
    transaction_type_hint: 'unknown', user_override: false,
  };
  const result = classifyTransaction(txn, null, ref);
  cmp(`${c.id} economic_type`, oracleCase.economic_type, result.economicTransactionType);
}

console.log('\n=== Transfer pairing ===');
for (const c of cases.transfer_cases) {
  const oracleCase = oracle.transfers.find((o: { id: string }) => o.id === c.id);
  const txns: TransferCandidateTxn[] = c.transactions.map((t: Record<string, string>) => ({
    id: t.id, financialAccountId: t.financial_account_id, transactionDate: t.transaction_date,
    amountOriginal: Number(t.amount_original), currencyOriginal: t.currency_original, creditDebit: t.credit_debit as never,
    descriptionClean: null, sourceReference: null,
  }));
  const links = matchInternalTransfers(txns, new Map(), c.date_window_days ?? 3);
  const actualPairs = links.map((l) => ({ from: l.transactionIdFrom, to: l.transactionIdTo })).sort((a, b) => a.from.localeCompare(b.from));
  const expectedPairs = [...oracleCase.pairs].map((p: { from: string; to: string }) => ({ from: p.from, to: p.to })).sort((a: { from: string }, b: { from: string }) => a.from.localeCompare(b.from));
  cmp(`${c.id} transfer pairs`, expectedPairs, actualPairs);
}

console.log('\n=== Refund/reversal linking ===');
for (const c of cases.refund_cases) {
  const oracleCase = oracle.refunds.find((o: { id: string }) => o.id === c.id);
  const isRefund = new Set<string>(c.is_refund_ids);
  const txns: RefundCandidateTxn[] = c.transactions.map((t: Record<string, string>) => ({
    id: t.id, financialAccountId: t.financial_account_id, transactionDate: t.transaction_date,
    amountOriginal: Number(t.amount_original), currencyOriginal: t.currency_original, creditDebit: t.credit_debit as never,
    isRefundClassified: isRefund.has(t.id),
  }));
  const links = matchRefundsToOriginals(txns);
  const actualLinks = links.map((l) => ({ refund: l.refundTransactionId, original: l.originalTransactionId }));
  cmp(`${c.id} refund links`, oracleCase.links, actualLinks);
}

console.log('\n=== Recurring-series detection ===');
for (const c of cases.recurring_cases) {
  const oracleCase = oracle.recurring.find((o: { id: string }) => o.id === c.id);
  const txns: RecurringCandidateTxn[] = c.transactions.map((t: Record<string, string>) => ({
    id: t.id, transactionDate: t.transaction_date, amountOriginal: 15, currencyOriginal: 'AUD',
    creditDebit: t.credit_debit as never, merchantId: t.merchant_id ?? null, descriptionClean: null,
    financialAccountId: t.financial_account_id,
  }));
  const series = detectRecurringSeries(txns);
  const actualSeries = series.map((s) => ({ frequency: s.frequency, members: [...s.memberTransactionIds].sort(), insufficient_history: s.insufficientHistory }));
  const expectedSeries = oracleCase.series.map((s: { frequency: string; members: string[]; insufficient_history: boolean }) => ({
    frequency: s.frequency, members: [...s.members].sort(), insufficient_history: s.insufficient_history,
  }));
  cmp(`${c.id} recurring series`, expectedSeries, actualSeries);
}

console.log(`\n=== RESULT: ${comparisons} comparisons, ${mismatches} mismatches ===`);
process.exit(mismatches === 0 ? 0 : 1);
