/**
 * Builds scripts/canonical_cert/dev_residue_ALL_for_PO.sql -- ONE guarded,
 * one-transaction, row-count-asserting DEV cleanup for every row the four
 * stage-3 certifiers could not remove through the service role (the applied
 * card/loan chains the import-bridge guards protect; GP-H1).
 *
 * Sources (each certifier's own PO file, parsed, never retyped):
 *   golden_pair/dev_residue_A_liability_chains.sql      range A
 *   econ/dev_residue_B_liability_chains.sql             range B
 *   scaleui/dev_residue_C_liability_retirement.sql      range C (hand-mirrored below: it restores a fixture row)
 *   secrev/dev_residue_D_liability_chain.sql            range D
 *
 *   node scripts/canonical_cert/build_dev_residue_all_sql.mjs          -> writes the file
 *   node scripts/canonical_cert/build_dev_residue_all_sql.mjs --check  -> exit 1 if the file is stale
 *
 * renderResidueSql(spec) is also used by tests/unit/canonicalCertResidueAllSql.test.ts, which runs the
 * rendered SQL on the real migration chain (PGlite) against synthetic applied chains, including the
 * negative controls (a production policy row, a wrong expected count, a non-synthetic owner).
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));

/** Emails of the synthetic fixture users (USER_RANGES.json): FCAST + E2E50. Anything else is refused. */
export const SYNTHETIC_EMAIL_PATTERNS = ['%@example.test', '%@test.fhip.invalid'];

/** Delete order proven on the real migration chain (tests/unit/gpImportChainDeletion.test.ts + the
 *  combined test): applications first (frees liabilities.last_import_application_id), then proposals,
 *  liability statements, facility accounts, liabilities, uploads. */
export const DELETE_ORDER = ['fhip_import_applications', 'fhip_import_proposals', 'fdh_liability_statements', 'fdh_financial_accounts', 'liabilities', 'fdh_statement_uploads'];

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const idList = (ids) => ids.map(q).join(', ');

/** Parses a certifier file of `delete from T where [user_id = 'u' and ]id in (...); -- expect N` lines. */
export function parseSimpleResidueFile(text, label) {
  const deletes = [];
  const re = /delete from (\w+) where (?:user_id = '([0-9a-f-]{36})' and )?id in \(([^)]*)\);\s*-- expect (\d+)/g;
  let m;
  while ((m = re.exec(text))) {
    const ids = [...m[3].matchAll(/'([0-9a-f-]{36})'/g)].map((x) => x[1]);
    if (ids.length !== Number(m[4])) throw new Error(`${label}: ${m[1]} lists ${ids.length} ids but expects ${m[4]}`);
    deletes.push({ table: m[1], userId: m[2] ?? null, ids });
  }
  if (deletes.length === 0) throw new Error(`${label}: no delete lines parsed`);
  return deletes;
}

/**
 * spec = { title, sections: [{ label, preUpdates?: [{ table, id, userId, set, expect }], deletes: [{ table, userId, ids }] }] }
 * Emits: DEV guard -> ownership/presence pre-check of EVERY targeted row -> updates -> deletes (DELETE_ORDER),
 * each with an asserted row count, all inside ONE transaction (any exception rolls everything back).
 */
export function renderResidueSql(spec) {
  const lines = [];
  const L = (s = '') => lines.push(s);
  const emailOk = (alias) => `(${SYNTHETIC_EMAIL_PATTERNS.map((p) => `${alias}.email like ${q(p)}`).join(' or ')})`;
  let total = 0;
  for (const s of spec.sections) for (const d of s.deletes) total += d.ids.length;
  const updates = spec.sections.reduce((n, s) => n + (s.preUpdates?.length ?? 0), 0);

  L(`-- ${spec.title}`);
  L('-- GENERATED by scripts/canonical_cert/build_dev_residue_all_sql.mjs -- do not hand-edit; re-run the builder.');
  L('--');
  L('-- DEV ONLY (vqycarelcoijzwlpkpcz). Paste the WHOLE file into the DEV Supabase SQL editor and run it once.');
  L(`-- It deletes ${total} rows and restores ${updates} fixture row(s), all created/changed by the stage-3 certifiers,`);
  L('-- in ONE transaction. It REFUSES (raises, nothing changes) unless:');
  L("--   * ii_nav_retention_policy has an environment='dev' row and NO environment='production' row;");
  L('--   * every targeted row exists and belongs to a synthetic fixture user (email @example.test / @test.fhip.invalid);');
  L('--   * every UPDATE / DELETE touches exactly the expected number of rows.');
  L('-- Expected result: NOTICE "canonical-cert residue removed: ..." and COMMIT. Any ERROR means nothing was changed.');
  for (const s of spec.sections) {
    const byTable = {};
    for (const d of s.deletes) byTable[d.table] = (byTable[d.table] ?? 0) + d.ids.length;
    L(`--   ${s.label}: ${Object.entries(byTable).map(([t, n]) => `${t} ${n}`).join(', ')}${s.preUpdates?.length ? `; restores ${s.preUpdates.length} fixture row(s)` : ''}`);
  }
  L();
  L('begin;');
  L();
  L('-- The applied-chain rows are guarded by the import-bridge triggers; this transaction-local setting is the');
  L('-- documented internal-write path (the same one every SECURITY DEFINER Apply uses). It ends with the transaction.');
  L("select set_config('fhip.import_bridge_internal_write', 'true', true);");
  L();
  L('do $$');
  L('declare');
  L('  n int;');
  L('begin');
  L('  -- 0. Environment guard.');
  L("  if not exists (select 1 from ii_nav_retention_policy where environment = 'dev') then");
  L("    raise exception 'REFUSED: no dev row in ii_nav_retention_policy -- this is not the DEV database';");
  L('  end if;');
  L("  if exists (select 1 from ii_nav_retention_policy where environment = 'production') then");
  L("    raise exception 'REFUSED: ii_nav_retention_policy has a production row -- this is PRODUCTION';");
  L('  end if;');
  L();
  L('  -- 1. Every targeted row must exist and belong to a synthetic fixture user (checked BEFORE any change).');
  for (const s of spec.sections) {
    for (const u of s.preUpdates ?? []) {
      L(`  select count(*) into n from ${u.table} t join auth.users u on u.id = t.user_id where t.id = ${q(u.id)} and t.user_id = ${q(u.userId)} and ${emailOk('u')};`);
      L(`  if n <> 1 then raise exception 'REFUSED (${s.label}): ${u.table} ${u.id} -- % synthetic-owned rows (expected 1)', n; end if;`);
    }
    for (const d of s.deletes) {
      const userClause = d.userId ? ` and t.user_id = ${q(d.userId)}` : '';
      L(`  select count(*) into n from ${d.table} t join auth.users u on u.id = t.user_id where t.id in (${idList(d.ids)})${userClause} and ${emailOk('u')};`);
      L(`  if n <> ${d.ids.length} then raise exception 'REFUSED (${s.label}): ${d.table} -- % synthetic-owned rows present (expected ${d.ids.length})', n; end if;`);
    }
  }
  L();
  L('  -- 2. Restore fixture rows the certifiers changed (before the deletes free their links).');
  for (const s of spec.sections) {
    for (const u of s.preUpdates ?? []) {
      L(`  update ${u.table} set ${u.set} where id = ${q(u.id)} and user_id = ${q(u.userId)};`);
      L(`  get diagnostics n = row_count; if n <> ${u.expect} then raise exception '${s.label}: update ${u.table} ${u.id}: % rows (expected ${u.expect})', n; end if;`);
    }
  }
  L();
  L(`  -- 3. Deletes, one table at a time across all ranges, in the proven order: ${DELETE_ORDER.join(' -> ')}.`);
  for (const table of DELETE_ORDER) {
    for (const s of spec.sections) {
      for (const d of s.deletes.filter((x) => x.table === table)) {
        const userClause = d.userId ? `user_id = ${q(d.userId)} and ` : '';
        L(`  delete from ${table} where ${userClause}id in (${idList(d.ids)});`);
        L(`  get diagnostics n = row_count; if n <> ${d.ids.length} then raise exception '${s.label}: delete ${table}: % rows (expected ${d.ids.length})', n; end if;`);
      }
    }
  }
  const unknown = spec.sections.flatMap((s) => s.deletes.map((d) => d.table)).filter((t) => !DELETE_ORDER.includes(t));
  if (unknown.length) throw new Error(`tables outside DELETE_ORDER: ${[...new Set(unknown)].join(', ')}`);
  L();
  L(`  raise notice 'canonical-cert residue removed: % rows deleted, % fixture row(s) restored', ${total}, ${updates};`);
  L('end $$;');
  L();
  L('commit;');
  L();
  L('-- Afterwards (optional, read-only): every count below must be 0.');
  for (const table of DELETE_ORDER) {
    const ids = spec.sections.flatMap((s) => s.deletes.filter((d) => d.table === table).flatMap((d) => d.ids));
    if (ids.length) L(`select ${q(table)} as table_name, count(*) as remaining from ${table} where id in (${idList(ids)});`);
  }
  return `${lines.join('\n')}\n`;
}

/** Range C mirrors scaleui/dev_residue_C_liability_retirement.sql (restore + unlink + 8 deletes). */
function rangeC() {
  const u = 'e9ff2441-05bf-441d-8d2c-a7c7549d6ec7';
  return {
    label: 'range C (scale+UI, fhip.e2e.tc001)',
    preUpdates: [
      { table: 'retirement_accounts', id: '7d09f0be-30a9-5efa-98da-3babf1d12405', userId: u, expect: 1,
        set: "source_type = 'manual', last_import_application_id = null, last_imported_at = null, current_balance = 9600, employer_contribution = 524.40, contribution_frequency = 'monthly'" },
      { table: 'liabilities', id: '05bf0114-77d0-464c-9a15-446b67038666', userId: u, expect: 1, set: 'last_import_application_id = null' },
    ],
    deletes: [
      { table: 'fhip_import_applications', userId: u, ids: ['458ddd7b-1ab2-44e7-b900-feab48e768df', '28b728c7-32c3-4fc8-a88f-362deebc2d81'] },
      { table: 'fhip_import_proposals', userId: u, ids: ['3c0fc5cc-c320-4d6d-aa42-af2e8a5a9351', 'a81a5432-07f1-43d1-a034-16b3dbb5a566'] },
      { table: 'fdh_liability_statements', userId: u, ids: ['920731d8-a9e2-40c7-a13a-a035f74913a9'] },
      { table: 'fdh_financial_accounts', userId: u, ids: ['d83543ee-fffb-4e52-b4cb-ae778b007ec7'] },
      { table: 'liabilities', userId: u, ids: ['05bf0114-77d0-464c-9a15-446b67038666'] },
      { table: 'fdh_statement_uploads', userId: u, ids: ['e0d222cb-710e-40f7-b5d4-60aad132f2d1'] },
    ],
  };
}

/** The consolidator's own live recheck (range A, forecast.tc025, ledger A-consol, 2026-09-27): one applied
 *  card chain the service role cannot delete (verify listed exactly these 6 rows). */
function consolidationRecheck() {
  const u = '60457111-1b20-4d17-aff5-ed5fdf3b8118';
  return {
    label: 'range A (consolidation recheck, forecast.tc025)',
    deletes: [
      { table: 'fhip_import_applications', userId: u, ids: ['d8b39a2c-1034-4d11-9c0e-3ad348b28dc9'] },
      { table: 'fhip_import_proposals', userId: u, ids: ['1c97ca69-9cd4-4169-83b9-3280f628c448'] },
      { table: 'fdh_liability_statements', userId: u, ids: ['7b2036ed-b10b-4388-b9ba-a768d29d748d'] },
      { table: 'fdh_financial_accounts', userId: u, ids: ['27d1527b-1741-4c28-a5e5-1da52e90011a'] },
      { table: 'liabilities', userId: u, ids: ['43fcd5dc-fbd5-4791-b1d7-df75cd94381a'] },
      { table: 'fdh_statement_uploads', userId: u, ids: ['66b3a6eb-b408-4ccd-95ca-a9add56a37bb'] },
    ],
  };
}

export function buildSpec() {
  const read = (rel) => fs.readFileSync(path.join(HERE, rel), 'utf8');
  const cText = read('scaleui/dev_residue_C_liability_retirement.sql');
  const c = rangeC();
  // The hand-mirrored range C must agree with the certifier's own file id-for-id.
  for (const id of [...c.preUpdates.map((x) => x.id), ...c.deletes.flatMap((d) => d.ids)]) {
    if (!cText.includes(id)) throw new Error(`range C mirror: ${id} not in scaleui/dev_residue_C_liability_retirement.sql`);
  }
  return {
    title: 'Canonical upload programme, stage 3 -- COMBINED DEV residue cleanup for the PO (ranges A-D)',
    sections: [
      { label: 'range A (golden pair)', deletes: parseSimpleResidueFile(read('golden_pair/dev_residue_A_liability_chains.sql'), 'A') },
      { label: 'range B (economic oracles)', deletes: parseSimpleResidueFile(read('econ/dev_residue_B_liability_chains.sql'), 'B') },
      c,
      { label: 'range D (security review)', deletes: parseSimpleResidueFile(read('secrev/dev_residue_D_liability_chain.sql'), 'D') },
      consolidationRecheck(),
    ],
  };
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const out = path.join(HERE, 'dev_residue_ALL_for_PO.sql');
  const sql = renderResidueSql(buildSpec());
  if (process.argv.includes('--check')) {
    const cur = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : '';
    if (cur !== sql) { console.error('dev_residue_ALL_for_PO.sql is stale: re-run the builder'); process.exit(1); }
    console.log('dev_residue_ALL_for_PO.sql is current');
  } else {
    fs.writeFileSync(out, sql, 'utf8'); // UTF-8 without BOM (the Supabase SQL editor rejects a BOM)
    console.log(`wrote ${out}`);
  }
}
