/**
 * Builds docs/financial-data-hub/po_run/DEV_apply_0218.sql: migration 0218 VERBATIM, wrapped in ONE
 * transaction behind the same DEV guard as the residue file (ii_nav_retention_policy must have a 'dev'
 * row and no 'production' row) plus a prerequisite check (0214 applied), followed by a PostgREST schema
 * reload. Written by Node (UTF-8, no BOM: the Supabase SQL editor rejects a BOM).
 *
 *   node scripts/canonical_cert/build_dev_apply_0218.mjs           -> writes the file
 *   node scripts/canonical_cert/build_dev_apply_0218.mjs --check   -> exit 1 if stale
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..', '..');
export const MIGRATION = path.join(ROOT, 'supabase', 'migrations', '0218_canonical_security_review_hardening.sql');
export const OUT = path.join(ROOT, 'docs', 'financial-data-hub', 'po_run', 'DEV_apply_0218.sql');

export const BEGIN_MARK = '-- ======== BEGIN 0218_canonical_security_review_hardening.sql (verbatim) ========';
export const END_MARK = '-- ======== END 0218_canonical_security_review_hardening.sql ========';

export function renderDevApply0218(migrationSql) {
  const head = [
    '-- DEV ONLY (vqycarelcoijzwlpkpcz): apply migration 0218 (canonical security-review hardening).',
    '-- GENERATED by scripts/canonical_cert/build_dev_apply_0218.mjs -- do not hand-edit.',
    '--',
    '-- Paste the WHOLE file into the DEV Supabase SQL editor and run it once. It runs in ONE transaction and',
    '-- REFUSES (raises, nothing changes) unless ii_nav_retention_policy has an environment=\'dev\' row and NO',
    '-- environment=\'production\' row, and 0214 is already applied (fdh15_apply_asset_proposal exists).',
    '-- 0218 itself also refuses while any cross-tenant split line exists (its PART B pre-check; the remedy',
    '-- query is in the migration header). It is idempotent (create or replace / drop trigger if exists / revoke).',
    '-- Expected result: success, no rows. Then PostgREST reloads its schema cache (last line).',
    '--',
    '-- PRODUCTION: do NOT use this file. Production applies 0207-0214 then 0218 in one sitting, immediately',
    '-- before the code deploy -- see docs/financial-data-hub/PRODUCTION_IMPORT_PROPAGATION_CERTIFICATION.md.',
    '',
    'begin;',
    '',
    'do $$',
    'begin',
    "  if not exists (select 1 from ii_nav_retention_policy where environment = 'dev') then",
    "    raise exception 'REFUSED: no dev row in ii_nav_retention_policy -- this is not the DEV database';",
    '  end if;',
    "  if exists (select 1 from ii_nav_retention_policy where environment = 'production') then",
    "    raise exception 'REFUSED: ii_nav_retention_policy has a production row -- this is PRODUCTION';",
    '  end if;',
    "  if to_regprocedure('public.fdh15_apply_asset_proposal(uuid, text, text[])') is null then",
    "    raise exception 'REFUSED: 0214 is not applied (fdh15_apply_asset_proposal missing) -- apply 0207-0214 first';",
    '  end if;',
    'end $$;',
    '',
    BEGIN_MARK,
  ].join('\n');
  const tail = [END_MARK, '', 'commit;', '', "notify pgrst, 'reload schema';", ''].join('\n');
  return `${head}\n${migrationSql.replace(/^﻿/, '').replace(/\s+$/, '')}\n${tail}`;
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const sql = renderDevApply0218(fs.readFileSync(MIGRATION, 'utf8'));
  if (process.argv.includes('--check')) {
    const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
    if (cur !== sql) { console.error('DEV_apply_0218.sql is stale: re-run the builder'); process.exit(1); }
    console.log('DEV_apply_0218.sql is current');
  } else {
    fs.mkdirSync(path.dirname(OUT), { recursive: true });
    fs.writeFileSync(OUT, sql, 'utf8');
    console.log(`wrote ${OUT}`);
  }
}
