-- =============================================================================
-- Financial Data Hub (FDH) — FDH-2 Migration E (0054): institution + payment-rail master-data seed
-- =============================================================================
-- GENERATED FILE. Produced deterministically by
-- scripts/fdh2_generate_master_data_migration.mjs from the version-controlled
-- source data under data/financial-data-hub/. Do not hand-edit this file —
-- edit the source data module and regenerate. Every INSERT is
-- `ON CONFLICT ... DO NOTHING`, so re-applying this migration (or the full
-- chain) twice produces the same row count with zero duplicates.
-- --- fdh_financial_institutions (AU) --------------------------------------
insert into fdh_financial_institutions (country_code, institution_code, institution_name, institution_type, legal_name, parent_group, website_domain, coverage_status, source_key, source_checked_at) values
  ('AU', $lit$cba$lit$, $lit$Commonwealth Bank of Australia$lit$, $lit$bank$lit$, $lit$Commonwealth Bank of Australia$lit$, null, $lit$commbank.com.au$lit$, $lit$master_only$lit$, $lit$au_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('AU', $lit$westpac$lit$, $lit$Westpac Banking Corporation$lit$, $lit$bank$lit$, $lit$Westpac Banking Corporation$lit$, null, $lit$westpac.com.au$lit$, $lit$master_only$lit$, $lit$au_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('AU', $lit$nab$lit$, $lit$National Australia Bank$lit$, $lit$bank$lit$, $lit$National Australia Bank Limited$lit$, null, $lit$nab.com.au$lit$, $lit$master_only$lit$, $lit$au_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('AU', $lit$anz$lit$, $lit$ANZ$lit$, $lit$bank$lit$, $lit$Australia and New Zealand Banking Group Limited$lit$, null, $lit$anz.com.au$lit$, $lit$master_only$lit$, $lit$au_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('AU', $lit$macquarie_bank$lit$, $lit$Macquarie Bank$lit$, $lit$bank$lit$, $lit$Macquarie Bank Limited$lit$, $lit$Macquarie Group Limited$lit$, $lit$macquarie.com.au$lit$, $lit$master_only$lit$, $lit$au_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('AU', $lit$ing_australia$lit$, $lit$ING (Australia)$lit$, $lit$bank$lit$, $lit$ING Bank (Australia) Limited$lit$, $lit$ING Groep N.V.$lit$, $lit$ing.com.au$lit$, $lit$master_only$lit$, $lit$au_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('AU', $lit$bendigo_adelaide_bank$lit$, $lit$Bendigo and Adelaide Bank$lit$, $lit$bank$lit$, $lit$Bendigo and Adelaide Bank Limited$lit$, null, $lit$bendigobank.com.au$lit$, $lit$master_only$lit$, $lit$au_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('AU', $lit$bank_australia$lit$, $lit$Bank Australia$lit$, $lit$bank$lit$, $lit$Bank Australia Limited$lit$, null, $lit$bankaust.com.au$lit$, $lit$master_only$lit$, $lit$au_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('AU', $lit$amp_bank$lit$, $lit$AMP Bank$lit$, $lit$bank$lit$, $lit$AMP Bank Limited$lit$, $lit$AMP Limited$lit$, $lit$amp.com.au$lit$, $lit$master_only$lit$, $lit$au_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('AU', $lit$boq$lit$, $lit$Bank of Queensland$lit$, $lit$bank$lit$, $lit$Bank of Queensland Limited$lit$, null, $lit$boq.com.au$lit$, $lit$master_only$lit$, $lit$au_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('AU', $lit$me_bank$lit$, $lit$ME Bank$lit$, $lit$bank$lit$, $lit$Members Equity Bank Pty Limited$lit$, $lit$Bank of Queensland Group$lit$, $lit$mebank.com.au$lit$, $lit$master_only$lit$, $lit$au_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('AU', $lit$ubank$lit$, $lit$ubank$lit$, $lit$bank$lit$, $lit$ubank Limited$lit$, $lit$National Australia Bank$lit$, $lit$ubank.com.au$lit$, $lit$master_only$lit$, $lit$au_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('AU', $lit$great_southern_bank$lit$, $lit$Great Southern Bank$lit$, $lit$bank$lit$, $lit$Great Southern Bank (a trading name of Credit Union Australia Limited)$lit$, null, $lit$greatsouthernbank.com.au$lit$, $lit$master_only$lit$, $lit$au_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('AU', $lit$hsbc_australia$lit$, $lit$HSBC Bank Australia$lit$, $lit$bank$lit$, $lit$HSBC Bank Australia Limited$lit$, $lit$HSBC Holdings plc$lit$, $lit$hsbc.com.au$lit$, $lit$master_only$lit$, $lit$au_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('AU', $lit$suncorp_bank$lit$, $lit$Suncorp Bank$lit$, $lit$bank$lit$, $lit$Suncorp-Metway Limited$lit$, $lit$ANZ Group Holdings Limited$lit$, $lit$suncorp.com.au$lit$, $lit$master_only$lit$, $lit$au_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('AU', $lit$commsec$lit$, $lit$CommSec$lit$, $lit$broker$lit$, $lit$Commonwealth Securities Limited$lit$, $lit$Commonwealth Bank of Australia$lit$, $lit$commsec.com.au$lit$, $lit$master_only$lit$, $lit$au_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('AU', $lit$selfwealth$lit$, $lit$SelfWealth$lit$, $lit$broker$lit$, $lit$SelfWealth Limited$lit$, null, $lit$selfwealth.com.au$lit$, $lit$master_only$lit$, $lit$au_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('AU', $lit$australiansuper$lit$, $lit$AustralianSuper$lit$, $lit$super_fund$lit$, $lit$AustralianSuper$lit$, null, $lit$australiansuper.com$lit$, $lit$master_only$lit$, $lit$au_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('AU', $lit$australian_retirement_trust$lit$, $lit$Australian Retirement Trust$lit$, $lit$super_fund$lit$, $lit$Australian Retirement Trust$lit$, null, $lit$art.com.au$lit$, $lit$master_only$lit$, $lit$au_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('AU', $lit$hostplus$lit$, $lit$Hostplus$lit$, $lit$super_fund$lit$, $lit$Hostplus$lit$, null, $lit$hostplus.com.au$lit$, $lit$master_only$lit$, $lit$au_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('AU', $lit$services_australia$lit$, $lit$Services Australia$lit$, $lit$government_payment_source$lit$, $lit$Services Australia (Commonwealth of Australia)$lit$, null, $lit$servicesaustralia.gov.au$lit$, $lit$master_only$lit$, $lit$au_government_payment_public_info$lit$, $lit$2026-08-21$lit$),
  ('AU', $lit$ato$lit$, $lit$Australian Taxation Office$lit$, $lit$government_payment_source$lit$, $lit$Australian Taxation Office (Commonwealth of Australia)$lit$, null, $lit$ato.gov.au$lit$, $lit$master_only$lit$, $lit$au_government_payment_public_info$lit$, $lit$2026-08-21$lit$)
on conflict (country_code, institution_code) do nothing;

-- --- fdh_financial_institutions (IN) --------------------------------------
insert into fdh_financial_institutions (country_code, institution_code, institution_name, institution_type, legal_name, parent_group, website_domain, coverage_status, source_key, source_checked_at) values
  ('IN', $lit$sbi$lit$, $lit$State Bank of India$lit$, $lit$bank$lit$, $lit$State Bank of India$lit$, null, $lit$sbi.co.in$lit$, $lit$master_only$lit$, $lit$in_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('IN', $lit$hdfc_bank$lit$, $lit$HDFC Bank$lit$, $lit$bank$lit$, $lit$HDFC Bank Limited$lit$, null, $lit$hdfcbank.com$lit$, $lit$master_only$lit$, $lit$in_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('IN', $lit$icici_bank$lit$, $lit$ICICI Bank$lit$, $lit$bank$lit$, $lit$ICICI Bank Limited$lit$, null, $lit$icicibank.com$lit$, $lit$master_only$lit$, $lit$in_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('IN', $lit$axis_bank$lit$, $lit$Axis Bank$lit$, $lit$bank$lit$, $lit$Axis Bank Limited$lit$, null, $lit$axisbank.com$lit$, $lit$master_only$lit$, $lit$in_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('IN', $lit$kotak_mahindra_bank$lit$, $lit$Kotak Mahindra Bank$lit$, $lit$bank$lit$, $lit$Kotak Mahindra Bank Limited$lit$, null, $lit$kotak.com$lit$, $lit$master_only$lit$, $lit$in_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('IN', $lit$idfc_first_bank$lit$, $lit$IDFC FIRST Bank$lit$, $lit$bank$lit$, $lit$IDFC FIRST Bank Limited$lit$, null, $lit$idfcfirstbank.com$lit$, $lit$master_only$lit$, $lit$in_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('IN', $lit$bank_of_baroda$lit$, $lit$Bank of Baroda$lit$, $lit$bank$lit$, $lit$Bank of Baroda$lit$, null, $lit$bankofbaroda.in$lit$, $lit$master_only$lit$, $lit$in_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('IN', $lit$pnb$lit$, $lit$Punjab National Bank$lit$, $lit$bank$lit$, $lit$Punjab National Bank$lit$, null, $lit$pnbindia.in$lit$, $lit$master_only$lit$, $lit$in_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('IN', $lit$canara_bank$lit$, $lit$Canara Bank$lit$, $lit$bank$lit$, $lit$Canara Bank$lit$, null, $lit$canarabank.com$lit$, $lit$master_only$lit$, $lit$in_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('IN', $lit$union_bank_of_india$lit$, $lit$Union Bank of India$lit$, $lit$bank$lit$, $lit$Union Bank of India$lit$, null, $lit$unionbankofindia.co.in$lit$, $lit$master_only$lit$, $lit$in_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('IN', $lit$indian_bank$lit$, $lit$Indian Bank$lit$, $lit$bank$lit$, $lit$Indian Bank$lit$, null, $lit$indianbank.in$lit$, $lit$master_only$lit$, $lit$in_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('IN', $lit$indusind_bank$lit$, $lit$IndusInd Bank$lit$, $lit$bank$lit$, $lit$IndusInd Bank Limited$lit$, null, $lit$indusind.com$lit$, $lit$master_only$lit$, $lit$in_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('IN', $lit$federal_bank$lit$, $lit$Federal Bank$lit$, $lit$bank$lit$, $lit$The Federal Bank Limited$lit$, null, $lit$federalbank.co.in$lit$, $lit$master_only$lit$, $lit$in_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('IN', $lit$yes_bank$lit$, $lit$Yes Bank$lit$, $lit$bank$lit$, $lit$Yes Bank Limited$lit$, null, $lit$yesbank.in$lit$, $lit$master_only$lit$, $lit$in_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('IN', $lit$au_small_finance_bank$lit$, $lit$AU Small Finance Bank$lit$, $lit$bank$lit$, $lit$AU Small Finance Bank Limited$lit$, null, $lit$aubank.in$lit$, $lit$master_only$lit$, $lit$in_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('IN', $lit$rbi$lit$, $lit$Reserve Bank of India$lit$, $lit$government_payment_source$lit$, $lit$Reserve Bank of India$lit$, null, $lit$rbi.org.in$lit$, $lit$master_only$lit$, $lit$in_government_payment_public_info$lit$, $lit$2026-08-21$lit$),
  ('IN', $lit$zerodha$lit$, $lit$Zerodha$lit$, $lit$broker$lit$, $lit$Zerodha Broking Limited$lit$, null, $lit$zerodha.com$lit$, $lit$master_only$lit$, $lit$in_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('IN', $lit$groww$lit$, $lit$Groww$lit$, $lit$broker$lit$, $lit$Billionbrains Garage Ventures Private Limited$lit$, null, $lit$groww.in$lit$, $lit$master_only$lit$, $lit$in_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('IN', $lit$nsdl$lit$, $lit$NSDL$lit$, $lit$depository$lit$, $lit$National Securities Depository Limited$lit$, null, $lit$nsdl.co.in$lit$, $lit$master_only$lit$, $lit$in_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('IN', $lit$cdsl$lit$, $lit$CDSL$lit$, $lit$depository$lit$, $lit$Central Depository Services (India) Limited$lit$, null, $lit$cdslindia.com$lit$, $lit$master_only$lit$, $lit$in_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('IN', $lit$cams$lit$, $lit$CAMS$lit$, $lit$mutual_fund_platform$lit$, $lit$Computer Age Management Services Limited$lit$, null, $lit$camsonline.com$lit$, $lit$master_only$lit$, $lit$in_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('IN', $lit$kfintech$lit$, $lit$KFintech$lit$, $lit$mutual_fund_platform$lit$, $lit$KFin Technologies Limited$lit$, null, $lit$kfintech.com$lit$, $lit$master_only$lit$, $lit$in_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('IN', $lit$epfo$lit$, $lit$EPFO$lit$, $lit$retirement_provider$lit$, $lit$Employees' Provident Fund Organisation$lit$, null, $lit$epfindia.gov.in$lit$, $lit$master_only$lit$, $lit$in_government_payment_public_info$lit$, $lit$2026-08-21$lit$),
  ('IN', $lit$protean_enps$lit$, $lit$Protean eGov Technologies (NPS)$lit$, $lit$retirement_provider$lit$, $lit$Protean eGov Technologies Limited$lit$, null, $lit$npscra.nsdl.co.in$lit$, $lit$master_only$lit$, $lit$in_institution_public_websites$lit$, $lit$2026-08-21$lit$),
  ('IN', $lit$income_tax_department_india$lit$, $lit$Income Tax Department (India)$lit$, $lit$government_payment_source$lit$, $lit$Income Tax Department, Government of India$lit$, null, $lit$incometax.gov.in$lit$, $lit$master_only$lit$, $lit$in_government_payment_public_info$lit$, $lit$2026-08-21$lit$)
on conflict (country_code, institution_code) do nothing;

-- --- fdh_institution_capabilities ---------------------------------------------
insert into fdh_institution_capabilities (institution_id, capability_type) values
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'macquarie_bank'), $lit$broker$lit$),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'macquarie_bank'), $lit$investment_platform$lit$),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'groww'), $lit$mutual_fund_platform$lit$)
on conflict (institution_id, capability_type) do nothing;

-- --- fdh_institution_aliases -------------------------------------------------
insert into fdh_institution_aliases (institution_id, alias, alias_normalized, source, confidence, verified) values
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'cba'), $lit$CBA$lit$, $lit$CBA$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'cba'), $lit$COMMBANK$lit$, $lit$COMMBANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'cba'), $lit$COMMONWEALTH BANK$lit$, $lit$COMMONWEALTH BANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'cba'), $lit$COMMONWEALTH BANK OF AUSTRALIA$lit$, $lit$COMMONWEALTH BANK OF AUSTRALIA$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'westpac'), $lit$WESTPAC$lit$, $lit$WESTPAC$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'westpac'), $lit$WBC$lit$, $lit$WBC$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'nab'), $lit$NAB$lit$, $lit$NAB$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'nab'), $lit$NATIONAL AUSTRALIA BANK$lit$, $lit$NATIONAL AUSTRALIA BANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'anz'), $lit$ANZ$lit$, $lit$ANZ$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'anz'), $lit$ANZ BANK$lit$, $lit$ANZ BANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'anz'), $lit$AUSTRALIA AND NEW ZEALAND BANKING GROUP$lit$, $lit$AUSTRALIA AND NEW ZEALAND BANKING GROUP$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'macquarie_bank'), $lit$MACQUARIE$lit$, $lit$MACQUARIE$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'macquarie_bank'), $lit$MACQUARIE BANK$lit$, $lit$MACQUARIE BANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'ing_australia'), $lit$ING$lit$, $lit$ING$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'ing_australia'), $lit$ING DIRECT$lit$, $lit$ING DIRECT$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'bendigo_adelaide_bank'), $lit$BENDIGO BANK$lit$, $lit$BENDIGO BANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'bendigo_adelaide_bank'), $lit$ADELAIDE BANK$lit$, $lit$ADELAIDE BANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'bendigo_adelaide_bank'), $lit$BENDIGO AND ADELAIDE BANK$lit$, $lit$BENDIGO AND ADELAIDE BANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'bank_australia'), $lit$BANK AUSTRALIA$lit$, $lit$BANK AUSTRALIA$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'amp_bank'), $lit$AMP BANK$lit$, $lit$AMP BANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'amp_bank'), $lit$AMP$lit$, $lit$AMP$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'boq'), $lit$BOQ$lit$, $lit$BOQ$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'boq'), $lit$BANK OF QUEENSLAND$lit$, $lit$BANK OF QUEENSLAND$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'me_bank'), $lit$ME BANK$lit$, $lit$ME BANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'me_bank'), $lit$MEMBERS EQUITY BANK$lit$, $lit$MEMBERS EQUITY BANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'me_bank'), $lit$ME$lit$, $lit$ME$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'ubank'), $lit$UBANK$lit$, $lit$UBANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'great_southern_bank'), $lit$GREAT SOUTHERN BANK$lit$, $lit$GREAT SOUTHERN BANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'great_southern_bank'), $lit$CUA$lit$, $lit$CUA$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'great_southern_bank'), $lit$CREDIT UNION AUSTRALIA$lit$, $lit$CREDIT UNION AUSTRALIA$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'hsbc_australia'), $lit$HSBC$lit$, $lit$HSBC$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'hsbc_australia'), $lit$HSBC AUSTRALIA$lit$, $lit$HSBC AUSTRALIA$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'suncorp_bank'), $lit$SUNCORP$lit$, $lit$SUNCORP$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'suncorp_bank'), $lit$SUNCORP BANK$lit$, $lit$SUNCORP BANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'suncorp_bank'), $lit$SUNCORP-METWAY$lit$, $lit$SUNCORP-METWAY$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'commsec'), $lit$COMMSEC$lit$, $lit$COMMSEC$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'commsec'), $lit$COMMONWEALTH SECURITIES$lit$, $lit$COMMONWEALTH SECURITIES$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'selfwealth'), $lit$SELFWEALTH$lit$, $lit$SELFWEALTH$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'australiansuper'), $lit$AUSTRALIANSUPER$lit$, $lit$AUSTRALIANSUPER$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'australian_retirement_trust'), $lit$AUSTRALIAN RETIREMENT TRUST$lit$, $lit$AUSTRALIAN RETIREMENT TRUST$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'australian_retirement_trust'), $lit$ART$lit$, $lit$ART$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'australian_retirement_trust'), $lit$SUNSUPER$lit$, $lit$SUNSUPER$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'australian_retirement_trust'), $lit$QSUPER$lit$, $lit$QSUPER$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'hostplus'), $lit$HOSTPLUS$lit$, $lit$HOSTPLUS$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'services_australia'), $lit$SERVICES AUSTRALIA$lit$, $lit$SERVICES AUSTRALIA$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'services_australia'), $lit$CENTRELINK$lit$, $lit$CENTRELINK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'ato'), $lit$ATO$lit$, $lit$ATO$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'AU' and institution_code = 'ato'), $lit$AUSTRALIAN TAXATION OFFICE$lit$, $lit$AUSTRALIAN TAXATION OFFICE$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'sbi'), $lit$SBI$lit$, $lit$SBI$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'sbi'), $lit$STATE BANK OF INDIA$lit$, $lit$STATE BANK OF INDIA$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'hdfc_bank'), $lit$HDFC$lit$, $lit$HDFC$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'hdfc_bank'), $lit$HDFC BANK$lit$, $lit$HDFC BANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'icici_bank'), $lit$ICICI$lit$, $lit$ICICI$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'icici_bank'), $lit$ICICI BANK$lit$, $lit$ICICI BANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'axis_bank'), $lit$AXIS$lit$, $lit$AXIS$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'axis_bank'), $lit$AXIS BANK$lit$, $lit$AXIS BANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'kotak_mahindra_bank'), $lit$KOTAK$lit$, $lit$KOTAK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'kotak_mahindra_bank'), $lit$KOTAK MAHINDRA BANK$lit$, $lit$KOTAK MAHINDRA BANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'kotak_mahindra_bank'), $lit$KOTAK BANK$lit$, $lit$KOTAK BANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'idfc_first_bank'), $lit$IDFC FIRST$lit$, $lit$IDFC FIRST$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'idfc_first_bank'), $lit$IDFC FIRST BANK$lit$, $lit$IDFC FIRST BANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'idfc_first_bank'), $lit$IDFC BANK$lit$, $lit$IDFC BANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'bank_of_baroda'), $lit$BOB$lit$, $lit$BOB$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'bank_of_baroda'), $lit$BANK OF BARODA$lit$, $lit$BANK OF BARODA$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'pnb'), $lit$PNB$lit$, $lit$PNB$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'pnb'), $lit$PUNJAB NATIONAL BANK$lit$, $lit$PUNJAB NATIONAL BANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'canara_bank'), $lit$CANARA$lit$, $lit$CANARA$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'canara_bank'), $lit$CANARA BANK$lit$, $lit$CANARA BANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'union_bank_of_india'), $lit$UNION BANK$lit$, $lit$UNION BANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'union_bank_of_india'), $lit$UNION BANK OF INDIA$lit$, $lit$UNION BANK OF INDIA$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'indian_bank'), $lit$INDIAN BANK$lit$, $lit$INDIAN BANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'indusind_bank'), $lit$INDUSIND$lit$, $lit$INDUSIND$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'indusind_bank'), $lit$INDUSIND BANK$lit$, $lit$INDUSIND BANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'federal_bank'), $lit$FEDERAL BANK$lit$, $lit$FEDERAL BANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'yes_bank'), $lit$YES BANK$lit$, $lit$YES BANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'au_small_finance_bank'), $lit$AU SMALL FINANCE BANK$lit$, $lit$AU SMALL FINANCE BANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'au_small_finance_bank'), $lit$AU BANK$lit$, $lit$AU BANK$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'rbi'), $lit$RBI$lit$, $lit$RBI$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'rbi'), $lit$RESERVE BANK OF INDIA$lit$, $lit$RESERVE BANK OF INDIA$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'zerodha'), $lit$ZERODHA$lit$, $lit$ZERODHA$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'groww'), $lit$GROWW$lit$, $lit$GROWW$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'nsdl'), $lit$NSDL$lit$, $lit$NSDL$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'nsdl'), $lit$NATIONAL SECURITIES DEPOSITORY$lit$, $lit$NATIONAL SECURITIES DEPOSITORY$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'cdsl'), $lit$CDSL$lit$, $lit$CDSL$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'cdsl'), $lit$CENTRAL DEPOSITORY SERVICES$lit$, $lit$CENTRAL DEPOSITORY SERVICES$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'cams'), $lit$CAMS$lit$, $lit$CAMS$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'kfintech'), $lit$KFINTECH$lit$, $lit$KFINTECH$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'kfintech'), $lit$KARVY$lit$, $lit$KARVY$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'kfintech'), $lit$KFIN$lit$, $lit$KFIN$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'epfo'), $lit$EPFO$lit$, $lit$EPFO$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'epfo'), $lit$EMPLOYEES' PROVIDENT FUND ORGANISATION$lit$, $lit$EMPLOYEES' PROVIDENT FUND ORGANISATION$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'epfo'), $lit$EPF$lit$, $lit$EPF$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'protean_enps'), $lit$PROTEAN$lit$, $lit$PROTEAN$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'protean_enps'), $lit$NSDL E-GOV$lit$, $lit$NSDL E-GOV$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'protean_enps'), $lit$NSDL E-GOVERNANCE$lit$, $lit$NSDL E-GOVERNANCE$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'protean_enps'), $lit$NPS TRUST$lit$, $lit$NPS TRUST$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'income_tax_department_india'), $lit$INCOME TAX DEPARTMENT$lit$, $lit$INCOME TAX DEPARTMENT$lit$, 'admin_curated', 0.95, true),
  ((select id from fdh_financial_institutions where country_code = 'IN' and institution_code = 'income_tax_department_india'), $lit$ITD$lit$, $lit$ITD$lit$, 'admin_curated', 0.95, true)
on conflict (institution_id, alias_normalized) do nothing;

-- --- fdh_payment_rail_master --------------------------------------------------
insert into fdh_payment_rail_master (rail_key, display_name, country_code, rail_category, description, active) values
  ($lit$au_eftpos$lit$, $lit$EFTPOS$lit$, $lit$AU$lit$, $lit$card$lit$, $lit$Electronic Funds Transfer at Point Of Sale — Australia's domestic debit-card payment network.$lit$, true),
  ($lit$au_bpay$lit$, $lit$BPAY$lit$, $lit$AU$lit$, $lit$bill_payment$lit$, $lit$Australian bill-payment scheme used to pay a biller via a Biller Code and Customer Reference Number.$lit$, true),
  ($lit$au_osko$lit$, $lit$Osko$lit$, $lit$AU$lit$, $lit$p2p_transfer$lit$, $lit$Near-real-time payment service built on Australia's New Payments Platform (NPP), commonly used for fast account-to-account transfers.$lit$, true),
  ($lit$au_payid$lit$, $lit$PayID$lit$, $lit$AU$lit$, $lit$p2p_transfer$lit$, $lit$An NPP addressing service allowing a payment to be sent to a registered identifier (email/phone) instead of a BSB and account number.$lit$, true),
  ($lit$au_direct_debit$lit$, $lit$Direct Debit$lit$, $lit$AU$lit$, $lit$direct_debit$lit$, $lit$A pre-authorised debit initiated by a biller/merchant against the account, commonly used for recurring bills and loan repayments.$lit$, true),
  ($lit$au_direct_credit$lit$, $lit$Direct Credit$lit$, $lit$AU$lit$, $lit$direct_credit$lit$, $lit$A credit deposited directly into the account, commonly used for salary/payroll and government payments.$lit$, true),
  ($lit$au_atm$lit$, $lit$ATM$lit$, $lit$AU$lit$, $lit$atm$lit$, $lit$Automated teller machine cash withdrawal or balance transaction.$lit$, true),
  ($lit$au_card_purchase$lit$, $lit$Card Purchase$lit$, $lit$AU$lit$, $lit$card$lit$, $lit$A card-present or card-not-present purchase transaction (debit or credit card).$lit$, true),
  ($lit$in_upi$lit$, $lit$UPI$lit$, $lit$IN$lit$, $lit$p2p_transfer$lit$, $lit$Unified Payments Interface — India's real-time payment system (NPCI) for account-to-account and merchant payments via a UPI ID/handle.$lit$, true),
  ($lit$in_imps$lit$, $lit$IMPS$lit$, $lit$IN$lit$, $lit$p2p_transfer$lit$, $lit$Immediate Payment Service — a 24x7 interbank electronic fund-transfer service in India.$lit$, true),
  ($lit$in_neft$lit$, $lit$NEFT$lit$, $lit$IN$lit$, $lit$direct_credit$lit$, $lit$National Electronic Funds Transfer — a batched interbank electronic fund-transfer system in India.$lit$, true),
  ($lit$in_rtgs$lit$, $lit$RTGS$lit$, $lit$IN$lit$, $lit$wire$lit$, $lit$Real Time Gross Settlement — India's real-time, high-value interbank funds-transfer system.$lit$, true),
  ($lit$in_nach$lit$, $lit$NACH$lit$, $lit$IN$lit$, $lit$direct_debit$lit$, $lit$National Automated Clearing House — used for bulk/recurring debits and credits in India (e.g. EMI collection, salary disbursement).$lit$, true),
  ($lit$in_ecs$lit$, $lit$ECS$lit$, $lit$IN$lit$, $lit$direct_debit$lit$, $lit$Electronic Clearing Service — an older bulk payment mechanism in India, largely superseded by NACH.$lit$, true),
  ($lit$in_atm$lit$, $lit$ATM$lit$, $lit$IN$lit$, $lit$atm$lit$, $lit$Automated teller machine cash withdrawal or balance transaction.$lit$, true),
  ($lit$in_pos_card$lit$, $lit$POS / Card$lit$, $lit$IN$lit$, $lit$card$lit$, $lit$A card-present or card-not-present purchase transaction (debit or credit card) at point of sale.$lit$, true),
  ($lit$global_wire$lit$, $lit$Wire Transfer$lit$, null, $lit$wire$lit$, $lit$A cross-border or high-value bank wire transfer (e.g. SWIFT).$lit$, true),
  ($lit$global_transfer$lit$, $lit$Bank Transfer (General)$lit$, null, $lit$p2p_transfer$lit$, $lit$A generic bank-to-bank transfer whose specific local rail could not be determined from the narrative alone.$lit$, true),
  ($lit$global_cash$lit$, $lit$Cash$lit$, null, $lit$cash$lit$, $lit$A cash transaction with no electronic payment rail.$lit$, true),
  ($lit$global_other$lit$, $lit$Other$lit$, null, $lit$other$lit$, $lit$A payment mechanism that does not fit any other defined rail.$lit$, true)
on conflict (rail_key) do nothing;

-- =============================================================================
