-- =============================================================================
-- Financial Data Hub (FDH) — FDH-2 Migration G (0056): classification rule seed library
-- =============================================================================
-- GENERATED FILE. Produced deterministically by
-- scripts/fdh2_generate_master_data_migration.mjs from the version-controlled
-- source data under data/financial-data-hub/. Do not hand-edit this file —
-- edit the source data module and regenerate. Every INSERT is
-- `ON CONFLICT ... DO NOTHING`, so re-applying this migration (or the full
-- chain) twice produces the same row count with zero duplicates.
-- --- fdh_classification_rules ---------------------------------------------------
insert into fdh_classification_rules (rule_key, rule_type, country_applicability, match_definition, action_definition, priority, status, active, version) values
  ($lit$income_salary_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["SALARY"],"excluded_terms_normalised":["SALARY SACRIFICE","SALARY PACKAGING"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'income', 'category_id', ((select id from fdh_categories where category_key = 'income'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'income') and subcategory_key = 'salary_wages'))::text), 220, 'approved', true, 1),
  ($lit$income_wages_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["WAGES"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'income', 'category_id', ((select id from fdh_categories where category_key = 'income'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'income') and subcategory_key = 'salary_wages'))::text), 220, 'approved', true, 1),
  ($lit$income_payroll_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["PAYROLL"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'income', 'category_id', ((select id from fdh_categories where category_key = 'income'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'income') and subcategory_key = 'salary_wages'))::text), 220, 'approved', true, 1),
  ($lit$income_bonus_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["BONUS"],"excluded_terms_normalised":["BONUS POINTS","BONUS REWARD"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'income', 'category_id', ((select id from fdh_categories where category_key = 'income'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'income') and subcategory_key = 'bonus_commission'))::text), 230, 'approved', true, 1),
  ($lit$income_commission_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["COMMISSION"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'income', 'category_id', ((select id from fdh_categories where category_key = 'income'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'income') and subcategory_key = 'bonus_commission'))::text), 230, 'approved', true, 1),
  ($lit$income_dividend_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["DIVIDEND"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'income', 'category_id', ((select id from fdh_categories where category_key = 'income'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'income') and subcategory_key = 'dividend_income'))::text), 220, 'approved', true, 1),
  ($lit$income_rental_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["RENTAL INCOME"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'income', 'category_id', ((select id from fdh_categories where category_key = 'income'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'income') and subcategory_key = 'rental_income'))::text), 230, 'approved', true, 1),
  ($lit$income_interest_earned$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["INTEREST"],"excluded_terms_normalised":["INTEREST CHARGED","INTEREST CHARGE","LOAN INTEREST","CARD INTEREST"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'income', 'category_id', ((select id from fdh_categories where category_key = 'income'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'income') and subcategory_key = 'interest_income'))::text), 240, 'approved', true, 1),
  ($lit$gov_au_centrelink_benefit$lit$, $lit$narrative_pattern$lit$, array['AU']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["CENTRELINK"],"excluded_terms_normalised":["REPAYMENT","DEBT RECOVERY"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'income', 'category_id', ((select id from fdh_categories where category_key = 'income'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'income') and subcategory_key = 'government_benefit'))::text), 210, 'approved', true, 1),
  ($lit$gov_au_services_australia_benefit$lit$, $lit$narrative_pattern$lit$, array['AU']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["SERVICES AUSTRALIA"],"excluded_terms_normalised":["REPAYMENT","DEBT RECOVERY"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'income', 'category_id', ((select id from fdh_categories where category_key = 'income'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'income') and subcategory_key = 'government_benefit'))::text), 210, 'approved', true, 1),
  ($lit$gov_au_ato_refund$lit$, $lit$narrative_pattern$lit$, array['AU']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["ATO","REFUND"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'refund', 'category_id', ((select id from fdh_categories where category_key = 'refund_reversal'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'refund_reversal') and subcategory_key = 'tax_refund'))::text), 200, 'approved', true, 1),
  ($lit$gov_au_ato_tax_payment$lit$, $lit$narrative_pattern$lit$, array['AU']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["ATO","PAYMENT"],"excluded_terms_normalised":["REFUND"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'tax', 'category_id', ((select id from fdh_categories where category_key = 'government_tax'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'government_tax') and subcategory_key = 'income_tax_payment'))::text), 210, 'approved', true, 1),
  ($lit$gov_in_epfo_credit$lit$, $lit$narrative_pattern$lit$, array['IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["EPFO"],"excluded_terms_normalised":["CONTRIBUTION"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'income', 'category_id', ((select id from fdh_categories where category_key = 'income'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'income') and subcategory_key = 'government_benefit'))::text), 220, 'approved', true, 1),
  ($lit$gov_in_epf_contribution$lit$, $lit$narrative_pattern$lit$, array['IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["EPF","CONTRIBUTION"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'investment', 'category_id', ((select id from fdh_categories where category_key = 'retirement_contribution'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'retirement_contribution') and subcategory_key = 'epf_contribution'))::text), 210, 'approved', true, 1),
  ($lit$gov_in_income_tax_refund$lit$, $lit$narrative_pattern$lit$, array['IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["INCOME TAX","REFUND"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'refund', 'category_id', ((select id from fdh_categories where category_key = 'refund_reversal'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'refund_reversal') and subcategory_key = 'tax_refund'))::text), 200, 'approved', true, 1),
  ($lit$gov_in_nps_contribution$lit$, $lit$narrative_pattern$lit$, array['IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["NPS","CONTRIBUTION"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'investment', 'category_id', ((select id from fdh_categories where category_key = 'retirement_contribution'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'retirement_contribution') and subcategory_key = 'nps_contribution'))::text), 210, 'approved', true, 1),
  ($lit$transfer_own_account_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["OWN ACCOUNT TRANSFER"]}$json$::jsonb, $json${"action_kind":"flag_candidate","candidate_type":"transfer_candidate"}$json$::jsonb, 260, 'approved', true, 1),
  ($lit$transfer_internal_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["INTERNAL TRANSFER"]}$json$::jsonb, $json${"action_kind":"flag_candidate","candidate_type":"transfer_candidate"}$json$::jsonb, 260, 'approved', true, 1),
  ($lit$transfer_au_bank_transfer$lit$, $lit$narrative_pattern$lit$, array['AU']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["BANK TRANSFER"]}$json$::jsonb, $json${"action_kind":"flag_candidate","candidate_type":"transfer_candidate"}$json$::jsonb, 270, 'approved', true, 1),
  ($lit$transfer_in_self_transfer$lit$, $lit$narrative_pattern$lit$, array['IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["SELF TRANSFER"]}$json$::jsonb, $json${"action_kind":"flag_candidate","candidate_type":"transfer_candidate"}$json$::jsonb, 260, 'approved', true, 1),
  ($lit$ccpay_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["CREDIT CARD PAYMENT"]}$json$::jsonb, $json${"action_kind":"flag_candidate","candidate_type":"liability_settlement_candidate"}$json$::jsonb, 210, 'approved', true, 1),
  ($lit$ccpay_cc_bill$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["CC BILL PAYMENT"]}$json$::jsonb, $json${"action_kind":"flag_candidate","candidate_type":"liability_settlement_candidate"}$json$::jsonb, 210, 'approved', true, 1),
  ($lit$ccpay_card_payment_received$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["CARD PAYMENT RECEIVED"]}$json$::jsonb, $json${"action_kind":"flag_candidate","candidate_type":"liability_settlement_candidate"}$json$::jsonb, 210, 'approved', true, 1),
  ($lit$ccpay_in_credit_card_bill$lit$, $lit$narrative_pattern$lit$, array['IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["CREDIT CARD BILL"]}$json$::jsonb, $json${"action_kind":"flag_candidate","candidate_type":"liability_settlement_candidate"}$json$::jsonb, 210, 'approved', true, 1),
  ($lit$invtransfer_mutual_fund_purchase$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["MUTUAL FUND"],"excluded_terms_normalised":["REDEMPTION","DIVIDEND"]}$json$::jsonb, $json${"action_kind":"flag_candidate","candidate_type":"investment_funding_candidate"}$json$::jsonb, 260, 'approved', true, 1),
  ($lit$invtransfer_in_sip$lit$, $lit$narrative_pattern$lit$, array['IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["SIP"],"excluded_terms_normalised":["SIP CANCELLED","SIP STOPPED"]}$json$::jsonb, $json${"action_kind":"flag_candidate","candidate_type":"investment_funding_candidate"}$json$::jsonb, 260, 'approved', true, 1),
  ($lit$invtransfer_broker_funding$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["BROKER"],"excluded_terms_normalised":["BROKERAGE FEE","BROKER FEE"]}$json$::jsonb, $json${"action_kind":"flag_candidate","candidate_type":"investment_funding_candidate"}$json$::jsonb, 280, 'approved', true, 1),
  ($lit$fee_account_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["ACCOUNT FEE"],"excluded_terms_normalised":["FEE WAIVED","FEE REVERSED","FEE REFUND"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'fee', 'category_id', ((select id from fdh_categories where category_key = 'financial_fees'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'financial_fees') and subcategory_key = 'bank_account_fee'))::text), 180, 'approved', true, 1),
  ($lit$fee_annual_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["ANNUAL FEE"],"excluded_terms_normalised":["FEE WAIVED","FEE REVERSED","FEE REFUND"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'fee', 'category_id', ((select id from fdh_categories where category_key = 'financial_fees'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'financial_fees') and subcategory_key = 'card_annual_fee'))::text), 180, 'approved', true, 1),
  ($lit$fee_late_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["LATE FEE"],"excluded_terms_normalised":["FEE WAIVED","FEE REVERSED","FEE REFUND"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'fee', 'category_id', ((select id from fdh_categories where category_key = 'financial_fees'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'financial_fees') and subcategory_key = 'late_payment_fee'))::text), 180, 'approved', true, 1),
  ($lit$fee_overdraft_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["OVERDRAFT FEE"],"excluded_terms_normalised":["FEE WAIVED","FEE REVERSED","FEE REFUND"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'fee', 'category_id', ((select id from fdh_categories where category_key = 'financial_fees'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'financial_fees') and subcategory_key = 'overdraft_fee'))::text), 180, 'approved', true, 1),
  ($lit$fee_atm_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["ATM FEE"],"excluded_terms_normalised":["FEE WAIVED","FEE REVERSED","FEE REFUND"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'fee', 'category_id', ((select id from fdh_categories where category_key = 'financial_fees'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'financial_fees') and subcategory_key = 'atm_fee'))::text), 180, 'approved', true, 1),
  ($lit$fee_foreign_transaction_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["FOREIGN TRANSACTION FEE"],"excluded_terms_normalised":["FEE WAIVED","FEE REVERSED","FEE REFUND"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'fee', 'category_id', ((select id from fdh_categories where category_key = 'financial_fees'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'financial_fees') and subcategory_key = 'foreign_transaction_fee'))::text), 180, 'approved', true, 1),
  ($lit$fee_dishonour_au$lit$, $lit$narrative_pattern$lit$, array['AU']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["DISHONOUR FEE"],"excluded_terms_normalised":["FEE WAIVED","FEE REVERSED"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'fee', 'category_id', ((select id from fdh_categories where category_key = 'financial_fees'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'financial_fees') and subcategory_key = 'other_fee'))::text), 180, 'approved', true, 1),
  ($lit$fee_in_penal_charge$lit$, $lit$narrative_pattern$lit$, array['IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["PENAL CHARGE"],"excluded_terms_normalised":["CHARGE WAIVED","CHARGE REVERSED"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'fee', 'category_id', ((select id from fdh_categories where category_key = 'financial_fees'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'financial_fees') and subcategory_key = 'other_fee'))::text), 190, 'approved', true, 1),
  ($lit$interest_charged_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["INTEREST CHARGED"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'debt_interest', 'category_id', ((select id from fdh_categories where category_key = 'loan_interest'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'loan_interest') and subcategory_key = 'other_loan_interest'))::text), 190, 'approved', true, 1),
  ($lit$interest_charge_card$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["INTEREST CHARGE"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'debt_interest', 'category_id', ((select id from fdh_categories where category_key = 'loan_interest'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'loan_interest') and subcategory_key = 'credit_card_interest'))::text), 190, 'approved', true, 1),
  ($lit$interest_home_loan$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["HOME LOAN INTEREST"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'debt_interest', 'category_id', ((select id from fdh_categories where category_key = 'loan_interest'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'loan_interest') and subcategory_key = 'home_loan_interest'))::text), 180, 'approved', true, 1),
  ($lit$interest_personal_loan$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["PERSONAL LOAN INTEREST"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'debt_interest', 'category_id', ((select id from fdh_categories where category_key = 'loan_interest'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'loan_interest') and subcategory_key = 'personal_loan_interest'))::text), 180, 'approved', true, 1),
  ($lit$cash_atm_withdrawal_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["ATM WITHDRAWAL"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'cash_withdrawal', 'category_id', ((select id from fdh_categories where category_key = 'cash_withdrawal'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'cash_withdrawal') and subcategory_key = 'atm_cash_withdrawal'))::text), 190, 'approved', true, 1),
  ($lit$cash_withdrawal_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["CASH WITHDRAWAL"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'cash_withdrawal', 'category_id', ((select id from fdh_categories where category_key = 'cash_withdrawal'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'cash_withdrawal') and subcategory_key = 'atm_cash_withdrawal'))::text), 200, 'approved', true, 1),
  ($lit$cash_branch_withdrawal_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["BRANCH WITHDRAWAL"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'cash_withdrawal', 'category_id', ((select id from fdh_categories where category_key = 'cash_withdrawal'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'cash_withdrawal') and subcategory_key = 'branch_cash_withdrawal'))::text), 190, 'approved', true, 1),
  ($lit$refund_purchase_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["REFUND"],"excluded_terms_normalised":["TAX REFUND","REFUND WAIVED"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'refund', 'category_id', ((select id from fdh_categories where category_key = 'refund_reversal'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'refund_reversal') and subcategory_key = 'purchase_refund'))::text), 210, 'approved', true, 1),
  ($lit$refund_reversal_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["REVERSAL"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'refund', 'category_id', ((select id from fdh_categories where category_key = 'refund_reversal'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'refund_reversal') and subcategory_key = 'transaction_reversal_chargeback'))::text), 210, 'approved', true, 1),
  ($lit$refund_reversed_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["REVERSED"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'refund', 'category_id', ((select id from fdh_categories where category_key = 'refund_reversal'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'refund_reversal') and subcategory_key = 'transaction_reversal_chargeback'))::text), 220, 'approved', true, 1),
  ($lit$refund_chargeback_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["CHARGEBACK"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'refund', 'category_id', ((select id from fdh_categories where category_key = 'refund_reversal'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'refund_reversal') and subcategory_key = 'transaction_reversal_chargeback'))::text), 200, 'approved', true, 1),
  ($lit$rail_au_eftpos$lit$, $lit$payment_rail_narrative$lit$, array['AU']::char(2)[], $json${"match_kind":"payment_rail_narrative","rail_key":"au_eftpos","narrative_terms_normalised":["EFTPOS"]}$json$::jsonb, $json${"action_kind":"annotate_payment_rail","rail_key":"au_eftpos"}$json$::jsonb, 50, 'approved', true, 1),
  ($lit$rail_au_bpay$lit$, $lit$payment_rail_narrative$lit$, array['AU']::char(2)[], $json${"match_kind":"payment_rail_narrative","rail_key":"au_bpay","narrative_terms_normalised":["BPAY"]}$json$::jsonb, $json${"action_kind":"annotate_payment_rail","rail_key":"au_bpay"}$json$::jsonb, 50, 'approved', true, 1),
  ($lit$rail_au_osko$lit$, $lit$payment_rail_narrative$lit$, array['AU']::char(2)[], $json${"match_kind":"payment_rail_narrative","rail_key":"au_osko","narrative_terms_normalised":["OSKO"]}$json$::jsonb, $json${"action_kind":"annotate_payment_rail","rail_key":"au_osko"}$json$::jsonb, 50, 'approved', true, 1),
  ($lit$rail_au_payid$lit$, $lit$payment_rail_narrative$lit$, array['AU']::char(2)[], $json${"match_kind":"payment_rail_narrative","rail_key":"au_payid","narrative_terms_normalised":["PAYID"]}$json$::jsonb, $json${"action_kind":"annotate_payment_rail","rail_key":"au_payid"}$json$::jsonb, 50, 'approved', true, 1),
  ($lit$rail_au_direct_debit$lit$, $lit$payment_rail_narrative$lit$, array['AU']::char(2)[], $json${"match_kind":"payment_rail_narrative","rail_key":"au_direct_debit","narrative_terms_normalised":["DIRECT DEBIT"]}$json$::jsonb, $json${"action_kind":"annotate_payment_rail","rail_key":"au_direct_debit"}$json$::jsonb, 50, 'approved', true, 1),
  ($lit$rail_au_direct_credit$lit$, $lit$payment_rail_narrative$lit$, array['AU']::char(2)[], $json${"match_kind":"payment_rail_narrative","rail_key":"au_direct_credit","narrative_terms_normalised":["DIRECT CREDIT"]}$json$::jsonb, $json${"action_kind":"annotate_payment_rail","rail_key":"au_direct_credit"}$json$::jsonb, 50, 'approved', true, 1),
  ($lit$rail_au_atm$lit$, $lit$payment_rail_narrative$lit$, array['AU']::char(2)[], $json${"match_kind":"payment_rail_narrative","rail_key":"au_atm","narrative_terms_normalised":["ATM"]}$json$::jsonb, $json${"action_kind":"annotate_payment_rail","rail_key":"au_atm"}$json$::jsonb, 50, 'approved', true, 1),
  ($lit$rail_in_upi$lit$, $lit$payment_rail_narrative$lit$, array['IN']::char(2)[], $json${"match_kind":"payment_rail_narrative","rail_key":"in_upi","narrative_terms_normalised":["UPI/","UPI-","UPI "]}$json$::jsonb, $json${"action_kind":"annotate_payment_rail","rail_key":"in_upi"}$json$::jsonb, 50, 'approved', true, 1),
  ($lit$rail_in_imps$lit$, $lit$payment_rail_narrative$lit$, array['IN']::char(2)[], $json${"match_kind":"payment_rail_narrative","rail_key":"in_imps","narrative_terms_normalised":["IMPS"]}$json$::jsonb, $json${"action_kind":"annotate_payment_rail","rail_key":"in_imps"}$json$::jsonb, 50, 'approved', true, 1),
  ($lit$rail_in_neft$lit$, $lit$payment_rail_narrative$lit$, array['IN']::char(2)[], $json${"match_kind":"payment_rail_narrative","rail_key":"in_neft","narrative_terms_normalised":["NEFT"]}$json$::jsonb, $json${"action_kind":"annotate_payment_rail","rail_key":"in_neft"}$json$::jsonb, 50, 'approved', true, 1),
  ($lit$rail_in_rtgs$lit$, $lit$payment_rail_narrative$lit$, array['IN']::char(2)[], $json${"match_kind":"payment_rail_narrative","rail_key":"in_rtgs","narrative_terms_normalised":["RTGS"]}$json$::jsonb, $json${"action_kind":"annotate_payment_rail","rail_key":"in_rtgs"}$json$::jsonb, 50, 'approved', true, 1),
  ($lit$rail_in_nach$lit$, $lit$payment_rail_narrative$lit$, array['IN']::char(2)[], $json${"match_kind":"payment_rail_narrative","rail_key":"in_nach","narrative_terms_normalised":["NACH"]}$json$::jsonb, $json${"action_kind":"annotate_payment_rail","rail_key":"in_nach"}$json$::jsonb, 50, 'approved', true, 1),
  ($lit$rail_in_ecs$lit$, $lit$payment_rail_narrative$lit$, array['IN']::char(2)[], $json${"match_kind":"payment_rail_narrative","rail_key":"in_ecs","narrative_terms_normalised":["ECS"]}$json$::jsonb, $json${"action_kind":"annotate_payment_rail","rail_key":"in_ecs"}$json$::jsonb, 50, 'approved', true, 1),
  ($lit$rail_in_pos_card$lit$, $lit$payment_rail_narrative$lit$, array['IN']::char(2)[], $json${"match_kind":"payment_rail_narrative","rail_key":"in_pos_card","narrative_terms_normalised":["POS "]}$json$::jsonb, $json${"action_kind":"annotate_payment_rail","rail_key":"in_pos_card"}$json$::jsonb, 50, 'approved', true, 1)
on conflict (rule_key) do nothing;

-- =============================================================================
