-- Chunk 3b — retirement_contributions data backfill (item 6, Spec 2 §34-36).
-- Auto-generated by scripts/chunk3bMigrationAudit.mjs's companion
-- generator against real DEV data (vqycarelcoijzwlpkpcz) on 2026-08-21 —
-- NOT hand-transcribed. Every row below is a real existing
-- retirement_accounts row using one of the 6 Class-F contribution
-- catalogue keys, linked to a specific parent retirement account using the
-- best available evidence: same user_id + same currency_code, and exactly
-- ONE candidate parent account existing for that user (a genuine balance-
-- style retirement item — industry_super/retail_super/smsf/etc., not
-- another contribution row). This is a real but comparatively weak
-- evidence bar for a LINK (retirement_accounts carries no institution/
-- account-number field to further disambiguate, unlike the
-- deterministic-duplicate MERGE bar in Spec 2 §54-57, which needs strong
-- multi-factor evidence because a wrong merge would hide real money —
-- linking to a plausible parent account has no such risk: it never changes
-- any total, only which account a contribution's own record display is
-- associated with). Rows with zero or multiple (ambiguous) candidate
-- parent accounts for their user are deliberately EXCLUDED below and
-- listed as a genuine data-quality gap in
-- docs/app-review-2026-08/CHUNK3B_MIGRATION_AUDIT.md — not silently
-- guessed at.
--
-- amount = the source row's current_balance (the only value field the
-- live grid ever exposed for a Class-F row — see dashboard.ts's
-- isRetirementContributionRow() comment for the phantom-balance mechanism
-- this corrects). frequency = the source row's own saved
-- contribution_frequency (real stored data, not assumed — every one of
-- the 45 affected rows in DEV has contribution_frequency = 'monthly').
-- contributor = 'spouse' only for spouse_contribution rows, 'self'
-- otherwise, per Chunk 3a's "who contributes to whose account" model.
--
-- Idempotent: guarded by a NOT EXISTS check so re-running this migration
-- (e.g. against a database where it was already applied) inserts nothing
-- new. Does NOT touch, modify, or delete the source retirement_accounts
-- row in any way — it stays exactly as saved (now correctly excluded from
-- totalRetirement by dashboard.ts's fix, and visible in the grid as an
-- "Archived item" once migration 0073 deprecates its catalogue entry).
--
-- Depends on migration 0071 (retirement_contributions table) and should be
-- applied after 0073 (catalogue deprecation) for a consistent taxonomy
-- state, though the ordering has no functional dependency either way.

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select '8606247e-a351-4eaf-a13d-dc6719843377', 'e2690fc9-7be3-55e9-bfe4-d1cc4df42a6c', 'employer_contributions', 32400, 'monthly', 'self',
  'Chunk 3b backfill from retirement_accounts.id=00d45201-b54f-595e-944c-8a532bd36a50 (deprecated catalogue key employer_contributions); linked to defined_benefit account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = '8606247e-a351-4eaf-a13d-dc6719843377' and rc.retirement_account_id = 'e2690fc9-7be3-55e9-bfe4-d1cc4df42a6c'
    and rc.contribution_type = 'employer_contributions' and rc.amount = 32400
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select '60457111-1b20-4d17-aff5-ed5fdf3b8118', '8e89def0-b53e-5bdc-aa9c-c7e367c46c47', 'employer_contributions', 147600, 'monthly', 'self',
  'Chunk 3b backfill from retirement_accounts.id=30397bf1-17ac-5ba7-9bde-7904bb5ac73c (deprecated catalogue key employer_contributions); linked to account_based_pension account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = '60457111-1b20-4d17-aff5-ed5fdf3b8118' and rc.retirement_account_id = '8e89def0-b53e-5bdc-aa9c-c7e367c46c47'
    and rc.contribution_type = 'employer_contributions' and rc.amount = 147600
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select '5e5aa253-18f2-4190-8eef-4c1fee42a26e', '19de9be2-ece6-5126-9d67-ecbc44eae088', 'employer_contributions', 32400, 'monthly', 'self',
  'Chunk 3b backfill from retirement_accounts.id=5c308f19-92fa-59a6-99fb-212de82d5f68 (deprecated catalogue key employer_contributions); linked to annuity account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = '5e5aa253-18f2-4190-8eef-4c1fee42a26e' and rc.retirement_account_id = '19de9be2-ece6-5126-9d67-ecbc44eae088'
    and rc.contribution_type = 'employer_contributions' and rc.amount = 32400
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select '76d59bf7-34dd-4d0d-9833-1cb0aaed1c43', '4925efc9-ed3e-5c7b-9f62-c74b798919fc', 'employer_contributions', 3600000, 'monthly', 'self',
  'Chunk 3b backfill from retirement_accounts.id=7e52a201-9fa1-5567-b122-547ed481462c (deprecated catalogue key employer_contributions); linked to retirement_savings account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = '76d59bf7-34dd-4d0d-9833-1cb0aaed1c43' and rc.retirement_account_id = '4925efc9-ed3e-5c7b-9f62-c74b798919fc'
    and rc.contribution_type = 'employer_contributions' and rc.amount = 3600000
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select '99d6ac7b-5c1c-4bc4-89be-2cae4f3b7664', 'a17a2676-b0cd-58af-96c1-97e638deead4', 'employer_contributions', 1800000, 'monthly', 'self',
  'Chunk 3b backfill from retirement_accounts.id=9ff815c1-244e-5938-b279-827782c0fb96 (deprecated catalogue key employer_contributions); linked to retail_super account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = '99d6ac7b-5c1c-4bc4-89be-2cae4f3b7664' and rc.retirement_account_id = 'a17a2676-b0cd-58af-96c1-97e638deead4'
    and rc.contribution_type = 'employer_contributions' and rc.amount = 1800000
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select '8454c9a3-0606-4969-8c21-0ce209ee198d', '30a5db05-193e-5bb7-aebf-4345d84366c0', 'employer_contributions', 1728000, 'monthly', 'self',
  'Chunk 3b backfill from retirement_accounts.id=dd709ab2-d485-5536-8123-38260883c13a (deprecated catalogue key employer_contributions); linked to other_retirement_assets account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = '8454c9a3-0606-4969-8c21-0ce209ee198d' and rc.retirement_account_id = '30a5db05-193e-5bb7-aebf-4345d84366c0'
    and rc.contribution_type = 'employer_contributions' and rc.amount = 1728000
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select 'c4ec6714-e1e2-4a9c-a9d9-d6136d7bcabd', '0a7d0e8d-d70d-52cf-a0fd-0dc4c9913a04', 'salary_sacrifice', 168000, 'monthly', 'self',
  'Chunk 3b backfill from retirement_accounts.id=1e88d889-0076-598d-9516-867696079656 (deprecated catalogue key salary_sacrifice); linked to account_based_pension account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = 'c4ec6714-e1e2-4a9c-a9d9-d6136d7bcabd' and rc.retirement_account_id = '0a7d0e8d-d70d-52cf-a0fd-0dc4c9913a04'
    and rc.contribution_type = 'salary_sacrifice' and rc.amount = 168000
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select 'c1c5f507-b513-4d07-9f90-dbe1d3762d78', '067bf9c7-149e-5948-a47e-0f4369dcc0bf', 'salary_sacrifice', 1728000, 'monthly', 'self',
  'Chunk 3b backfill from retirement_accounts.id=4858e764-1de5-599f-9ac5-9ba7eb3d70fe (deprecated catalogue key salary_sacrifice); linked to overseas_pension account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = 'c1c5f507-b513-4d07-9f90-dbe1d3762d78' and rc.retirement_account_id = '067bf9c7-149e-5948-a47e-0f4369dcc0bf'
    and rc.contribution_type = 'salary_sacrifice' and rc.amount = 1728000
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select '4bf647fd-0984-487b-b746-71c941ddff58', 'b7f914b8-858e-5abf-876f-03a3cefd243b', 'salary_sacrifice', 4400000, 'monthly', 'self',
  'Chunk 3b backfill from retirement_accounts.id=7dfc6fda-01ae-52e0-9c83-101d25326494 (deprecated catalogue key salary_sacrifice); linked to retirement_savings account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = '4bf647fd-0984-487b-b746-71c941ddff58' and rc.retirement_account_id = 'b7f914b8-858e-5abf-876f-03a3cefd243b'
    and rc.contribution_type = 'salary_sacrifice' and rc.amount = 4400000
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select '2984ac17-c9e5-4a20-8c0d-6d2cb55d7e02', 'b6c7e584-4ccf-512c-a733-2aad27573623', 'salary_sacrifice', 32400, 'monthly', 'self',
  'Chunk 3b backfill from retirement_accounts.id=8c9d95e6-c16b-50c0-a32e-8ae7fe99dfae (deprecated catalogue key salary_sacrifice); linked to allocated_pension account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = '2984ac17-c9e5-4a20-8c0d-6d2cb55d7e02' and rc.retirement_account_id = 'b6c7e584-4ccf-512c-a733-2aad27573623'
    and rc.contribution_type = 'salary_sacrifice' and rc.amount = 32400
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select 'e0b1a5da-57fb-433d-b517-c0ef3c9843e6', '6a07843d-5ca1-50c4-a95d-674d41558df5', 'salary_sacrifice', 672000, 'monthly', 'self',
  'Chunk 3b backfill from retirement_accounts.id=e5868594-a9fc-5244-9360-f4b5288006ae (deprecated catalogue key salary_sacrifice); linked to retirement_savings account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = 'e0b1a5da-57fb-433d-b517-c0ef3c9843e6' and rc.retirement_account_id = '6a07843d-5ca1-50c4-a95d-674d41558df5'
    and rc.contribution_type = 'salary_sacrifice' and rc.amount = 672000
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select '387ddc55-4813-4913-9e2c-64348eb0461f', '90b4a6b0-d27a-5c3c-a79f-33b32da60e07', 'salary_sacrifice', 147600, 'monthly', 'self',
  'Chunk 3b backfill from retirement_accounts.id=ff8aa19a-8568-559f-91f9-2ef4f5a926db (deprecated catalogue key salary_sacrifice); linked to transition_to_retirement account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = '387ddc55-4813-4913-9e2c-64348eb0461f' and rc.retirement_account_id = '90b4a6b0-d27a-5c3c-a79f-33b32da60e07'
    and rc.contribution_type = 'salary_sacrifice' and rc.amount = 147600
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select '75fc8c36-35a9-4fd7-8dc7-af8f189c9f4f', '1886c7d7-15bb-5867-b0d2-6b5d21e50280', 'personal_concessional', 672000, 'monthly', 'self',
  'Chunk 3b backfill from retirement_accounts.id=371f9c9b-81bd-5bef-84a1-df48565e22e0 (deprecated catalogue key personal_concessional); linked to allocated_pension account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = '75fc8c36-35a9-4fd7-8dc7-af8f189c9f4f' and rc.retirement_account_id = '1886c7d7-15bb-5867-b0d2-6b5d21e50280'
    and rc.contribution_type = 'personal_concessional' and rc.amount = 672000
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select '99d6ac7b-5c1c-4bc4-89be-2cae4f3b7664', 'a17a2676-b0cd-58af-96c1-97e638deead4', 'personal_concessional', 3600000, 'monthly', 'self',
  'Chunk 3b backfill from retirement_accounts.id=5fa3870e-a94f-55be-bcf6-632116b83b79 (deprecated catalogue key personal_concessional); linked to retail_super account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = '99d6ac7b-5c1c-4bc4-89be-2cae4f3b7664' and rc.retirement_account_id = 'a17a2676-b0cd-58af-96c1-97e638deead4'
    and rc.contribution_type = 'personal_concessional' and rc.amount = 3600000
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select '3edcbe79-141e-45b7-8fe7-1039b43797f2', 'f0402263-081f-5b69-8395-c5ecc481f84d', 'personal_concessional', 75000, 'monthly', 'self',
  'Chunk 3b backfill from retirement_accounts.id=93cfb0b6-4f7e-51e4-b441-452c77afadb2 (deprecated catalogue key personal_concessional); linked to industry_super account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = '3edcbe79-141e-45b7-8fe7-1039b43797f2' and rc.retirement_account_id = 'f0402263-081f-5b69-8395-c5ecc481f84d'
    and rc.contribution_type = 'personal_concessional' and rc.amount = 75000
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select '854fd280-0d90-4795-a528-4792aef1c524', '302cb8fc-12bb-5382-a16f-5f90be342c1c', 'personal_concessional', 1728000, 'monthly', 'self',
  'Chunk 3b backfill from retirement_accounts.id=b471b0f3-cb76-5bf5-a3dd-5c15b531a740 (deprecated catalogue key personal_concessional); linked to retirement_savings account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = '854fd280-0d90-4795-a528-4792aef1c524' and rc.retirement_account_id = '302cb8fc-12bb-5382-a16f-5f90be342c1c'
    and rc.contribution_type = 'personal_concessional' and rc.amount = 1728000
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select '79c7f796-5e72-4962-8e13-624e30026f07', '11fbb49d-aef8-5e80-8eaa-4fc6bbce69e3', 'personal_concessional', 147600, 'monthly', 'self',
  'Chunk 3b backfill from retirement_accounts.id=d5eb4bad-74b8-5aec-b085-a154d863ddb9 (deprecated catalogue key personal_concessional); linked to industry_super account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = '79c7f796-5e72-4962-8e13-624e30026f07' and rc.retirement_account_id = '11fbb49d-aef8-5e80-8eaa-4fc6bbce69e3'
    and rc.contribution_type = 'personal_concessional' and rc.amount = 147600
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select '8e28545a-4c76-4489-bced-b2ec3b39326a', 'd04ce587-8718-5430-9d8c-81b2daf11191', 'non_concessional', 907200, 'monthly', 'self',
  'Chunk 3b backfill from retirement_accounts.id=2e062018-eebd-5879-a07a-3ab6b929d987 (deprecated catalogue key non_concessional); linked to overseas_pension account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = '8e28545a-4c76-4489-bced-b2ec3b39326a' and rc.retirement_account_id = 'd04ce587-8718-5430-9d8c-81b2daf11191'
    and rc.contribution_type = 'non_concessional' and rc.amount = 907200
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select '1f356dd1-2c30-4c31-b3e5-829abdf61a27', '015754e3-b27a-523c-9afa-921e64305773', 'non_concessional', 672000, 'monthly', 'self',
  'Chunk 3b backfill from retirement_accounts.id=3c2e79e7-7a05-5556-ad50-c32342cc982b (deprecated catalogue key non_concessional); linked to allocated_pension account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = '1f356dd1-2c30-4c31-b3e5-829abdf61a27' and rc.retirement_account_id = '015754e3-b27a-523c-9afa-921e64305773'
    and rc.contribution_type = 'non_concessional' and rc.amount = 672000
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select '0fd32c7a-158a-4fbf-befa-cc77a828ef41', 'ccf6dd7a-e7cb-5815-876b-cb5e4ae69e5c', 'non_concessional', 672000, 'monthly', 'self',
  'Chunk 3b backfill from retirement_accounts.id=562ca39d-0914-5019-9774-a99b21f4d9f4 (deprecated catalogue key non_concessional); linked to retirement_savings account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = '0fd32c7a-158a-4fbf-befa-cc77a828ef41' and rc.retirement_account_id = 'ccf6dd7a-e7cb-5815-876b-cb5e4ae69e5c'
    and rc.contribution_type = 'non_concessional' and rc.amount = 672000
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select 'a75c38e5-6472-4850-bc39-233cb2957d8c', '2904bf16-19c6-542b-ad9c-77a76e094a4b', 'non_concessional', 22680, 'monthly', 'self',
  'Chunk 3b backfill from retirement_accounts.id=e43a0a6a-b59e-548c-bc37-da0040aa0bbc (deprecated catalogue key non_concessional); linked to retail_super account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = 'a75c38e5-6472-4850-bc39-233cb2957d8c' and rc.retirement_account_id = '2904bf16-19c6-542b-ad9c-77a76e094a4b'
    and rc.contribution_type = 'non_concessional' and rc.amount = 22680
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select 'd8039853-ae9f-4ed1-afd2-35138287d0b6', '9ed2d4f9-303a-5abc-bd1e-4808dc393958', 'government_co_contribution', 32400, 'monthly', 'self',
  'Chunk 3b backfill from retirement_accounts.id=08b961db-a9ba-5bb6-9140-dae7ba5dc632 (deprecated catalogue key government_co_contribution); linked to defined_benefit account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = 'd8039853-ae9f-4ed1-afd2-35138287d0b6' and rc.retirement_account_id = '9ed2d4f9-303a-5abc-bd1e-4808dc393958'
    and rc.contribution_type = 'government_co_contribution' and rc.amount = 32400
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select 'af048889-efb0-4d27-8f53-5fa6c202cd7c', '78e22501-715d-5c98-8ca6-c3081a080e5b', 'government_co_contribution', 45000, 'monthly', 'self',
  'Chunk 3b backfill from retirement_accounts.id=3af1fecc-44ba-531b-99e1-7c69f6faa305 (deprecated catalogue key government_co_contribution); linked to defined_benefit account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = 'af048889-efb0-4d27-8f53-5fa6c202cd7c' and rc.retirement_account_id = '78e22501-715d-5c98-8ca6-c3081a080e5b'
    and rc.contribution_type = 'government_co_contribution' and rc.amount = 45000
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select 'dca43ce2-4008-48d0-95ab-7b48a934be4c', 'a05e8318-6a08-5477-bd58-3bc7fbe4d82f', 'government_co_contribution', 4400000, 'monthly', 'self',
  'Chunk 3b backfill from retirement_accounts.id=4d66551f-ebc8-5d84-9163-4dd061c0cca1 (deprecated catalogue key government_co_contribution); linked to retirement_savings account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = 'dca43ce2-4008-48d0-95ab-7b48a934be4c' and rc.retirement_account_id = 'a05e8318-6a08-5477-bd58-3bc7fbe4d82f'
    and rc.contribution_type = 'government_co_contribution' and rc.amount = 4400000
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select '9bed77aa-e0dc-4b70-a7e6-8f6286e4fafb', 'f69d86ba-14cc-5b77-aee9-67f6d43a0394', 'government_co_contribution', 103320, 'monthly', 'self',
  'Chunk 3b backfill from retirement_accounts.id=c66c5332-c71d-595c-a061-6e0dc0a914a4 (deprecated catalogue key government_co_contribution); linked to industry_super account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = '9bed77aa-e0dc-4b70-a7e6-8f6286e4fafb' and rc.retirement_account_id = 'f69d86ba-14cc-5b77-aee9-67f6d43a0394'
    and rc.contribution_type = 'government_co_contribution' and rc.amount = 103320
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select 'd0f4afcc-272c-4eeb-9714-2a9d5f01cce6', 'ebc7b959-e827-5a67-9d88-01206c6eee8b', 'government_co_contribution', 1728000, 'monthly', 'self',
  'Chunk 3b backfill from retirement_accounts.id=f785a861-aa1d-5a06-a8cc-473c574df9eb (deprecated catalogue key government_co_contribution); linked to allocated_pension account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = 'd0f4afcc-272c-4eeb-9714-2a9d5f01cce6' and rc.retirement_account_id = 'ebc7b959-e827-5a67-9d88-01206c6eee8b'
    and rc.contribution_type = 'government_co_contribution' and rc.amount = 1728000
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select '76958197-2e32-4c4c-859c-d4babcdf5eef', '63f2b7ef-cd89-50d2-8aa2-3ff88baa14e1', 'spouse_contribution', 1008000, 'monthly', 'spouse',
  'Chunk 3b backfill from retirement_accounts.id=27e2da65-d30a-55a6-b181-ae56986e35ae (deprecated catalogue key spouse_contribution); linked to account_based_pension account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = '76958197-2e32-4c4c-859c-d4babcdf5eef' and rc.retirement_account_id = '63f2b7ef-cd89-50d2-8aa2-3ff88baa14e1'
    and rc.contribution_type = 'spouse_contribution' and rc.amount = 1008000
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select '891e877b-3615-445e-a0b1-17f014415883', '546832c4-fd1c-50fc-a697-be0a9d8249a6', 'spouse_contribution', 147600, 'monthly', 'spouse',
  'Chunk 3b backfill from retirement_accounts.id=6be2df38-29d4-5745-b877-4a6f57aa89e4 (deprecated catalogue key spouse_contribution); linked to retail_super account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = '891e877b-3615-445e-a0b1-17f014415883' and rc.retirement_account_id = '546832c4-fd1c-50fc-a697-be0a9d8249a6'
    and rc.contribution_type = 'spouse_contribution' and rc.amount = 147600
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select '12a3e92b-0b86-4d4a-92a2-9fd781affcb2', '0f5aede5-ddf8-59f0-a30c-0fdd25e55c2a', 'spouse_contribution', 672000, 'monthly', 'spouse',
  'Chunk 3b backfill from retirement_accounts.id=9f230b1a-cd5b-595d-828c-02b7e33f2c65 (deprecated catalogue key spouse_contribution); linked to retail_super account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = '12a3e92b-0b86-4d4a-92a2-9fd781affcb2' and rc.retirement_account_id = '0f5aede5-ddf8-59f0-a30c-0fdd25e55c2a'
    and rc.contribution_type = 'spouse_contribution' and rc.amount = 672000
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select '818f64c1-9c18-4568-bb6f-780c96b28c54', 'e2312fc2-7a2b-5155-8ad9-de5c4a03ea8e', 'spouse_contribution', 5200000, 'monthly', 'spouse',
  'Chunk 3b backfill from retirement_accounts.id=a52b3847-da86-5d5c-8473-83f9ff178cf0 (deprecated catalogue key spouse_contribution); linked to retirement_savings account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = '818f64c1-9c18-4568-bb6f-780c96b28c54' and rc.retirement_account_id = 'e2312fc2-7a2b-5155-8ad9-de5c4a03ea8e'
    and rc.contribution_type = 'spouse_contribution' and rc.amount = 5200000
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select '6e876aaf-21aa-44fb-85bc-ef4e9bbef2c5', '68467c1f-542f-52e4-ab93-854eeb854c36', 'spouse_contribution', 147600, 'monthly', 'spouse',
  'Chunk 3b backfill from retirement_accounts.id=e75b7533-a91c-584d-a118-9d0d5c9a5f6e (deprecated catalogue key spouse_contribution); linked to industry_super account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = '6e876aaf-21aa-44fb-85bc-ef4e9bbef2c5' and rc.retirement_account_id = '68467c1f-542f-52e4-ab93-854eeb854c36'
    and rc.contribution_type = 'spouse_contribution' and rc.amount = 147600
);

insert into retirement_contributions (user_id, retirement_account_id, contribution_type, amount, frequency, contributor, notes)
select '705c72d7-957b-4792-8cc1-fd2014c5f9c7', '0d40a498-f233-58d2-94ec-1b6310fc959e', 'spouse_contribution', 1728000, 'monthly', 'spouse',
  'Chunk 3b backfill from retirement_accounts.id=f5c64759-c47b-55ab-acb2-acd12e0a9e51 (deprecated catalogue key spouse_contribution); linked to overseas_pension account by same-user+same-currency single-candidate evidence.'
where not exists (
  select 1 from retirement_contributions rc
  where rc.user_id = '705c72d7-957b-4792-8cc1-fd2014c5f9c7' and rc.retirement_account_id = '0d40a498-f233-58d2-94ec-1b6310fc959e'
    and rc.contribution_type = 'spouse_contribution' and rc.amount = 1728000
);

-- =============================================================================
-- Rows EXCLUDED from this backfill (genuine data-quality gap, not guessed):
-- =============================================================================
-- id=0c03e43b-2521-5994-9b5e-01b594462afa user_id=4672a2f3-f2bd-4a02-b05f-3cf1725e1b8c master_item_key=employer_contributions reason: no candidate parent account (same user, same currency)
-- id=4d05b77d-372d-549e-912a-8af8b195c43f user_id=ea92e844-2315-4499-8476-38a501cd2336 master_item_key=employer_contributions reason: 2 ambiguous candidates
-- id=00330e2e-2d4c-5cef-84fe-ac47eabf2f52 user_id=9d58f4e1-07f2-46db-8c3f-af9bd9385a8a master_item_key=salary_sacrifice reason: 2 ambiguous candidates
-- id=09dc4813-92eb-51ed-bf86-3fe51c22bf87 user_id=f2ceb877-b2c7-4f8c-a4a0-503583ea8b50 master_item_key=salary_sacrifice reason: no candidate parent account (same user, same currency)
-- id=1cd0da6a-6cb2-5772-83ad-05b06bc2579b user_id=6f10dec4-b448-4f95-9c90-7bbed96c3eca master_item_key=salary_sacrifice reason: no candidate parent account (same user, same currency)
-- id=48c410e9-a394-53fb-ac67-be14589d3bb1 user_id=b0680754-5ab0-4273-9fba-2cbe8832e0b8 master_item_key=personal_concessional reason: 2 ambiguous candidates
-- id=971ffdac-562a-53a0-b022-bdef9dd2f5cf user_id=fd57a550-c091-4c21-b802-8e6802812c76 master_item_key=personal_concessional reason: no candidate parent account (same user, same currency)
-- id=d3103f11-c30a-5289-8724-f709506c78f9 user_id=4672a2f3-f2bd-4a02-b05f-3cf1725e1b8c master_item_key=personal_concessional reason: no candidate parent account (same user, same currency)
-- id=4c8c8b48-791c-5f03-a3dc-bdd3e9512286 user_id=f2ceb877-b2c7-4f8c-a4a0-503583ea8b50 master_item_key=non_concessional reason: no candidate parent account (same user, same currency)
-- id=87643413-c2a5-5a32-a98c-de49af490535 user_id=fd57a550-c091-4c21-b802-8e6802812c76 master_item_key=non_concessional reason: no candidate parent account (same user, same currency)
-- id=bcd55851-6767-5f18-8121-d272c004e0b3 user_id=b0680754-5ab0-4273-9fba-2cbe8832e0b8 master_item_key=non_concessional reason: 2 ambiguous candidates
-- id=e305ee28-db3e-545d-a83d-e0f6ebd5fe79 user_id=26addcb7-1446-4867-94fe-791da8cccc92 master_item_key=non_concessional reason: no candidate parent account (same user, same currency)
-- id=d8b3e635-a562-5aec-baa6-a69a07be0eba user_id=6f10dec4-b448-4f95-9c90-7bbed96c3eca master_item_key=spouse_contribution reason: no candidate parent account (same user, same currency)
