-- =============================================================================
-- FDH-6 — Financial Classification, Transfer, Duplicate & Recurring
-- Intelligence: economic-class gap-closure rule seed (0072).
-- =============================================================================
-- SCOPE: additive data only. Zero new tables, zero new columns, zero new
-- constraints. `docs/financial-data-hub/FDH6_R8_ADOPTION_AND_GAP_AUDIT.md`
-- section 3 independently confirmed (both by reading every migration file
-- and by a live-DEV REST query against `fdh_classification_rules`) that
-- three of the frozen 13-class `economic_transaction_type` taxonomy —
-- `debt_principal`, `asset_purchase`, `asset_sale` — are schema-complete
-- (FDH-2 migration 0053 already seeded their categories/subcategories:
-- `loan_principal`, `investment_purchase`, `investment_sale`, all AU+IN) but
-- UNREACHABLE: zero merchants and zero `fdh_classification_rules` rows have
-- ever pointed to them. This migration closes exactly that gap, in the same
-- generated-style shape FDH-2 migration 0056 established, reusing the
-- EXISTING categories/subcategories — no taxonomy change.
--
-- Every narrative pattern below is deliberately UNAMBIGUOUS (spec section
-- 50/55: "do not invent principal/interest splits... use the safest
-- supported classification"; "use \[asset] classes cautiously"). A generic
-- "LOAN REPAYMENT" or "HOME LOAN" narrative with no PRINCIPAL/INTEREST
-- qualifier is deliberately NOT matched here — that stays `unknown`/review,
-- exactly as it does today, because a single generic repayment line cannot
-- be safely split into principal vs interest without loan-schedule data
-- this system does not have. Every INSERT is `ON CONFLICT (rule_key) DO
-- NOTHING`, so re-applying this migration (or the full chain) twice
-- produces the same row count with zero duplicates — matching 0056's own
-- idempotency discipline.
-- =============================================================================

insert into fdh_classification_rules (rule_key, rule_type, country_applicability, match_definition, action_definition, priority, status, active, version) values
  -- --- debt_principal (category: loan_principal) ---------------------------
  ($lit$debt_principal_loan_principal_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["LOAN PRINCIPAL"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'debt_principal', 'category_id', ((select id from fdh_categories where category_key = 'loan_principal'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'loan_principal') and subcategory_key = 'other_loan_principal'))::text), 180, 'approved', true, 1),
  ($lit$debt_principal_repayment_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["PRINCIPAL REPAYMENT"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'debt_principal', 'category_id', ((select id from fdh_categories where category_key = 'loan_principal'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'loan_principal') and subcategory_key = 'other_loan_principal'))::text), 180, 'approved', true, 1),
  ($lit$debt_principal_home_loan$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["HOME LOAN PRINCIPAL"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'debt_principal', 'category_id', ((select id from fdh_categories where category_key = 'loan_principal'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'loan_principal') and subcategory_key = 'home_loan_principal'))::text), 175, 'approved', true, 1),
  ($lit$debt_principal_personal_loan$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["PERSONAL LOAN PRINCIPAL"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'debt_principal', 'category_id', ((select id from fdh_categories where category_key = 'loan_principal'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'loan_principal') and subcategory_key = 'personal_loan_principal'))::text), 175, 'approved', true, 1),
  ($lit$debt_principal_vehicle_loan$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["VEHICLE LOAN PRINCIPAL"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'debt_principal', 'category_id', ((select id from fdh_categories where category_key = 'loan_principal'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'loan_principal') and subcategory_key = 'vehicle_loan_principal'))::text), 175, 'approved', true, 1),
  ($lit$debt_principal_mortgage_generic$lit$, $lit$narrative_pattern$lit$, array['AU']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["MORTGAGE PRINCIPAL"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'debt_principal', 'category_id', ((select id from fdh_categories where category_key = 'loan_principal'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'loan_principal') and subcategory_key = 'home_loan_principal'))::text), 175, 'approved', true, 1),
  ($lit$debt_principal_emi_principal_in$lit$, $lit$narrative_pattern$lit$, array['IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["EMI","PRINCIPAL"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'debt_principal', 'category_id', ((select id from fdh_categories where category_key = 'loan_principal'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'loan_principal') and subcategory_key = 'other_loan_principal'))::text), 190, 'approved', true, 1),

  -- --- asset_purchase (category: investment_purchase) ----------------------
  ($lit$asset_purchase_broker_funding_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["BROKER FUNDING"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'asset_purchase', 'category_id', ((select id from fdh_categories where category_key = 'investment_purchase'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'investment_purchase') and subcategory_key = 'other_investment_purchase'))::text), 180, 'approved', true, 1),
  ($lit$asset_purchase_share_purchase_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["SHARE PURCHASE"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'asset_purchase', 'category_id', ((select id from fdh_categories where category_key = 'investment_purchase'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'investment_purchase') and subcategory_key = 'shares_equity_purchase'))::text), 180, 'approved', true, 1),
  ($lit$asset_purchase_mutual_fund_purchase_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["MUTUAL FUND PURCHASE"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'asset_purchase', 'category_id', ((select id from fdh_categories where category_key = 'investment_purchase'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'investment_purchase') and subcategory_key = 'managed_fund_mutual_fund_purchase'))::text), 180, 'approved', true, 1),
  ($lit$asset_purchase_mf_purchase_in$lit$, $lit$narrative_pattern$lit$, array['IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["MF PURCHASE"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'asset_purchase', 'category_id', ((select id from fdh_categories where category_key = 'investment_purchase'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'investment_purchase') and subcategory_key = 'managed_fund_mutual_fund_purchase'))::text), 190, 'approved', true, 1),
  ($lit$asset_purchase_managed_fund_purchase_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["MANAGED FUND PURCHASE"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'asset_purchase', 'category_id', ((select id from fdh_categories where category_key = 'investment_purchase'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'investment_purchase') and subcategory_key = 'managed_fund_mutual_fund_purchase'))::text), 180, 'approved', true, 1),

  -- --- asset_sale (category: investment_sale) -------------------------------
  ($lit$asset_sale_share_sale_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["SHARE SALE PROCEEDS"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'asset_sale', 'category_id', ((select id from fdh_categories where category_key = 'investment_sale'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'investment_sale') and subcategory_key = 'shares_equity_sale'))::text), 180, 'approved', true, 1),
  ($lit$asset_sale_mutual_fund_redemption_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["MUTUAL FUND REDEMPTION"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'asset_sale', 'category_id', ((select id from fdh_categories where category_key = 'investment_sale'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'investment_sale') and subcategory_key = 'managed_fund_mutual_fund_sale'))::text), 180, 'approved', true, 1),
  ($lit$asset_sale_mf_redemption_in$lit$, $lit$narrative_pattern$lit$, array['IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["MF REDEMPTION"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'asset_sale', 'category_id', ((select id from fdh_categories where category_key = 'investment_sale'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'investment_sale') and subcategory_key = 'managed_fund_mutual_fund_sale'))::text), 190, 'approved', true, 1),
  ($lit$asset_sale_fund_redemption_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["FUND REDEMPTION"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'asset_sale', 'category_id', ((select id from fdh_categories where category_key = 'investment_sale'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'investment_sale') and subcategory_key = 'managed_fund_mutual_fund_sale'))::text), 180, 'approved', true, 1),
  ($lit$asset_sale_investment_redemption_generic$lit$, $lit$narrative_pattern$lit$, array['AU','IN']::char(2)[], $json${"match_kind":"narrative_pattern","required_terms_normalised":["INVESTMENT REDEMPTION"]}$json$::jsonb, jsonb_build_object('action_kind', 'classify', 'economic_transaction_type', 'asset_sale', 'category_id', ((select id from fdh_categories where category_key = 'investment_sale'))::text, 'subcategory_id', ((select id from fdh_subcategories where category_id = (select id from fdh_categories where category_key = 'investment_sale') and subcategory_key = 'other_investment_sale'))::text), 180, 'approved', true, 1)
on conflict (rule_key) do nothing;

-- =============================================================================
-- End FDH-6 migration 0072.
-- =============================================================================
