-- NAV 1 Stage D (D.9 follow-up) — AMFI fund-house codes, stored once.
--
-- WHY. On-demand hydration needs a scheme's AMFI fund-house code, because
-- AMFI's NAV history report can only be filtered by fund house (a 3-day
-- whole-market window is ~3.5 MB). The adapter used to discover the codes by
-- probing all 150 on every cold server process -- 150 requests, 8 at a time.
-- AMFI appears to throttle that burst from the production server's address:
-- the first real production hydration run slowed to ~90 s per request after
-- it, and the second (2026-09-24) stalled outright, recording nothing in 20
-- minutes. On a 30-minute schedule it would have sent AMFI ~7,000 probe
-- requests a day. The same burst finishes in 7 s from a workstation, which is
-- why local testing never showed it.
--
-- NOW. The ~53 fund houses are stored here, and a scheme is resolved through
-- ii_scheme_master.amc_name. A hydration run sends AMFI no probes at all.
-- Resolving by fund-house NAME also covers schemes that no longer publish
-- daily, which the per-day probe could never see: measured against
-- production, 14,324 of 14,358 scheme-master rows (99.76%) resolve, against
-- ~8,730 (~61%) for the probe; all 17 user-held funds resolve. The misses (one
-- fund house not publishing on the reference day, and 22 schemes with no
-- fund-house name) are exactly what the TIGZIG fallback is for.
--
-- GLOBAL reference data, identical in every environment -- so, unlike the
-- per-environment retention-policy row, this belongs in a migration. No user
-- column. Service role writes; reference-data admins read.
--
-- REFRESH. Re-run scripts/pc6_amfi_fund_houses_seed.ts for a recent full
-- business day and apply its output (idempotent). A new fund house simply
-- resolves via the TIGZIG fallback until then.

create table if not exists ii_amfi_fund_houses (
  fund_house_code integer primary key check (fund_house_code > 0),
  amc_name text not null,
  observed_on date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- One code per fund-house name, compared the way the resolver compares.
create unique index if not exists ii_amfi_fund_houses_amc_name_key
  on ii_amfi_fund_houses (lower(amc_name));

alter table ii_amfi_fund_houses enable row level security;

drop policy if exists "admin read ii_amfi_fund_houses" on ii_amfi_fund_houses;
create policy "admin read ii_amfi_fund_houses" on ii_amfi_fund_houses
  for select using (is_pc6_reference_data_admin());

comment on table ii_amfi_fund_houses is
  'NAV 1 (0191). AMFI fund-house code per fund-house name, so hydration can filter AMFI''s NAV history '
  'report without probing. Resolved via ii_scheme_master.amc_name. Refresh with '
  'scripts/pc6_amfi_fund_houses_seed.ts.';

-- Generated by scripts/pc6_amfi_fund_houses_seed.ts from AMFI's NAV history report for 22-Sep-2026:
-- 53 fund houses, 8730 schemes. Idempotent.
insert into ii_amfi_fund_houses (fund_house_code, amc_name, observed_on) values
  (3, 'Aditya Birla Sun Life Mutual Fund', '2026-09-22'),
  (4, 'Baroda BNP Paribas Mutual Fund', '2026-09-22'),
  (6, 'DSP Mutual Fund', '2026-09-22'),
  (9, 'HDFC Mutual Fund', '2026-09-22'),
  (13, 'quant Mutual Fund', '2026-09-22'),
  (16, 'JM Financial Mutual Fund', '2026-09-22'),
  (17, 'Kotak Mahindra Mutual Fund', '2026-09-22'),
  (18, 'LIC Mutual Fund', '2026-09-22'),
  (20, 'ICICI Prudential Mutual Fund', '2026-09-22'),
  (21, 'Nippon India Mutual Fund', '2026-09-22'),
  (22, 'SBI Mutual Fund', '2026-09-22'),
  (25, 'Tata Mutual Fund', '2026-09-22'),
  (26, 'Taurus Mutual Fund', '2026-09-22'),
  (27, 'Franklin Templeton Mutual Fund', '2026-09-22'),
  (28, 'UTI Mutual Fund', '2026-09-22'),
  (32, 'Canara Robeco Mutual Fund', '2026-09-22'),
  (33, 'Sundaram Mutual Fund', '2026-09-22'),
  (37, 'HSBC Mutual Fund', '2026-09-22'),
  (41, 'Quantum Mutual Fund', '2026-09-22'),
  (42, 'Invesco Mutual Fund', '2026-09-22'),
  (45, 'Mirae Asset Mutual Fund', '2026-09-22'),
  (46, 'Bank of India Mutual Fund', '2026-09-22'),
  (47, 'Edelweiss Mutual Fund', '2026-09-22'),
  (48, 'Bandhan Mutual Fund', '2026-09-22'),
  (53, 'Axis Mutual Fund', '2026-09-22'),
  (54, 'Navi Mutual Fund', '2026-09-22'),
  (55, 'Motilal Oswal Mutual Fund', '2026-09-22'),
  (58, 'PGIM India Mutual Fund', '2026-09-22'),
  (61, 'Union Mutual Fund', '2026-09-22'),
  (62, '360 ONE Mutual Fund', '2026-09-22'),
  (63, 'Groww Mutual Fund', '2026-09-22'),
  (64, 'PPFAS Mutual Fund', '2026-09-22'),
  (67, 'Shriram Mutual Fund', '2026-09-22'),
  (69, 'Mahindra Manulife Mutual Fund', '2026-09-22'),
  (70, 'ITI Mutual Fund', '2026-09-22'),
  (71, 'WhiteOak Capital Mutual Fund', '2026-09-22'),
  (72, 'Trust Mutual Fund', '2026-09-22'),
  (73, 'NJ Mutual Fund', '2026-09-22'),
  (74, 'Samco Mutual Fund', '2026-09-22'),
  (75, 'Bajaj Finserv Mutual Fund', '2026-09-22'),
  (76, 'Helios Mutual Fund', '2026-09-22'),
  (77, 'Zerodha Mutual Fund', '2026-09-22'),
  (78, 'Old Bridge Mutual Fund', '2026-09-22'),
  (79, 'Unifi Mutual Fund', '2026-09-22'),
  (80, 'Angel One Mutual Fund', '2026-09-22'),
  (81, 'Capitalmind Mutual Fund', '2026-09-22'),
  (82, 'Jio BlackRock Mutual Fund', '2026-09-22'),
  (83, 'The Wealth Company Mutual Fund', '2026-09-22'),
  (84, 'Choice Mutual Fund', '2026-09-22'),
  (85, 'Abakkus Mutual Fund', '2026-09-22'),
  (86, 'AlphaGrep Mutual Fund', '2026-09-22'),
  (87, 'ASK MUTUAL FUND', '2026-09-22'),
  (89, 'Monarch Mutual Fund', '2026-09-22')
on conflict (fund_house_code) do update
  set amc_name = excluded.amc_name, observed_on = excluded.observed_on, updated_at = now();
