import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync, existsSync } from 'fs';
import { join } from 'path';
import { PasswordException } from 'pdf-parse';
import { extractPdfText } from '@/lib/services/investment-intelligence/pdfExtraction';
import { parseExtractedDocument } from '@/lib/services/investment-intelligence/parsers/registry';
import { scaledToDecimalString } from '@/lib/services/investment-intelligence/decimal';
import { planFolioAccountResolution, accountResolutionKey } from '@/lib/services/investment-intelligence/accountResolution';
import { computeTransactionFingerprint } from '@/lib/services/investment-intelligence/fingerprint';
import { reconcilePosition, determineHistoryCompleteness } from '@/lib/services/investment-intelligence/reconciliation';
import { evaluateCertification } from '@/lib/services/investment-intelligence/certification';
import { DEFAULT_RECONCILIATION_CONFIG } from '@/lib/services/investment-intelligence/reconciliationConfig';
import type { ParsedTransactionRecord } from '@/lib/services/investment-intelligence/parsers/types';

// II-PC3-C1 — REAL_CAMS_VARIANT_QUALIFICATION pack (Q01-Q12), DB-free half.
//
// Built against the REAL CAMS grammar recorded in
// docs/investment-intelligence/II_PC3_REAL_CAMS_VARIANT_FINGERPRINT.md —
// NOT the pre-real-sample "detailed_v1" grammar iiPc3QualificationPack.test.ts
// targets (that file/pack is unmodified and re-run as
// LEGACY_CAMS_GRAMMAR_REGRESSION alongside this one, never replaced).
//
// Same discipline as the legacy pack: real PDF bytes -> real `pdf-parse`
// extraction -> real detector/parser -> independent, hand-authored oracle
// (never generated by running the parser). DB-touching stages are proven
// separately in tests/live-dev/iiPc3RealVariantQualificationLiveDev.test.ts.

const PACK_DIR = join(process.cwd(), 'lib/fixtures/investment-intelligence/pc3-cams-real-variant');

interface ExpectedTxn { folioNumber: string; scheme: string; isin: string | null; transactionDateIso: string; canonicalType: string; amount: string; units: string; navRaw: string | null; sourceReference: string | null }
interface ExpectedHolding { folioNumber: string; scheme: string; units: string; value: string }
interface ExpectedFixture {
  fixtureId: string; title: string; sourceKey: string; documentTypeDetected: string;
  statementPeriodStartIso: string; statementPeriodEndIso: string;
  accounts: { folioNumber: string; holderName: string | null; holdingModeRaw: string | null }[];
  transactionCount: number; transactions: ExpectedTxn[];
  holdingCount: number; holdings: ExpectedHolding[];
  notes: string | null;
}

function loadOracle(id: string): ExpectedFixture {
  return JSON.parse(readFileSync(join(PACK_DIR, `${id}.expected.json`), 'utf8')) as ExpectedFixture;
}
function loadPdfBytes(id: string): Buffer {
  return readFileSync(join(PACK_DIR, `${id}.pdf`));
}

async function runPipeline(id: string, password?: string) {
  const bytes = loadPdfBytes(id);
  const extraction = await extractPdfText(bytes, password);
  if (!extraction.ok) return { extraction, result: null as ReturnType<typeof parseExtractedDocument> | null };
  const result = parseExtractedDocument(extraction.text);
  return { extraction, result };
}

function assertOracleMatch(parsed: NonNullable<ReturnType<typeof parseExtractedDocument>['parsed']>, expected: ExpectedFixture) {
  expect(parsed.accounts.length).toBe(expected.accounts.length);
  for (const expAcc of expected.accounts) {
    const found = parsed.accounts.find((a) => a.folioNumber === expAcc.folioNumber);
    expect(found, `expected account with folio ${expAcc.folioNumber} to be found`).toBeTruthy();
    // Real-variant grammar has no Name:/Holding Mode: labels at all —
    // both must be null, never a guessed/fabricated value.
    expect(found!.holderName).toBeNull();
    expect(found!.holdingModeRaw).toBeNull();
  }
  expect(parsed.transactions.length).toBe(expected.transactionCount);
  for (const expTxn of expected.transactions) {
    const found = expTxn.sourceReference
      ? parsed.transactions.find((t) => t.folioNumber === expTxn.folioNumber && t.sourceReference === expTxn.sourceReference)
      : parsed.transactions.find((t) => t.folioNumber === expTxn.folioNumber && t.transactionDateIso === expTxn.transactionDateIso && t.canonicalType === expTxn.canonicalType && t.sourceReference === null);
    expect(found, `expected transaction ref=${expTxn.sourceReference ?? '(fee row, no ref)'} folio=${expTxn.folioNumber} date=${expTxn.transactionDateIso} to be found`).toBeTruthy();
    expect(found!.scheme.rawSchemeName).toBe(expTxn.scheme);
    expect(found!.canonicalType).toBe(expTxn.canonicalType);
    expect(scaledToDecimalString(found!.amountScaled, 2)).toBe(expTxn.amount);
    expect(found!.transactionDateIso).toBe(expTxn.transactionDateIso);
    expect(scaledToDecimalString(found!.unitsScaled ?? BigInt(0), 6)).toBe(expTxn.units);
    if (expTxn.navRaw === null) {
      // Fee/tax rows never carry a Price/NAV field on this grammar — must
      // be genuinely null, never fabricated as 0 or guessed.
      expect(found!.navScaled).toBeNull();
    } else {
      expect(found!.navScaled).not.toBeNull();
      expect(scaledToDecimalString(found!.navScaled!, 6)).toBe(expTxn.navRaw);
    }
  }
  expect(parsed.holdings.length).toBe(expected.holdingCount);
  for (const expHolding of expected.holdings) {
    const found = parsed.holdings.find((h) => h.folioNumber === expHolding.folioNumber && h.scheme.rawSchemeName === expHolding.scheme);
    expect(found, `expected holding for folio ${expHolding.folioNumber} scheme ${expHolding.scheme} to be found`).toBeTruthy();
    expect(scaledToDecimalString(found!.unitsScaled, 3)).toBe(expHolding.units);
  }
}

describe('II-PC3-C1 — Golden real-variant fixture gate (RED->GREEN)', () => {
  it('golden real-variant fixture: real PDF bytes -> real pdf-parse extraction -> detector -> parser -> zero warnings, correct fee/tax classification', async () => {
    const bytes = readFileSync(join(process.cwd(), 'lib/fixtures/investment-intelligence/pc3-cams-real-variant/pc3-golden-real-variant.pdf'));
    const extraction = await extractPdfText(bytes);
    expect(extraction.ok).toBe(true);
    if (!extraction.ok) return;
    const result = parseExtractedDocument(extraction.text);
    expect(result.parsed).not.toBeNull();
    expect(result.parsed!.accounts.length).toBe(2);
    expect(result.parsed!.transactions.length).toBe(6);
    expect(result.parsed!.holdings.length).toBe(2);
    expect(result.parsed!.warnings).toEqual([]);
    const types = result.parsed!.transactions.map((t) => t.canonicalType);
    expect(types).toEqual(['purchase', 'fee', 'tax', 'sip', 'sip', 'purchase']);
    // The fee/tax rows must never carry units/NAV — proving they are not
    // misclassified as an economic transaction.
    const feeTxn = result.parsed!.transactions.find((t) => t.canonicalType === 'fee')!;
    const taxTxn = result.parsed!.transactions.find((t) => t.canonicalType === 'tax')!;
    expect(feeTxn.unitsScaled).toBe(BigInt(0));
    expect(feeTxn.navScaled).toBeNull();
    expect(taxTxn.unitsScaled).toBe(BigInt(0));
    expect(taxTxn.navScaled).toBeNull();
  });
});

describe('II-PC3-C1 — REAL_CAMS_VARIANT_QUALIFICATION pack: Q01-Q12 preflight + oracle', () => {
  const positives: { id: string; label: string }[] = [
    { id: 'pc3rv-q01-baseline-multi-amc-multi-folio', label: 'Q01 real-variant baseline' },
    { id: 'pc3rv-q03-two-folios-fifo-scope', label: 'Q03 real-variant two folios' },
    { id: 'pc3rv-q04-monthly-delta', label: 'Q04 real-variant monthly delta' },
    { id: 'pc3rv-q06-sip-rich-skipped-month', label: 'Q06 real-variant SIP-rich, skipped month' },
    { id: 'pc3rv-q07-transaction-rich', label: 'Q07 real-variant transaction-rich' },
    { id: 'pc3rv-q09-continuation-amc-transition', label: 'Q09 real-variant continuation + AMC transition' },
    { id: 'pc3rv-q11-fee-evidence', label: 'Q11 real-variant fee evidence' },
    { id: 'pc3rv-q12-continuation-stress', label: 'Q12 real-variant continuation stress' },
  ];

  for (const { id, label } of positives) {
    it(`${label} (${id}): preflight VALID_POSITIVE — extractable, detected, parsed, matches independent oracle, zero real PII`, async () => {
      const expected = loadOracle(id);
      const { extraction, result } = await runPipeline(id);
      expect(extraction.ok, `${id} must be extractable`).toBe(true);
      expect(result!.detection.parser, `${id} must be detected`).not.toBeNull();
      expect(result!.parsed!.errors, `${id} must parse with zero errors`).toEqual([]);
      assertOracleMatch(result!.parsed!, expected);
      const rawPans = extraction.ok ? extraction.text.match(/PAN:\s*[A-Z]{5}\d{4}[A-Z]/g) ?? [] : [];
      for (const p of rawPans) expect(p).toMatch(/PCRVQ/); // this pack's own synthetic PAN prefix — never a plausible real PAN series code
    });
  }

  it('Q02 (encrypted duplicate of Q01): no password -> password_required, wrong password -> wrong_password, correct password -> decrypts to SAME economics as Q01', async () => {
    const encId = 'pc3rv-q02-encrypted-duplicate-of-q01';
    const bytes = loadPdfBytes(encId);
    const noPw = await extractPdfText(bytes);
    expect(noPw.ok).toBe(false);
    if (!noPw.ok) expect(noPw.kind).toBe('password_required');

    const wrongPw = await extractPdfText(bytes, 'definitely-the-wrong-password');
    expect(wrongPw.ok).toBe(false);
    if (!wrongPw.ok) expect(wrongPw.kind).toBe('wrong_password');

    const expected = loadOracle(encId);
    const { extraction, result } = await runPipeline(encId, 'PC3RV-Qualification-2026');
    expect(extraction.ok).toBe(true);
    expect(result!.parsed!.errors).toEqual([]);
    assertOracleMatch(result!.parsed!, expected);

    // Never the real document's password, never persisted anywhere: only
    // used here and in the live-DEV suite, matching the legacy Q02's own
    // discipline.
    try {
      const { PDFParse } = await import('pdf-parse');
      const p = new PDFParse({ data: bytes });
      await p.getText();
      expect.fail('expected PasswordException');
    } catch (e) {
      expect(e).toBeInstanceOf(PasswordException);
    }
  });

  it('Q05 (exact reimport of Q04): re-parsing the SAME fixture twice produces IDENTICAL transaction fingerprints per row (guaranteed DB-level dedup)', async () => {
    const { result: r1 } = await runPipeline('pc3rv-q04-monthly-delta');
    const { result: r2 } = await runPipeline('pc3rv-q04-monthly-delta');
    expect(r1!.parsed!.transactions.length).toBeGreaterThan(0);
    expect(r1!.parsed!.transactions.length).toBe(r2!.parsed!.transactions.length);
    const accountId = '00000000-0000-0000-0000-0000000000a1';
    const instrumentId = '00000000-0000-0000-0000-0000000000a2';
    for (let i = 0; i < r1!.parsed!.transactions.length; i++) {
      const t1 = r1!.parsed!.transactions[i];
      const t2 = r2!.parsed!.transactions[i];
      const fp1 = computeTransactionFingerprint({ sourceKey: 'cams', accountId, instrumentId, transactionDateIso: t1.transactionDateIso, transactionType: t1.canonicalType, amountScaled: t1.amountScaled, unitsScaled: t1.unitsScaled, navScaled: t1.navScaled, sourceReference: t1.sourceReference });
      const fp2 = computeTransactionFingerprint({ sourceKey: 'cams', accountId, instrumentId, transactionDateIso: t2.transactionDateIso, transactionType: t2.canonicalType, amountScaled: t2.amountScaled, unitsScaled: t2.unitsScaled, navScaled: t2.navScaled, sourceReference: t2.sourceReference });
      expect(fp1, `row ${i} must fingerprint-match itself across a re-import`).toBe(fp2);
    }
  });

  it('Q04 monthly delta: transactions shared with Q01/Q03 fingerprint IDENTICALLY (dedup), the genuinely new ones fingerprint DIFFERENTLY (no false dedup)', async () => {
    const { result: q01 } = await runPipeline('pc3rv-q01-baseline-multi-amc-multi-folio');
    const { result: q04 } = await runPipeline('pc3rv-q04-monthly-delta');
    const accountId = '00000000-0000-0000-0000-0000000000b1';
    const instrumentId = '00000000-0000-0000-0000-0000000000b2';
    const fp = (t: ParsedTransactionRecord) =>
      computeTransactionFingerprint({ sourceKey: 'cams', accountId, instrumentId, transactionDateIso: t.transactionDateIso, transactionType: t.canonicalType, amountScaled: t.amountScaled, unitsScaled: t.unitsScaled, navScaled: t.navScaled, sourceReference: t.sourceReference });
    const q01Purchase = q01!.parsed!.transactions.find((t) => t.sourceReference === 'PCRV1-001')!;
    const q04SamePurchase = q04!.parsed!.transactions.find((t) => t.sourceReference === 'PCRV1-001')!;
    const q04NewSip = q04!.parsed!.transactions.find((t) => t.sourceReference === 'PCRV4-NEW-001')!;
    expect(fp(q01Purchase)).toBe(fp(q04SamePurchase)); // must dedup
    expect(fp(q01Purchase)).not.toBe(fp(q04NewSip)); // must NOT false-dedup a genuinely new transaction
  });

  it('Q03 real-variant, two folios: account-resolution plan produces exactly 2 DISTINCT keys — zero cross-folio contamination (F1 probe)', async () => {
    const { result } = await runPipeline('pc3rv-q03-two-folios-fifo-scope');
    const parsed = result!.parsed!;
    const plan = planFolioAccountResolution({ accounts: parsed.accounts, transactions: parsed.transactions, holdings: parsed.holdings });
    expect(plan.assignments.length).toBe(2);
    const folios = [...new Set(parsed.transactions.map((t) => t.folioNumber))];
    expect(folios.length).toBe(2);
    const [folioA, folioB] = folios;
    // scheme.amcName stays '' in this grammar (disclosed gap) — an empty
    // amcName resolves to accountResolution.ts's own 'Unknown AMC' default
    // (unmodified, pre-existing behaviour) — resolution must still be
    // keyed distinctly per folio despite sharing that same default.
    const keyA = accountResolutionKey(folioA, 'Unknown AMC');
    const keyB = accountResolutionKey(folioB, 'Unknown AMC');
    expect(keyA).not.toBe(keyB);
    for (const t of parsed.transactions) {
      const resolved = plan.resolveRowKey(t.folioNumber, t.scheme.amcName);
      if (t.folioNumber === folioA) expect(resolved).toBe(keyA);
      if (t.folioNumber === folioB) expect(resolved).toBe(keyB);
    }
  });

  it('Q06 real-variant SIP-rich: exactly 5 SIP transactions (Jan,Feb,Apr,May,Jun), zero phantom March row', async () => {
    const { result } = await runPipeline('pc3rv-q06-sip-rich-skipped-month');
    const dates = result!.parsed!.transactions.map((t) => t.transactionDateIso).sort();
    expect(dates).toEqual(['2025-01-05', '2025-02-05', '2025-04-05', '2025-05-05', '2025-06-05']);
    expect(result!.parsed!.transactions.every((t) => t.canonicalType === 'sip')).toBe(true);
  });

  it('Q07 real-variant transaction-rich: every currently-supported canonical type present, plus fee evidence, opening balance correctly zero throughout', async () => {
    const { result } = await runPipeline('pc3rv-q07-transaction-rich');
    const types = result!.parsed!.transactions.map((t) => t.canonicalType).sort();
    expect(types).toEqual(['dividend', 'fee', 'purchase', 'redemption', 'reinvestment', 'sip', 'switch_in', 'switch_out']);
    // Reproduces the legacy pack's Finding: opening balance must be
    // correctly zero, so the closing balance the fixture prints is exactly
    // consistent with the sum of its own listed transactions from
    // inception — checked directly here, not just asserted implicitly.
    const holding = result!.parsed!.holdings.find((h) => h.scheme.rawSchemeName.includes('Composite Growth'))!;
    const schemeATxns = result!.parsed!.transactions.filter((t) => t.scheme.rawSchemeName.includes('Composite Growth'));
    const direction: Record<string, number> = { purchase: 1, sip: 1, redemption: -1, dividend: 0, reinvestment: 1, switch_out: -1, fee: 0 };
    let sum = BigInt(0);
    for (const t of schemeATxns) sum += BigInt(direction[t.canonicalType] ?? 0) * (t.unitsScaled ?? BigInt(0));
    expect(scaledToDecimalString(sum, 3)).toBe(scaledToDecimalString(holding.unitsScaled, 3));
  });

  it('Q08 real-variant: preflight VALID_NEGATIVE — parses cleanly, but reconciliation MUST detect the deliberate closing-balance mismatch (never silently certify)', async () => {
    const { extraction, result } = await runPipeline('pc3rv-q08-reconciliation-mismatch');
    expect(extraction.ok).toBe(true);
    expect(result!.parsed!.errors).toEqual([]);
    const txn = result!.parsed!.transactions[0];
    const holding = result!.parsed!.holdings[0];
    const reconciliation = reconcilePosition({
      openingUnitsScaled: null,
      transactions: [{ canonicalType: txn.canonicalType, unitsScaled: txn.unitsScaled }],
      statementClosingUnitsScaled: holding.unitsScaled,
      historyCompleteness: determineHistoryCompleteness({ hasExplicitOpeningBalanceTransaction: false, hasAnyTransactionHistory: true, hasClosingHoldingSnapshot: true, statementCoversFromInception: true }),
      config: DEFAULT_RECONCILIATION_CONFIG,
    });
    expect(reconciliation.withinTolerance, 'Q08 must be flagged OUTSIDE tolerance — this is the entire point of the fixture').toBe(false);
    const certification = evaluateCertification({
      sourceDetected: true, parserFatalError: false, documentCorrupt: false, ownerUnresolved: false, instrumentUnresolved: false, crossHouseholdConflict: false, invalidCanonicalRecord: false,
      hasOpenBlockingReconciliationCase: false, hasMaterialUnclassifiedTransaction: false, hasNonMaterialUnclassifiedTransaction: false,
      reconciliation, historyCompleteness: 'complete_from_inception', staleStatementDays: null, staleThresholdDays: 90,
    });
    expect(certification.status).toBe('reconciliation_required');
    expect(certification.blockingReasons.some((b) => b.code === 'unit_variance_exceeds_tolerance')).toBe(true);
  });

  it('Q09 real-variant: 7 transactions across a REAL page break with zero header reprint, zero loss/duplication, then a distinct second folio/scheme (AMC transition) with zero cross-contamination', async () => {
    const { result } = await runPipeline('pc3rv-q09-continuation-amc-transition');
    const parsed = result!.parsed!;
    expect(parsed.transactions.length).toBe(7);
    const refs = parsed.transactions.map((t) => t.sourceReference).filter(Boolean);
    expect(new Set(refs).size).toBe(refs.length); // zero duplication
    const folios = new Set(parsed.transactions.map((t) => t.folioNumber));
    expect(folios.size).toBe(2); // the AMC-transition folio/scheme genuinely present
  });

  it('Q10 real-variant: preflight VALID_NEGATIVE — the impossible-date row is REJECTED with a structured error, the clean row still parses, fatal-error signal reaches certification', async () => {
    const { extraction, result } = await runPipeline('pc3rv-q10-malformed-negative');
    expect(extraction.ok).toBe(true);
    const parsed = result!.parsed!;
    expect(parsed.errors.length).toBeGreaterThanOrEqual(1);
    expect(parsed.errors.some((e) => e.code === 'unparseable_date')).toBe(true);
    expect(parsed.transactions.length).toBe(1);
    expect(parsed.transactions[0].sourceReference).toBe('PCRV10-002');

    const parserHasFatalError = parsed.errors.length > 0;
    const certification = evaluateCertification({
      sourceDetected: true, parserFatalError: parserHasFatalError, documentCorrupt: false, ownerUnresolved: false, instrumentUnresolved: false, crossHouseholdConflict: false, invalidCanonicalRecord: false,
      hasOpenBlockingReconciliationCase: false, hasMaterialUnclassifiedTransaction: false, hasNonMaterialUnclassifiedTransaction: false,
      reconciliation: { reconciledOpeningUnitsScaled: null, reconciledClosingUnitsScaled: null, statementClosingUnitsScaled: BigInt(0), unitVarianceScaled: null, withinTolerance: null },
      historyCompleteness: 'holdings_only', staleStatementDays: null, staleThresholdDays: 90,
    });
    expect(certification.status, 'a document with a genuine parse-time error must NEVER reach certified/certified_with_warnings on reconciliation math alone').toBe('reconciliation_required');
    expect(certification.blockingReasons.some((b) => b.code === 'parser_fatal_error')).toBe(true);
  });

  it('Q11 real-variant fee evidence: every fee/tax row classifies correctly, carries ZERO units and NULL nav, is never misclassified as a holding/economic transaction', async () => {
    const { result } = await runPipeline('pc3rv-q11-fee-evidence');
    const parsed = result!.parsed!;
    const feeTaxTxns = parsed.transactions.filter((t) => t.canonicalType === 'fee' || t.canonicalType === 'tax');
    expect(feeTaxTxns.length).toBe(4); // 2 fee + 2 tax, per the fixture's design
    for (const t of feeTaxTxns) {
      expect(t.unitsScaled).toBe(BigInt(0));
      expect(t.navScaled).toBeNull();
      expect(t.sourceReference).toBeNull();
    }
    // Exactly one holding exists (one scheme) — fee/tax rows never became
    // their own holding/instrument.
    expect(parsed.holdings.length).toBe(1);
    // The dual-fee date (Stamp Duty + STT same day) must produce TWO
    // distinct transaction rows, not one merged/overwritten row.
    const dualFeeDate = '2025-03-11';
    const onThatDate = parsed.transactions.filter((t) => t.transactionDateIso === dualFeeDate);
    expect(onThatDate.length).toBe(2);
    expect(onThatDate.map((t) => t.canonicalType).sort()).toEqual(['fee', 'tax']);
  });

  it('Q12 real-variant continuation stress: 18 transactions across a page break with zero header reprint, zero loss/duplication, zero cross-scheme/cross-AMC leakage', async () => {
    const { result } = await runPipeline('pc3rv-q12-continuation-stress');
    const parsed = result!.parsed!;
    expect(parsed.transactions.length).toBe(18);
    const refs = parsed.transactions.map((t) => t.sourceReference).filter(Boolean);
    expect(new Set(refs).size).toBe(refs.length); // zero duplication
    const folio1Refs = new Set(refs.filter((r) => r!.startsWith('PCRV12-0')));
    const folio2Refs = new Set(refs.filter((r) => r!.startsWith('PCRV12-EXTRA')));
    expect(folio1Refs.size).toBe(14);
    expect(folio2Refs.size).toBe(2);
    // Every folio-1 transaction must resolve to folio 1 only, never folio 2.
    const folios = new Set(parsed.transactions.map((t) => t.folioNumber));
    expect(folios.size).toBe(2);
    for (const t of parsed.transactions) {
      if (t.sourceReference?.startsWith('PCRV12-EXTRA')) {
        expect([...folios][1] === t.folioNumber || [...folios][0] === t.folioNumber).toBe(true);
      }
    }
    expect(parsed.holdings.length).toBe(2);
  });
});

describe('II-PC3-C1 — real-variant fixture pack manifest sanity', () => {
  it('every declared real-variant fixture file actually exists on disk (pack completeness)', () => {
    const ids = [
      'pc3rv-q01-baseline-multi-amc-multi-folio', 'pc3rv-q02-encrypted-duplicate-of-q01', 'pc3rv-q03-two-folios-fifo-scope',
      'pc3rv-q04-monthly-delta', 'pc3rv-q06-sip-rich-skipped-month', 'pc3rv-q07-transaction-rich',
      'pc3rv-q08-reconciliation-mismatch', 'pc3rv-q09-continuation-amc-transition', 'pc3rv-q10-malformed-negative',
      'pc3rv-q11-fee-evidence', 'pc3rv-q12-continuation-stress',
    ];
    for (const id of ids) {
      expect(existsSync(join(PACK_DIR, `${id}.pdf`)), `${id}.pdf must exist`).toBe(true);
      expect(existsSync(join(PACK_DIR, `${id}.expected.json`)), `${id}.expected.json must exist`).toBe(true);
    }
    // Q05 deliberately reuses Q04's PDF (exact reimport) — no separate file.
  });

  it('no fixture directory contains a real 10-char alphanumeric PAN pattern in raw .txt form (synthetic-only guard)', () => {
    const files = readdirSync(PACK_DIR).filter((f) => f.endsWith('.txt'));
    for (const f of files) {
      const text = readFileSync(join(PACK_DIR, f), 'utf8');
      const pans = text.match(/PAN:\s*([A-Z0-9]{10})/g) ?? [];
      for (const p of pans) expect(p).toMatch(/PCRVQ|PCQAL/); // this pack's synthetic PAN prefix, or the golden-fixture probe's shared prefix — never a plausible real PAN series code
    }
  });
});
