// R4 — 50-case independent certification harness (spec sections 71-72,
// 90). This test:
//   1. Loads scripts/ii-r4-certification/cases.json (the shared input,
//      generated by a pure-JS generator that imports no production code).
//   2. Computes each case's result using the REAL PRODUCTION engines
//      (direct imports — this is the only place in the certification
//      pipeline production code is invoked).
//   3. Loads scripts/ii-r4-certification/oracle_results.json (pre-computed
//      by the INDEPENDENT Python oracle, scripts/ii_r4_independent_reconciliation.py,
//      which imports nothing from production).
//   4. Asserts every case's production result matches the oracle result
//      within the documented tolerance (spec section 78), and writes a
//      full comparison table to comparison_report.json for
//      R4_50_CASE_CALCULATION_CERTIFICATION.md to consume.
//
// Tolerances (defined BEFORE reviewing results, per spec section 78):
//   currency values      <= 0.01 (absolute)
//   NAV-derived / CAGR    <= 0.000001 (absolute rate)
//   XIRR                  <= 0.000001 (absolute annual rate)
//   TWRR                  <= 0.000001
//   risk metrics          <= 0.000001 where deterministic
//   weights / blended     <= 0.000001

import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import path from 'path';
import { xirr } from '@/lib/engines/investment-intelligence/xirr';
import { cagr } from '@/lib/engines/investment-intelligence/navReturn';
import { twrr } from '@/lib/engines/investment-intelligence/twrr';
import { blendedBenchmarkReturn, activeReturn, type BenchmarkPeriodReturn } from '@/lib/engines/investment-intelligence/benchmarkEngine';
import { volatility, beta, trackingError, sharpeRatio, maxDrawdown } from '@/lib/engines/investment-intelligence/riskMetrics';

const CERT_DIR = path.resolve(__dirname, '../../scripts/ii-r4-certification');
const CASES_PATH = path.join(CERT_DIR, 'cases.json');
const ORACLE_RESULTS_PATH = path.join(CERT_DIR, 'oracle_results.json');
const COMPARISON_REPORT_PATH = path.join(CERT_DIR, 'comparison_report.json');

const TOLERANCE = 0.000001;

interface CaseRecord {
  id: string;
  family: string;
  description: string;
  input: Record<string, unknown>;
}
interface OracleRecord {
  id: string;
  family: string;
  result: Record<string, unknown>;
}

function d(s: string): Date {
  return new Date(s + 'T00:00:00.000Z');
}

interface RawPeriod {
  periodStart: string;
  periodEnd: string;
  weights: BenchmarkPeriodReturn['weights'];
  benchmarkReturnsByInstrument: Record<string, number>;
}

function computeProduction(c: CaseRecord): Record<string, unknown> {
  const input = c.input;
  switch (c.family) {
    case 'xirr': {
      const cashFlows = (input.cashFlows as Array<{ date: string; amount: number }>).map((cf) => ({ date: d(cf.date), amount: cf.amount }));
      const r = xirr(cashFlows);
      return r.status === 'ok' ? { status: 'ok', rate: r.rate } : { status: 'unavailable', reason: r.reason };
    }
    case 'cagr': {
      const r = cagr(input.beginningValue as number, d(input.beginningDate as string), input.endingValue as number, d(input.endingDate as string));
      return r.status === 'ok' ? { status: 'ok', pointToPointReturn: r.pointToPointReturn, cagr: r.cagr, years: r.years } : { status: 'unavailable', reason: r.reason };
    }
    case 'twrr': {
      const valuations = (input.valuations as Array<{ date: string; value: number }>).map((v) => ({ date: d(v.date), value: v.value }));
      const externalFlows = (input.externalFlows as Array<{ date: string; amount: number }>).map((f) => ({ date: d(f.date), amount: f.amount }));
      const r = twrr(valuations, externalFlows);
      return r.status === 'ok' ? { status: 'ok', twrr: r.twrr, subPeriodCount: r.subPeriods!.length } : { status: 'unavailable', reason: r.reason };
    }
    case 'blendedBenchmark': {
      const periods: BenchmarkPeriodReturn[] = (input.periods as RawPeriod[]).map((p) => ({
        periodStart: d(p.periodStart),
        periodEnd: d(p.periodEnd),
        weights: p.weights,
        benchmarkReturnsByInstrument: p.benchmarkReturnsByInstrument,
      }));
      const r = blendedBenchmarkReturn(periods);
      return { status: r.status, blendedReturn: r.blendedReturn, coveragePct: r.coveragePct, reason: r.reason };
    }
    case 'activeReturn': {
      const r = activeReturn(input.portfolioMetric as number, input.benchmarkMetric as number, input.metricFamily as 'TWRR' | 'CAGR' | 'POINT_TO_POINT');
      return r.status === 'ok' ? { status: 'ok', activeReturn: r.activeReturn } : { status: 'unavailable', reason: r.reason };
    }
    case 'riskBundle': {
      const fund = input.fundReturns as number[];
      const bench = input.benchReturns as number[];
      const ppy = input.periodsPerYear as number;
      const rf = input.annualisedRiskFreeRate as number | undefined;
      const vol = volatility(fund, ppy);
      if (vol.status !== 'ok') return { status: 'unavailable', reason: vol.reason };
      const b = beta(fund, bench);
      const te = trackingError(fund, bench, ppy);
      const sharpe = sharpeRatio(fund, ppy, rf);
      // Independently-comparable max drawdown: build a cumulative-wealth
      // series from the fund's OWN periodic returns (matching the
      // oracle's construction exactly) rather than requiring a separate
      // dated valuation series for this synthetic risk-bundle case.
      const wealth: Array<{ date: Date; value: number }> = [{ date: new Date(2020, 0, 1), value: 1 }];
      fund.forEach((r, i) => wealth.push({ date: new Date(2020, i + 1, 1), value: wealth[wealth.length - 1].value * (1 + r) }));
      const dd = maxDrawdown(wealth);
      return {
        status: 'ok',
        annualisedVolatility: vol.value!.annualisedVolatility,
        beta: b.status === 'ok' ? b.value!.beta : null,
        trackingError: te.status === 'ok' ? te.value!.trackingError : null,
        sharpe: sharpe.status === 'ok' ? sharpe.value!.sharpe : null,
        maxDrawdown: dd.status === 'ok' ? dd.value!.maxDrawdown : null,
      };
    }
    default:
      return { status: 'unavailable', reason: 'UNKNOWN_FAMILY' };
  }
}

function fieldsForFamily(family: string): string[] {
  switch (family) {
    case 'xirr':
      return ['rate'];
    case 'cagr':
      return ['pointToPointReturn', 'cagr'];
    case 'twrr':
      return ['twrr'];
    case 'blendedBenchmark':
      return ['blendedReturn', 'coveragePct'];
    case 'activeReturn':
      return ['activeReturn'];
    case 'riskBundle':
      return ['annualisedVolatility', 'beta', 'trackingError', 'sharpe', 'maxDrawdown'];
    default:
      return [];
  }
}

interface ComparisonRow {
  id: string;
  family: string;
  description: string;
  production: Record<string, unknown>;
  oracle: Record<string, unknown>;
  maxVariance: number;
  tolerance: number;
  result: 'PASS' | 'FAIL';
  note: string;
}

describe('R4 50-case independent certification', () => {
  let cases: CaseRecord[];
  let oracleResults: Map<string, OracleRecord>;
  const comparisonRows: ComparisonRow[] = [];

  beforeAll(() => {
    if (!existsSync(CASES_PATH) || !existsSync(ORACLE_RESULTS_PATH)) {
      throw new Error(
        'Certification fixtures not found. Run: node scripts/ii-r4-certification/generate_cases.mjs && python scripts/ii_r4_independent_reconciliation.py'
      );
    }
    cases = JSON.parse(readFileSync(CASES_PATH, 'utf-8'));
    const oracleArray: OracleRecord[] = JSON.parse(readFileSync(ORACLE_RESULTS_PATH, 'utf-8'));
    oracleResults = new Map(oracleArray.map((r) => [r.id, r]));
  });

  it('loads exactly 50 cases with matching oracle results', () => {
    expect(cases.length).toBe(50);
    expect(oracleResults.size).toBe(50);
  });

  it('every case: production result matches independent oracle within tolerance', () => {
    for (const c of cases) {
      const production = computeProduction(c);
      const oracle = oracleResults.get(c.id)!.result;
      const fields = fieldsForFamily(c.family);

      let passResult = true;
      let maxVariance = 0;
      let note = '';

      if (production.status !== oracle.status) {
        passResult = false;
        note = `status mismatch: production=${production.status} oracle=${oracle.status}`;
      } else if (production.status === 'unavailable') {
        // Both sides agree data is insufficient — the important agreement
        // for pathological/edge cases (TC046-050) is on STATUS, not reason
        // text (the two implementations use independently-worded reasons).
        note = `both unavailable (production reason=${production.reason}, oracle reason=${oracle.reason})`;
      } else {
        for (const field of fields) {
          const p = production[field] as number | null | undefined;
          const o = oracle[field] as number | null | undefined;
          if (p === undefined && o === undefined) continue;
          if (p === null || o === null || p === undefined || o === undefined) {
            if ((p ?? null) !== (o ?? null)) {
              passResult = false;
              note += `${field}: production=${p} oracle=${o} (one side null/undefined, other not); `;
            }
            continue;
          }
          const variance = Math.abs(p - o);
          maxVariance = Math.max(maxVariance, variance);
          if (variance > TOLERANCE) {
            passResult = false;
            note += `${field}: production=${p} oracle=${o} variance=${variance}; `;
          }
        }
      }

      comparisonRows.push({
        id: c.id,
        family: c.family,
        description: c.description,
        production,
        oracle,
        maxVariance,
        tolerance: TOLERANCE,
        result: passResult ? 'PASS' : 'FAIL',
        note,
      });
    }

    writeFileSync(COMPARISON_REPORT_PATH, JSON.stringify(comparisonRows, null, 2));

    const failures = comparisonRows.filter((r) => r.result === 'FAIL');
    if (failures.length > 0) {
      console.error('CERTIFICATION FAILURES:', JSON.stringify(failures, null, 2));
    }
    expect(failures).toEqual([]);
    expect(comparisonRows.filter((r) => r.result === 'PASS').length).toBe(50);
  });
});
